### ISSUE TITLE
trying to catch a defer that propagates an error -> Segmentation fault

### ISSUE THREAD

**Issue by kuche1** [vlang/v#10265]
**V doctor:**
```
OS: linux, "Artix Linux"
Processor: 12 cpus, 64bit, little endian, AMD Ryzen 5 3600 6-Core Processor
CC version: cc (GCC) 11.1.0

getwd: /home/me/coding/v
vmodules: /home/me/.vmodules
vroot: /home/me/Programs/v
vexe: /home/me/Programs/v/v
vexe mtime: 2021-05-30 08:16:49
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 e4f6369.ba86d61

Git version: git version 2.31.1
Git vroot status: weekly.2021.21-57-gba86d619
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81
``` 
**OS:** 

**What did you do?**
`v test_err.v`
```
fn main(){
	test1() or{
		println('an err occured: $err')
	}
}

fn test1() ? {
	println(1)
	defer{
		println(-1) // last
	}

	println(2)
	defer{
		println(-2) // second
	}

	println(3)
	defer{
		println(-3) // first
		an_error() ?
	}
}

fn an_error()?{
	return error('some error')
}
```

**What did you expect to see?**
a compiled binary

 
**What did you see instead?**
`Segmentation fault`

**Comment by kuche1** [comment]
this may be related to https://github.com/vlang/v/issues/10266

**Comment by UweKrueger** [comment]
The issue can actually be triggered by a much simpler program:
```v
fn main() {
    defer {
        return
    }
}
```
And here the fundamental problem becomes visible:

- statements in `defer` blocks are supposed to be executed after the return value has been calculated but before the program really returns
- they are not supposed to create a return value (because that exists already) - not even by error propagation
- they should not return themselves (because there might be other `defer` blocks to be executed

From this perspective `return` statements and error propagation inside `defer` blocks should probably be forbidden.
