### ISSUE TITLE
[security] some OS module functions are vulnerable to TOCTOU attacks -- V should warn programmers about that

### ISSUE THREAD

**Issue by bstnbuck** [vlang/v#10268]
Many OS module functions use POSIX C functions which have been shown to allow TOCTOU attacks. 
A description of TOCTOU can be found here: https://cwe.mitre.org/data/definitions/367.html or here https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use. 
Almost all programming languages are vulnerable to this kind of vulnerability (also Go, Python, C (especially)). **V should warn programmers (e.g. in docs) about these vulnerabilities**. However, functions like is_readable() should not be used by programmers in productive. Instead the following can be used.

do **not** use this:
```v
if os.is_readable("file"){
	mut f := open(path string) ?
        <do something with file>
	f.close()
}
```

**use** this instead:
```v
mut f := open(path string) or {
	return "file not readable"
}
<do someting with file>
f.close()
```

**Comment by spytheman** [comment]
Hm, how is using open inside such a function any better?

After calling is_readable() (which takes a path, and returns a bool), there is still a short time window, where the file at that path could have been changed, before it is actually used (which presumably will open it again).

**Comment by dumblob** [comment]
I agree with @spytheman - this is about educating end users (e.g. by mentioning TOCTOU in doc of `is_readable()` suggesting `open()` and checking the error). *V* lib is a **thin** wrapper around os-specific etc. APIs and **must not** diverge from the semantics of those APIs otherwise it'd be a catastrophe (nobody would know how the *V* API relates to the os-specific APIs and would need to read source code all the time - that's always the very worst thing a language/library could do, believe me).

So to wrap up - this is solely about documentation which really should warn about this vulnerability at every such function. Nothing else to do here.

----

Btw. I've actually done some measurements on this topic some years ago - find them in https://github.com/dumblob/dao/pull/1#issuecomment-485960161 . Maybe the "slow down" of factor ~2.25 in exchange for atomicity could be mentioned in the doc to give an impression how it affects real apps.

**Comment by bstnbuck** [comment]
I accept. The example of me was unfortunately very poorly chosen. Of course there is no difference (except for speed) with is_readable(). It is the programmer alone who makes it. 
V should, as @dumblob said, warn programmers about this. Suggestion would be 
1. an enumeration of the functions to be avoided in the Docs to hold and 
2. in each case with the description of the function this to note.

What do you guys say?
By the way, I have improved the original bug report a bit :)

**Comment by dumblob** [comment]
IMHO it has to be mentioned in **each case** - but rather as a big colorful warning triangle with reference to some footnote or alike describing it in more detail.

**Comment by dumblob** [comment]
@bstnbuck could you check whether the docs mention it on all places where you would expect it?

**Comment by bstnbuck** [comment]
@dumblob there seem to be no warnings made. 
I will address this and give a warning in `https://github.com/vlang/v/blob/master/vlib/os/README.md` and at the functions that are typical for it (`is_writable`, `is_readable`, `is_executable`, `is_link`, (any more?))

**Comment by dumblob** [comment]
> (`is_writable`, `is_readable`, `is_executable`, `is_link`, (any more?))

I think that is it for the beginning. Maybe `grep -Ei 'write|read|open|stat|file' ./v_upstream_git` will reveal something more (and maybe even some bugs)...

**Comment by bstnbuck** [comment]
@dumblob done! :)

**Comment by dumblob** [comment]
Awesome, thanks a lot @bstnbuck !
