### ISSUE TITLE
dead lock error mesage like in Go

### ISSUE THREAD

**Issue by kahsa** [vlang/v#10340]

**Comment by UweKrueger** [comment]
Feature request that contain "... like in ..." without any text describing what feature exactly is desired and why it is needed should normally be ignored. However I'll try to give some answers anyway:

- What `Go` does in some cases of deadlocks is producing a fatal *runtime* error. This is not more acceptable in production code than waiting indefinitely.
- Not all deadlocks are detected in Go. Look at this code
  ```go
    package main
    
    func main () {
        ch := make(chan string, 0)
        go func (c chan string) {
            if 0 != 1 { return }
            c <- "never reached"
        }(ch)
        go func () {
            a := 0
            for {
                a++
            }
        }()
        println(<- ch)
    }
  ```
  Since the for loop is always running no error message will be printed, but the program runs forever. It's actually no *deadlock* detection but a *no thread running* detection.
- Doing such a kind of detection requires some kind of supervising. Since (unlike Go) V does not run a separate scheduler in user space implementing such supervision would mean a significant impact. Given the low benefit I think it is not worth it.

**Comment by dumblob** [comment]
Related: https://github.com/vlang/v/issues/6156 .
