### ISSUE TITLE
expression evaluation compiler error for some combinations

### ISSUE THREAD

**Issue by DevrosTheOne** [vlang/v#10425]
**V version:** 
V full version: V 0.2.2 7878bad.6761697
**OS:** 
OS: macos, macOS, 11.4, 20F71
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 12.0.5 (clang-1205.0.22.9)
**What did you do?**
```v
// ints and a float
x, y, z := 10, 5, 3.3
println( ' x $x ${typeof(x).name}, y $y ${typeof(y).name}, z ${z} ${typeof(z).name}')

println( ( x - y ) / z )
println( ( x - y ) / 3.3 ) // error: mismatched types `int` and `float literal`
println( ( 10 - 5 ) / z )
println( ( 10 - 5 ) / 3.3 )
println( ( 10 - y ) / z )
println( ( 10 - y ) / 3.3) // error: mismatched types `int` and `float literal`
println( ( x - 5 ) / z )
println( ( x - 5 ) / 3.3 ) // error: mismatched types `int` and `float literal`

//floats and a int
a, b, c := 10.1, 5.2, 3

println(( a - b ) / c)
println(( a - b ) / 3)
println(( 10.1 - b) / c)
println(( 10.1 - b) / 3)
println(( 10.1 - 5.2) / c)  // error: mismatched types `float literal` and `int`
println(( 10.1 - 5.2) / 3)
println(( a - 5.2) / c)
println(( a - 5.2) / 3)
```
**What did you expect to see?**
 x 10 int, y 5 int, z 3.3 f64
1.5151515151515151
1.5151515151515151
1.5151515151515151
1.5151515151515151
1.5151515151515151
1.633333333333333
1.633333333333333
1.633333333333333
1.633333333333333
1.633333333333333
1.633333333333333
1.633333333333333
 
**What did you see instead?**

```
evalerror.v:6:10: error: mismatched types `int` and `float literal`
    4 | 
    5 | println( ( x - y ) / z )
    6 | println( ( x - y ) / 3.3 ) // error: mismatched types `int` and `float literal`
      |          ~~~~~~~~~~~~~~~
    7 | println( ( 10 - 5 ) / z )
    8 | println( ( 10 - 5 ) / 3.3 )
evalerror.v:10:10: error: mismatched types `int` and `float literal`
    8 | println( ( 10 - 5 ) / 3.3 )
    9 | println( ( 10 - y ) / z )
   10 | println( ( 10 - y ) / 3.3) // error: mismatched types `int` and `float literal`
      |          ~~~~~~~~~~~~~~~~
   11 | println( ( x - 5 ) / z )
   12 | println( ( x - 5 ) / 3.3 ) // error: mismatched types `int` and `float literal`
evalerror.v:12:10: error: mismatched types `int` and `float literal`
   10 | println( ( 10 - y ) / 3.3) // error: mismatched types `int` and `float literal`
   11 | println( ( x - 5 ) / z )
   12 | println( ( x - 5 ) / 3.3 ) // error: mismatched types `int` and `float literal`
      |          ~~~~~~~~~~~~~~~
   13 | 
   14 | //floats and a int
evalerror.v:21:9: error: mismatched types `float literal` and `int`
   19 | println(( 10.1 - b) / c)
   20 | println(( 10.1 - b) / 3)
   21 | println(( 10.1 - 5.2) / c)  // error: mismatched types `float literal` and `int`
      |         ~~~~~~~~~~~~~~~~~
   22 | println(( 10.1 - 5.2) / 3)
   23 | println(( a - 5.2) / c)
```

**Comment by shadowninja55** [comment]
seems we've been having some issues lately with float literal vs actual float. i won't assign myself yet, but i'll take a look into what's happening in the checker.

**Comment by UweKrueger** [comment]
This is not a bug. The problem with `(x - y) / 3.3` is that `3.3` has an *undecided* type but `(x - y)` has the defined type `int` (32 bit).
The compiler only tries to promote an undecided type to a defined one and never vice versa. So the compiler tries to convert this undecided float `3.3` to an `int` - and that's not possible.
If both types are undecided - like in `10 / 1.3` the more powerful type is assumed - that would be "undecided float" (which defaults to `f64` when used in an assignment. The same if both are decided `int(10) / f64(1.7)` - that's promoted to `f64`.
Another question is what should happen with `int(10) / f32(1.3)`. There is a loss in precision so this was originally forbidden.
Due to coplaints by some users that wanted to work with `f32` and `int` interchangeably the rule was later relaxed.
