### ISSUE TITLE
skip attribute used for ORM and JSON

### ISSUE THREAD

**Issue by odunboye** [vlang/v#10476]
Currently building web services with vweb, this requires separate `skip` attribute for ORM and JSON on a struct. ORM and JSON both use `skip` attribute to bypass generating code for a field, there by preventing code generation for both in case you want one. Proposing `skip: [json, orm, xml]`

**Comment by rcorre** [comment]
This would be nice -- one of the nice things about an ORM is potentially sharing the same types between the DB and the API, but you might store DB fields that you don't want to return in responses (or visa-versa).

What about `[skip: json,xml,orm]`? That looks a little cleaner to me (no nested brackets) and would be easier for the handling code to parse (since there aren't array attributes right now).

**Comment by walkingdevel** [comment]
Now you can use `[json: '-']` for skipping JSON fields and `[sql: '-']` for ORM. See the example: https://vosca.dev/p/8729b27a91

**Comment by walkingdevel** [comment]
Fixed in b9f5cc830b0b0c84e5848f66d7a314532acfde6b and 9f118ba3f1d48c87890fa4647c091501fdf4624f.
