### ISSUE TITLE
can not cast generic type

### ISSUE THREAD

**Issue by lcddh** [vlang/v#10660]
```
struct Name<T> {
	v T
}

fn main() {
	pn := &Name<int>(0)
}
```
This should be supported, right?

**Comment by DevrosTheOne** [comment]
Syntax slightly wrong for creating a struct

```v
struct Name<T> {
	v T
}

fn main() {
	pn := Name<int>{0}
	println(pn)
}
```
output
Name<int>{
    v: 0
}

**Comment by lcddh** [comment]
sorry,I want to get a pointer to Name struct  and i want to set the variable to  zero.

**Comment by DevrosTheOne** [comment]
something like 
pn := &Name<int>{0}

**Comment by lcddh** [comment]
Yes, that initializes a pointer variable, but now I just want to initialize it to 0 and wait until I need it later to assign a value

**Comment by DevrosTheOne** [comment]
Discord V help forum better option for questions. 
```v
struct Name<T> {
mut:
	v T
}

fn (mut name Name<int>) change_v(val int) {
	name.v = val
}

fn main() {
	mut pn := &Name<int>{0}
	pn.v = 123
	println(pn.v)
	pn.change_v(42)
	println(pn.v)
}
```

**Comment by DevrosTheOne** [comment]
Sorry.   Confused :confused:   'initialize it to 0' 
Need more sample code.

**Comment by lucasrdrgs** [comment]
> Yes, that initializes a pointer variable, but now I just want to initialize it to 0 and wait until I need it later to assign a value

`pn := &Name<int>{0}` should work, though:

Try to run this:
```v
struct Name<T> {
    v T
}
pn := &Name<int>{0}
pn.v
```
And you should get 0 as output.

If that's not what you want, what is it? Setting the variable `pn` to 0? In this case, I'd rather not, since according to the [docs](https://github.com/vlang/v/blob/master/doc/docs.md#structs-with-reference-fields): "Zero-value references, or nil pointers, will NOT be supported in the future".
