### ISSUE TITLE
Compiler crash on asm bloc

### ISSUE THREAD

**Issue by bumbread** [vlang/v#10710]
**V version:** V 0.2.2 `47bf644`, timestamp: 2021-07-09 03:27:16 +0300
**OS:** Linux 5.8.0-59-generic #66~20.04.1-Ubuntu

**What did you do?**

```
fn main() {
  mut n := 0
  n += 1
  if n != 2 {

    asm x64 {
      jmp main
    }
    
  }
  println('$n')
}
```

**What did you expect to see?**

Either:
- A message that says that I can not jump to functions from assembly blocks; or
- The program successfully printing `2` to the console
 
**What did you see instead?**

```sh
$ v run main.v
Segmentation fault (core dumped)
```

**Comment by danieldaeschle** [comment]
@crthpl

**Comment by crthpl** [comment]
There are several problems with your code:
a) you have to use `jmp main__main`, because the generated C code uses that for the function names (`modulename__functionname`)
b) `n` will always get reset to 0 at the start, causing an infinite recursion and a stack overflow
c) you are doing `jmp main`, which does not do the pre-function call initialization, you should use `call main__main`

**Comment by danieldaeschle** [comment]
Using `main__main` looks strange to me. Would it work for the native backend?
Could we translate main to main__main? and module.method to module__method?
