### ISSUE TITLE
Parallelization SIMD support like un JuliaLang

### ISSUE THREAD

**Issue by acostaja** [vlang/v#1079]
Please add support to vectorial (parallelized) instructions with something like in Julia Lang with it's "." Dot-syntax 
This opens opportunities in HPC/GPGPU/ML where this is very useful for SIMD optimization. Also include some syntax/keyword to enable such features being complied like declaration to CUDA << >> non STD C syntax being generated when compiled/translated to/from CUDA, HIP/opencl

**Comment by medvednikov** [comment]
Yes, this would be nice.

**Comment by dumblob** [comment]
Any special syntax for SIMD parallelization will fall short rather quickly (and has too many shortcomings). From my experience the best way is to stick with intrinsics (as mentioned in https://github.com/vlang/v/issues/1868#issuecomment-528559933 ) as this approach is by definition extendable and because they already exist e.g. in C++, there is no need to reinvent the wheel.
