### ISSUE TITLE
import module written in golang or python directly

### ISSUE THREAD

**Issue by robotcc** [vlang/v#10828]
Then V can stand on the shoulders of giants!

**Comment by JalonSolov** [comment]
As long as they have a C interface, you can wrap calls to them as you would with any C library.  Otherwise, I don't think this will ever happen.  Python is a mess (even between it's own versions), and Go is too specialized to Go.

Instead, there are 2 projects just started - `py2v` and `go2v`.  Both are "transpilers" - they turn the original code into V code.  Neither one very usable, yet, but started.

https://github.com/vlang/py2v
https://github.com/vlang/go2v

Early attempt at go2v:  https://github.com/crthpl/go2v
