### ISSUE TITLE
Memory management failure in a simple program

### ISSUE THREAD

**Issue by vtereshkov** [vlang/v#10903]
**V version:** V 0.2.2 06de9c7, timestamp: 2021-07-21 23:56:00 +0300
**OS:** Windows 10

**What did you do?**
Wrote the following code and compiled it with `-autofree` and without it:
```
fn main() {
  mut b := [5, 6, 7]
  {
    a := [1, 2, 3]
    b = &a
  }
  println(b)
}
```

**What did you expect to see?**
Either `[1, 2, 3]`, or a compilation error if `b = &a` is an invalid assignment.
 
**What did you see instead?**
Without `-autofree`: `[1, 2, 3]`
With `-autofree`:
```
Unhandled Exception 0xC0000374
C:/Users/vtere/AppData/Local/Temp/v/test.5468496854535777885.tmp.c:6487: at print_backtrace_skipping_top_frames_tcc: Backtrace
C:/Users/vtere/AppData/Local/Temp/v/test.5468496854535777885.tmp.c:6454: by print_backtrace_skipping_top_frames
C:/Users/vtere/AppData/Local/Temp/v/test.5468496854535777885.tmp.c:6512: by unhandled_exception_handler
7fffb92c8a4c : by ???
```
The generated C code seems to perform neither lifetime analysis, nor reference counting. Instead it just deallocates every object when leaving the scope:
```
VV_LOCAL_SYMBOL void main__main(void) {
	Array_int b = new_array_from_c_array(3, 3, sizeof(int), _MOV((int[3]){5, 6, 7}));
	{
		Array_int *a = HEAP(Array_int, (new_array_from_c_array(3, 3, sizeof(int), _MOV((int[3]){1, 2, 3}))));
		array _sref66 = (b); // free array on re-assignment2
		b = *&(*(a));
		array_free(&_sref66);
		array_free(&a); // autofreed var main false
	}
	string _t1 = Array_int_str(b); println(_t1); string_free(&_t1);
	;
	array_free(&b); // autofreed var main false
}

```

**Comment by medvednikov** [comment]
Fixed:
```
cannot assign a reference to a value
```

This is a warning for now (won't compile with -prod), will make it an error in a week.

**Comment by Congyuwang** [comment]
So, what is the memory management model, really? I am interested in V. I like its goal to remain a simple, maintainable language, which is great! However, I don't read from any website, readme, tutorial, that talks about the memory management model. It just says that it is safe, but how? Instead, I see in issues various kind of memory leak bug fixes. Really, so, is it safe because it is actively patched here and there whenever a memory bug is detected. not safe in the sense that it is logically guaranteed?
