### ISSUE TITLE
Buffer allocate question

### ISSUE THREAD

**Issue by robotcc** [vlang/v#11001]
```v
pub fn (mut sock NanoSocket) nn_recv() ?voidptr {
	mut buf := &byte(0)
	mut bsize := size_t(0)
	res := C.nn_recv(sock.native_socket, unsafe{ &voidptr(&buf) }, &bsize, 0)
	if res < 0 {
		errmsg := unsafe{C.nn_strerror(C.nn_errno())}
		return error(unsafe{errmsg.vstring()})
	}
	return buf
}
```
I don't know the size of buffer, how to init buffer to be able to recv message, and how to free buffer.
And I don't want to do all the did with an additional memcopy.

**Comment by div72** [comment]
@robotcc You can allocate memory in V with `malloc` and deallocate with `free`. 

Also you don't have to use voidptrs gor everything if you specify the proper V types in your `fn C.foo` decls.

**Comment by robotcc** [comment]
@div72 Thanks! I don't want to do malloc and free because of the additional memcopy.

**Comment by div72** [comment]
@robotcc I would have to look at the C functions you used to be certain, but most likely you can already pass a buffer to your function. So you won't need to do any `memcpy`s.

**Comment by robotcc** [comment]
C.nn_recv malloc memory and transfer it out. At second thought, It's not standard operation and should not be handled by the runtime. @div72

**Comment by div72** [comment]
@robotcc I really don't understand what do you mean. Allocations are always done at runtime regardless if it's on stack or heap.

I assume you're trying to use nanomsg, according to the documentation you can either allocate a buffer yourself(with `malloc` so that you can return the ptr, and free it with `free` when you're done) or let the library allocate(as you seem to do) the memory for you. The size of the buffer is res, and when you want to free the memory your library has a function to do so(nn_freemsg).

If you prefer to not deal with a pointer and length, you could cast it to an V array:
```v
pub fn (mut sock NanoSocket) nn_recv() ?[]byte {
	mut arr := []byte{}
	res := C.nn_recv(sock.native_socket, &arr.data, C.NN_MSG, 0)
	if res < 0 {
		errmsg := unsafe{C.nn_strerror(C.nn_errno())}
		return error(unsafe{errmsg.vstring()})
	}
	arr.len = res
	return arr
}
```
I would recommend not using autofree and freeing arr.data with your C.nn_freemsg function when you're done with the arr. And the data itself will not be copied itself in this instance.

**Comment by robotcc** [comment]
Thanks a lot!

**Comment by robotcc** [comment]
By the way, Is there anything capable with array but like smart point  which count the references and automatic free at no reference?

**Comment by JalonSolov** [comment]
That is supposed to be part of `autofree` once it is fully implemented, but it doesn't work yet.

**Comment by robotcc** [comment]
Looking forward to it. That's great!
