### ISSUE TITLE
Blog application tutorial triggering C error this should never happen

### ISSUE THREAD

**Issue by trenta3** [vlang/v#11012]
**V doctor:**
```
OS: linux, Linux version 5.12.7-200.fc33.x86_64 (mockbuild@bkernel02.iad2.fedoraproject.org) (gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1), GNU ld version 2.35-18.fc33) #1 SMP Wed May 26 13:15:51 UTC 2021
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
CC version: cc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)

getwd: /home/trenta3/blog
vmodules: /home/trenta3/.vmodules
vroot: /home/trenta3/bin/v
vexe: /home/trenta3/bin/v/v
vexe mtime: 2021-07-27 06:11:57
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 cb7be87

Git version: git version 2.31.1
Git vroot status: Error: fatal: non è un repository Git (né lo è alcun genitore fino al punto di mount /)
Mi fermo al limite del filesystem (l'opzione GIT_DISCOVERY_ACROSS_FILESYSTEM non è impostata).
.git/config present: false
thirdparty/tcc status: thirdparty-linux-amd64 333c14de
```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg blog.v`
```v
module main

import sqlite
import vweb

struct App {
	vweb.Context
pub mut:
	db sqlite.DB
}


fn main() {
	mut app := App{}
	app.init_server()
	vweb.run(app, 8081)
}


pub fn (mut app App) init_server() {
	app.db = sqlite.connect(":memory:") or { panic(err) }
	sql app.db {
		create table Article
	}

	first_article := Article{
		title: "Hello, world!"
		text: "V is great."
	}

	second_article := Article{
		title: "Second post"
		text: "Hm.. what should I write about?"
	}

	sql app.db {
		insert first_article into Article
		insert second_article into Article
	}
}

["/index"]
pub fn (app App) index() vweb.Result {
	articles := app.find_all_articles()
	return $vweb.html()
}

struct Article {
	id int [primary; sql: serial]
	title string
	text string
}

pub fn (app &App) find_all_articles() []Article {
	return sql app.db {
		select from Article
	}
}

```

**What did you expect to see?**

I was following https://github.com/vlang/v/blob/master/tutorials/building_a_simple_web_blog_with_vweb/README.md and I expected to see the blog application running as it should

**What did you see instead?**
```
==================
/tmp/v/blog.12343783932069734705.tmp.c:25588: error: cannot convert 'struct main__App *' to 'struct main__App'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

**Comment by JalonSolov** [comment]
There are several problems here:

- You installed from what looks like a "weekly" zip.  That explains the SHA for V itself being 5 days old, as well as the error on the `Git vroot status` line output from `v doctor` (since the zip files don't include the `.git` subdir).  It is recommended to clone the repository instead of using one of the zip files, and do frequest `v up` commands - especially if you see an error.  It should always be "See an error, `v up` and try again."

- You don't need to build V with debug info then use the debug version to compile, unless you are trying to track down an error in V itself. `v .` would be enough.

- It would not have compiled correctly, because you explicitly gave the blog.v file to compile, but there are 2 files in the directory.  The correct way to compile so that V picks up all the files would be `v .`

- Even if it had compiled, it wouldn't have run, as all you told it to do was compile.  You have to include the `run` command to make it run the executable after compiling.  Otherwise, build it then run it manually.

All of that said, I just tried the same compile here, using the latest version of V (`V 0.2.2 6068777`), and it compiled clean:
```
[jamie@5950x blog]$ v .
/home/jamie/git/v/thirdparty/cJSON/cJSON.o not found, building it in /home/jamie/.vmodules/cache/2f/2f8ad8f09cf674acb675bb6d0ab69288.o ...
[jamie@5950x blog]$
```

**Comment by trenta3** [comment]
Hi! Thank you for the very detailed reply. I will try to answer to all points:

I reported the problem because of what was written when the error popped up:
```
builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.
```
I then followed by running `v bug blog.v`.
I think it would be better to remind the user (especially for newbies like me) to try first `v up`.

Concerning point (2) I actually ran `v run blog.v`, and I don't know why in the report the command ` v -g -o vdbg cmd/v && vdbg blog.v` shows up, since I also did not know about the `vdbg` executable (I'm just getting started).
For point (3) there were indeed two files in the folder, but if you notice in the listing above, I have copied the `struct Article` definition from `article.v` to `blog.v` so that it all fits in one file, since I was not sure (and still I am) that calling `v bug .` would have reported the entire folder.

After your suggestions I've finally managed to run the examples, so this issue can be closed.

**Comment by JalonSolov** [comment]
Thanks for the details you supplied, and yes, please do report any time you see the `C error` type message.  That is always something that should be fixed.  It just so happens that it already has been, since the weekly zip was created.

I agree that is should be made more obvious that cloning the repo is preferred, at least for now.  We _will_ get things to the point that installing from a zip file is better, but V is still changing too rapidly for this to be the best method for now.

It may be that `v bug` is the thing that gave the different command - I haven't used it before, so haven't run into this, but that is likely the source.

I didn't know you had combined the files, which is why I mentioned the difference in specifying a single file vs `.` for the whole current directory.  Documented here:  https://github.com/vlang/v/blob/master/doc/docs.md#running-a-project-folder-with-several-files

I'm glad things are working for you now.  Welcome to V!  :-)
