### ISSUE TITLE
Choose and implement a regex implementation

### ISSUE THREAD

**Issue by watzon** [vlang/v#1114]
v seems to be missing an implementation of regular expressions, which are very handy to have for any language, and I think most people would agree are necessary for completeness. There are several flavors to choose from, but I personally like PCRE.

We could of course just wrap c's `std::regex`, but if the goal is to eventually have no c dependencies rolling a custom implementation would make the most sense.

**Comment by joe-conigliaro** [comment]
I started doing an implentation of re2 in V but we are lacking a lot of unicode conversion functions which need to be implemented first.
Someone made this V wrapper around PCRE lib: https://github.com/ShellBear/v-regex

**Comment by ntrel** [comment]
> if the goal is to eventually have no c dependencies 

I think this goal is for embedded systems to avoid libc. (Even then, partial libc may be OK). I'm not sure that regex is an important use case for embedded systems, but if so then we should port an existing regex library rather than developing our own. One reason to have our own is when compile-time function execution is powerful enough to compile a regex pattern at compile-time. This saves compiling a pattern at runtime.

**Comment by joe-conigliaro** [comment]
@ntrel I agree we should port re2 I think

**Comment by joe-conigliaro** [comment]
Over then next few days I'm going to begin porting re2 to v specifically the golang implementations

**Comment by lutherwenxu** [comment]
Work has already started in `vlib/regex`!
