### ISSUE TITLE
dont require capital letters for struct names

### ISSUE THREAD

**Issue by maddanio** [vlang/v#11256]
Hello, I am very excited about v, I think it does a ton of things right, but I was just trying my first program when i was shocked that it forces me to capitalize struct names. Is there a functional reason for that? if not please please please lift this restriction. I absolutely detest capitalized type names. I dont judge others for it, but I dont like it in my code and find it hard to read, and I am also very annoyed at programs forcing style on me (think go with its brackets). this is such a strong emotional rejection that I might consider forking v just for that :).

keep up the good work!

**Comment by maddanio** [comment]
similarly for requiring snake case in other places: while I like snake-case, I think its wrong for a language to enforce style.

**Comment by maddanio** [comment]
also: why are names starting with underscored reserved? i find them to be a nice short way of signifying private fields

**Comment by medvednikov** [comment]
This makes the parser simpler and faster. It knows it's a type just by looking at the first character.

**Comment by medvednikov** [comment]
Fields are private by default, as opposed to `pub` fields. _names are reserved for internal automatically generated code to avoid name clashes.

**Comment by Larpon** [comment]
V is very opinionated.

The main reasons for the chosen syntax is readability and maintainability.

To write maintainable software you need as little difference as possible between code bases and all programmers have their own style. This is a real world problem that V works around very simple by only allowing (and enforcing, via vfmt) one code style. It has other nice benefits too but readability is the major reason. You can distinct all types from eachother quite easily. You'll have to get used to it because not much will change in this area.

Code is read many more times than it is written. So readability a cross code bases is really important.

**Comment by maddanio** [comment]
hmm, camel case has been shown to be much harder to read than snake-case which is why c++ uses the _t suffix for types, and its a bit hard to being forced to do so, but sure, the simplicty of the parser argument wins me over (I dont think it improves readabilty though :)).

**Comment by maddanio** [comment]
> V is very opinionated.
> 
> The main reasons for the chosen syntax is readability and maintainability.
> 
> To write maintainable software you need as little difference as possible between code bases and all programmers have their own style. This is a real world problem that V works around very simple by only allowing (and enforcing, via vfmt) one code style. It has other nice benefits too but readability is the major reason. You can distinct all types from eachother quite easily. You'll have to get used to it because not much will change in this area.
> 
> Code is read many more times than it is written. So readability a cross code bases is really important.

and how was the concensus on style reached? camel case and brackets on the same line imho make code harder to read, not easier. did you question people about readability or consult studies?

**Comment by JalonSolov** [comment]
If you don't like V, you probably don't like Go, either.  It is another language that is highly opinionated about formatting, naming conventions, etc.

**Comment by Larpon** [comment]
> 
> and how was the concensus on style reached? camel case and brackets on the same line imho make code harder to read, not easier. did you question people about readability or consult studies?

It has been mostly set in stone since the open source release, so it's a brainchild of  @medvednikov . Small things are sometimes discussed on Discord or voted for on e.g. Twitter. Beside that it has just "always been" like it is now. People get used to it. I got used to it when realising the huge benefit of codebases that is easy to read through because there's no style changes, only things and constructs you're used to see in other codebases. Try doing that with C++.
