### ISSUE TITLE
Regex causing segfault

### ISSUE THREAD

**Issue by SurmanPP** [vlang/v#11366]
**V version:** 227d12f
**OS:** Pop Os

**What did you do?**
import regex
fn main() {
	query := '+{3}(.*){3}'
	text := '+++pippo+++\n elvo +++ pippo2 +++'
	mut re := regex.regex_opt(query) or { panic(err) }
	res_str := re.find_all_str(text)
	println(res_str)
}

**What did you expect to see?**
"['+++pippo+++', '+++ pippo2 +++']" as output
 
**What did you see instead?**
V panic: substr(0, 4) out of bounds (len=3)
v hash: 227d12f
/tmp/v/main.4208415553534628165.tmp.c:6056: at _v_panic: Backtrace
/tmp/v/main.4208415553534628165.tmp.c:8934: by string_substr
/tmp/v/main.4208415553534628165.tmp.c:12460: by regex__RE_find_all_str
/tmp/v/main.4208415553534628165.tmp.c:12591: by main__main
/tmp/v/main.4208415553534628165.tmp.c:12955: by main

**Comment by jcweaver997** [comment]
This is kinda odd. There are a few issues with your query, but there are also issues with V's regex.
For a quick fix, you can use the query `[\+]{3}.*[\+]{3}` which gives your expected result of `['+++pippo+++', '+++ pippo2 +++']`.

The big problem here is that V doesn't seem to differentiate between characters and quantifiers properly.
For example, using `\+\+\+\+` gives the result  `['+++', '+++', '+++', '+++']`. This is likely due to it mixing up the characters and quantifiers despite the leading backslash. For example, using the query `[+]{3}.*[+]{3}` with putting the '+' within square brackets seems to read it as a character despite not escaping it with a backslash

**Comment by penguindark** [comment]
@jcweaver997 please have a look at the fix.
Please remember that V regex is not PCRE regex, the base block is char not the sequence, this can result in different behaviour and in different response to the escaped chars.

**Comment by jcweaver997** [comment]
Tried it and it works perfectly @penguindark . 
No more seg fault, and it identifies quantifiers perfectly now.

I made a mistake in my post before which was made evident now that the quantifiers are read correctly. I was using '\+\+\+' but the backslash was being escaped in the string, and I needed to put '\\+\\+\\+'
Thanks for the fix!

**Comment by penguindark** [comment]
@jcweaver997 Tnx :)
Please have a look at the regex documentation: <https://github.com/vlang/v/tree/master/vlib/regex>
and remember to use the `raw` strings when you write the patterns like: `r"\+"`
