### ISSUE TITLE
Optional typing on variable declaration

### ISSUE THREAD

**Issue by cindRoberta** [vlang/v#11408]
Optional typing on variable declaration
```v
i int := 45


type Int_string = u8 | string

mut is Int_string := u8(77)
is = 'berg'
```

**Comment by JalonSolov** [comment]
Your syntax is incorrect, but it pretty much works when written properly.
```v
type Int_string = u8 | string

mut ik := Int_string(u8(77))
ik = 'berg'
println(ik)
```

**Comment by cindRoberta** [comment]
@JalonSolov why not use a left-hand/variable optional typing? all typed languages have it, inclusive Go, Zig and Rust

**Comment by JalonSolov** [comment]
V is none of those.  It figures it out from the type on the right-hand side of the`:=`, instead of you always having to type it.

It works for the most common types (`int`, `string`, `float`, etc.) without having to type out the type name, and it is simple enough to change the type explicitly if you need to do so.
