### ISSUE TITLE
Since there are no globals, and functions can't modify their arguments, there are only 2 ways to modify data concurrently

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#12]
1) Closures
```
mut a := 0
go fn() {
  lock { a++ }
}()
```

2) Receivers
```
mut foo := Foo{}
go foo.modify()

fn (foo mut Foo) modify() {
  lock {
    foo.bar++
  }
}
```

What do you think?

**Comment by PavelVozenilek** [comment]
Assuming `go` behaves as in the go language (I have only vague understanding of go):

```
mut a := 0
go fn() {
  lock { a++ }
}()

```

Isn't there good chance of  `a` going out of scope before the thread manages to modify it?

**Comment by ntrel** [comment]
So IIUC, mutating a local variable locally doesn't need locking. A closure has to lock before it can mutate a closed over variable. Doesn't the closure also have to lock to read that mutable variable? Or maybe V then makes local mutation need locking too because the variable is now shared across threads?

Also, is there a way to pass a mutable variable *or* an immutable variable to a function parameter (like D's `const`)? Such a parameter in V might need locking to read as it could be mutable (but the function can't modify it as it could be immutable).

**Comment by ntrel** [comment]
BTW, the mutable receiver docs don't use `lock`, is this a mistake?
```rust
fn (u mut User) register() {
	u.is_registered = true 
} 
```
Also, I saw https://github.com/vlang-io/V/commit/894db193325ac3f8ffcca1ea00bdd046b2b72edb, does this mean V will require locking for reading mutable data too?

**Comment by medvednikov** [comment]
This is not a concurrent example, so locking is not needed.

**Comment by ntrel** [comment]
Yes, so I assume mutable receiver methods will not be callable with `go` as a co-routine unless they use `lock`.

**Comment by medvednikov** [comment]
> Isn't there good chance of a going out of scope before the thread manages to modify it?

`a` escapes:

https://play.golang.org/p/AG9MHkb-W_3
