### ISSUE TITLE
$embed_file() not working properly

### ISSUE THREAD

**Issue by axetroy** [vlang/v#12090]
**V version:** V 0.2.4 77c18f4
**OS:** macOS

**What did you do?**

```v
fn main () {
	embedded_file := $embed_file('./test.txt')

	println(embedded_file.to_string())
}
```

**What did you expect to see?**

```bash
# working like expect
v run main.v

# build
v -prod -os macos -m64 -o ./bin/test main.v
# remove fille, if not remove it, once removed, it won’t work
rm test.txt
./bin/test
```
 
**What did you see instead?**

runtime error

```
V panic: EmbedFileData error: files "./test.txt" and "/Users/axetroy/gpm/github.com/axetroy/prune/test.txt" do not exist
v hash: 77c18f4
0   prune                               0x0000000107dd81ab main + 2619
1   prune                               0x0000000107dc3194 start + 52
```

**Comment by JalonSolov** [comment]
`-os macos` is useless (if it's even valid) if you're compiling on the mac, and won't work at all on anything else (mac can cross-compile to others, but others can't cross-compile to mac... stupid Apple).

**Comment by JalonSolov** [comment]
Yes, it does appear to be valid, and no it won't have any effect, but... it should be ok to specify it.

And yes, there appears to be a problem with `$embed_file`.

However, the error is that the file you're trying to embed doesn't exist.  V should catch this and give a better error message, instead of letting C catch the error later.  I don't know why the compilation doesn't fail, but running the compiled executable does - that should never happen.
