### ISSUE TITLE
porting v frontend to llvm

### ISSUE THREAD

**Issue by sh4m2hwz** [vlang/v#12209]
interesting is there already frontend vlang under llvm?  If not, do you plan to port to llvm?

**Comment by JalonSolov** [comment]
No, and no.  There was a little talk about it for a while, but everyone dropped it.

**Comment by sh4m2hwz** [comment]
are there any developments? they stayed?

**Comment by JalonSolov** [comment]
No.  It never got past the discussion phase.  One of the biggest problems is that the IR changes so much every version, nobody wanted to maintain the code to keep up with the changes.

Basically, the llvm is really only good for things that are already on the llvm.

Even the channel on the discord server was archived, since nobody posted any messages there for a long time.
