### ISSUE TITLE
after bootstrap, should abandon c

### ISSUE THREAD

**Issue by wanjochan** [vlang/v#1241]
suggest to release two branch, one is v@c while another v@v

because once v can be boostrap (to compile/run itself), the c dependency should be removed asap, otherwise it seems meaningless.

hope the author(s) can take s serious consideration.

**Comment by medvednikov** [comment]
Not sure what you mean, can you elaborate?

**Comment by MaD70** [comment]
@wanjochan the V compiler code generator currently emits C source code so it needs a C compiler to produce an executable.

**medvednikov** is working on an X64 (aka X86-64) code generator for the [Mach-O executable format](https://en.wikipedia.org/wiki/Mach-O) (see [homepage](https://vlang.io/) under _Fast compilation_**<sup>1</sup>**). When ready, it will produce executables for Mac OS and then, on Mac OS only, you'll not need a C compiler.

To be without the C dependence on other OSes, but on the same CPU (X64), at minimum someone have to write the code to produce an executable format understood by such OSes **<sup>2</sup>** ([PE](https://en.wikipedia.org/wiki/Portable_Executable) on Windows and [ELF](https://en.wikipedia.org/wiki/Executable_and_Linkable_Format) on Linux). Left as an exercise for the reader to understand how [ABIs](https://en.wikipedia.org/wiki/Application_binary_interface) enter the picture.

To be without the C dependence (or other dependencies) on other CPUs (typically ARM nowadays) you need a code generator for each of such CPUs.

If one think all this is easy and fast to produce, think again. One can choose to write a simple code generator, but needs to tame somehow the rest of the infrastructure. To give everyone an idea about how messy the situation is, I quote from the [job openings](https://www.di.ens.fr/~zappa/jobs.html) of a fully-funded academic research project:

> <h3>The low-level interface between applications and system software</h3>
> 
> Hidden, obscure, and badly specified components that lurk at the very heart of our computing infrastructure. Even advanced programmers and system researchers usually have only a partial understanding of the _low-level interface between applications and system software_. This interface is defined across, and scattered between, several components: at the very least these include the _binary format_ of the system (e.g., ELF on Linux, Mach-O on MacOsX, PE/COFF on Windows), the _Application Binary Interface_ (usually, but not always, dictated by the architecture), and the _linker behaviour_.
>
> This layer has evolved over forty years, continuously adjusting to the novel architectures and high-level programming language features. As it stands today, several of its aspects are _poorly specified_, and in extreme cases the sole documentation consists in the source code of the relevant libraries. This layer is _pervaded by subtle bugs_; most of the time these are unobservable only because _redundant strategies_ to recover correct informations have been baked over the years into libraries and tools to circumvent the problems.
>
> Broadly, we propose to investigate some aspects of this complex interface and to develop tools to make programming more robust and better-understood.

I wonder if in the long run is not better to start from a clean slate (a simpler, formally specified infrastructure).
_____________

1. It would be handy to have html anchors to all the sections so that one can refer to a section directly with a link.
2. To be more precise: by the loaders of such OSes — see [Linkers and loaders](https://linker.iecc.com/), drafts available on author's ftp site in postscript format **ftp://ftp.iecc.com/pub/linker/**; Github that cannot link to a ftp site is so lame!

**Comment by medvednikov** [comment]
Exactly, that's why emitting C will always be an option.
