### ISSUE TITLE
Add cli option to stop test execution after first failure

### ISSUE THREAD

**Issue by jdonnerstag** [vlang/v#12446]
I like test cases and often have many. Now and then it happens that I need to make breaking changes. After I fixed all the compiler errors, many of the test cases may still fail and I need to review and fix them one after the other.  Currently the process is rather annoying: I need to scroll up possible many pages and search for the first error. The proposed cli option would execute all tests sequentially (like -stats) and stop execution after the first error. Making my life a lot easier. Thanks for considering

**Comment by smartiniOnGitHub** [comment]
This would be very useful to have, as optional flag.

**Comment by spytheman** [comment]
With latest V 7b72326, you can now do:
`VJOBS=1 VTEST_FAIL_FAST=1 ./v test .` .
or
`VJOBS=1 ./v test -fail-fast .`

Doing just `./v test -fail-fast .` also works, but may not do what you expect, since if you do not set VJOBS explicitly to 1 (sequential execution), then all the tests, that were already started in parallel to the one that failed, will still continue their execution.

We can also make `-fail-fast` set VJOBS to 1 implicitly, if that is what people want, at the cost of making the 2 options slightly interdependent.
