### ISSUE TITLE
launch `cc` separately or `v -cc ${CC}`

### ISSUE THREAD

**Issue by whoizit** [vlang/v#1268]
Currently, for correctness, we should be able to pass `-cc` to `v`
in Makefile
`./v -cc ${CC} -cflags '${CFLAGS}' -o v compiler`

In fact, I think that we should not pass these options to V, we should run `cc` separately
```
./v -o v.c compiler
${CC} ${CFLAGS} -o v v.c
```

**Comment by spytheman** [comment]
I like the second variant more. 
In this way you could then compile the resulting v.c with whatever compiler you want, even with several ones, and do comparisons of the results easily.

**Comment by whoizit** [comment]
example for `/usr/bin/vc`
```
#!/bin/sh
[ -z "$CC" ] && CC=cc
[ -z "$CFLAGS" ] && CFLAGS='-O2 -fPIC '
v -o $1.c $1
eval $CC $CFLAGS -o $1 $1.c
```
USAGE:
`CC=gcc CFLAGS+='-pie' vc compiler/`

will build `compiler` binary

**Comment by spytheman** [comment]
The shell script will not work as it is. 
If you launch it inside v/ root folder, there is already a compiler/  folder, 
so there can not be generated a file with the same name at last line.

**Comment by whoizit** [comment]
`./v -o v.c compiler` vs `./v -o v compiler`
I believe that another compilation method (over `v`) should be removed before `v` gets its own compilation. 
A `bin/vc` script should be created that does what `v` currently does itself.
And this issue should not be closed until that method will not be removed.

**Comment by whoizit** [comment]
@spytheman how to use that commit? This generates `v.c` binary for me
`v -o v.c compiler`

**Comment by spytheman** [comment]
```
0[23:17:06]/v/v $ 
git pull
Already up to date.
Current branch master is up to date.
0[23:17:17]/v/v $ 
make
rm -f v.c .v.c v vprod thirdparty/**/*.o
curl -Os https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v v.c -lm 
./v -o v compiler
cc -O2 -fPIC   -c -o thirdparty/zip/zip.o thirdparty/zip/zip.c
cc -O2 -fPIC   -c -o thirdparty/glad/glad.o thirdparty/glad/glad.c
cc -O2 -fPIC   -c -o thirdparty/cJSON/cJSON.o thirdparty/cJSON/cJSON.c
V has been successfully built
0[23:17:24]/v/v $ 
./v -o x.c compiler
0[23:17:36]/v/v $ 
head x.c 
    
#include <stdio.h>  // TODO remove all these includes, define all function signatures and types manually 
#include <stdlib.h>
#include <signal.h>
#include <stdarg.h> // for va_list 
#include <inttypes.h>  // int64_t etc 


#if defined(__linux__) || defined(__OpenBSD__) 
#include <pthread.h> 
0[23:17:44]/v/v $ 
tail x.c
        vsprintf(g_str_buf, fmt, argptr);
        va_end(argptr);
#ifdef DEBUG_ALLOC 
        //puts("_STR_TMP:"); 
        //puts(g_str_buf); 
#endif 
        return tos2(g_str_buf);
}


0[23:17:48]/v/v $ 
```

**Comment by medvednikov** [comment]
@whoizit is suggesting moving entire cc() logic to a bash script `vc`. This is not going to happen.

Bash is going to be used only for installing V.

**Comment by whoizit** [comment]
Not bash, but POSIX SHELL. You still run the shell commands through V

**Comment by medvednikov** [comment]
How is this POSIX SHELL going to work on Windows?

Why introduce a new language, when everything can be written in V?

**Comment by whoizit** [comment]
windows guys will solve their problems

**Comment by medvednikov** [comment]
Then perhaps it's best not to introduce these problems in the first place.

This logic is already written in V, and it works on all systems.

**Comment by whoizit** [comment]
then we need to remove `-cflags`, because it must exist along with `-cc` and `-ldflags`. But this creates redundancy, because now we can do `-o v.c`
`vc` script still useful who need to change `cc` (for example if u have installed `gcc` and `clang` together) and other flags

**Comment by medvednikov** [comment]
`-cc` for specifying the C compiler I have no problems with. `-cflags` for specifying certain arguments is also ok.

There's no need in `-ldflags`, this is handled by the `#flag` syntax.

**Comment by spytheman** [comment]
The reason for -cflags and a new -ldflags is the same - making distro maintainers/packagers job easier, and supporting debugging problems with the build process of v projects, without customizing the v compiler each time. 

I think that both options would be useful, as long as V do not have working native code generation, and uses a C compiler as its backend.

I needed -cflags while debugging (for example passing -fsanitize=address or -fsanitize=leak or -fsanitize=thread without changing v compiler/ source was VERY useful for me while debugging hot reloading).

Admittedly, I had not encountered yet the need to customize the libraries,
linked to the resulting binary so far, but I do see that it could be useful, 

Example from: https://github.com/jemalloc/jemalloc/wiki/Getting-Started
```
Link jemalloc into the application at build time, but use it as a generic malloc implementation:
cc app.c -o app -L`jemalloc-config --libdir` -Wl,-rpath,`jemalloc-config --libdir` -ljemalloc `jemalloc-config --libs`
```

I think -cflags could not be used instead of -ldflags, since the later should append its arguments to the final C compiler invokation, instead of prefixing it like -cflags does now. I am not 100% sure about that though, will have to test.

**Comment by medvednikov** [comment]
@spytheman -ldflags functionality can be achieved with `#flag -L .`. Backticks won't work, but this is not crucial.

**Comment by spytheman** [comment]
> then we need to remove `-cflags`, because it must exist along with `-cc` and `-ldflags`. But this creates redundancy, because now we can do `-o v.c`
> `vc` script still useful who need to change `cc` (for example if u have installed `gcc` and `clang` together) and other flags

@whoizit , I think that @medvednikov is right to keep the build details inside v. 
There is no redundancy, because v is not a final application nor merely a transpiler, but aims to be a cross compiler. The fact that v is used to compile itself, is a detail that would not matter for most people, who would use it for writing applications.

As a compiler, v needs to know specific details about the trifecta of:
a) source of the application it compiles (for example the [live] or [json] attributes for the functions, the #flag and #include directives that are specified), 
b) the target OS
c) the host OS (availability of different compilers, linkers, assemblers)
... that is, if it wants to have native code generation + cross compilation. 

Such information would need to be passed somehow to the wrapper shell script, if v is reduced to just a transpiler to C (although for packaging purposes it may be fine (because you would know host/target OS in advance, and v would have already embedded the source knowledge in the C intermediary file). Thus the system would not be simplified in my opinion by splitting the c->native stage into a shell script.

**Comment by Yardanico** [comment]
@medvednikov It seems that `-cc` is now added to the V compiler, but it wasn't added to the command-line help text.
