### ISSUE TITLE
`substr` now returns a copy not a slice

### ISSUE THREAD

**Issue by ntrel** [vlang/v#1269]
https://github.com/vlang/v/commit/390394b56ba91beb9b9adc66838e7c62239502bb
https://github.com/vlang/v/issues/1247#issuecomment-513849769
`substr` now makes an unnecessary copy of *immutable* data, requiring freeing the result. This is very inefficient. Why are strings immutable if we're not making full use of slicing them? Strings should internally just be an array of bytes, and arrays should be reference counted.

**Comment by medvednikov** [comment]
Because if we substring a small string that points to a 1 MB string, we can longer free that big string, and memory is wasted. This is a common problem in Go.

Also it makes compile time memory management much easier and faster.

Java and C# have immutable strings, but they still use this approach. In fact Java switched to copying very recently.

It's not as expensive as it sounds. The V compiler uses lots of `.substr()`, I didn't get any slower.

**Comment by Rendims** [comment]
A suggestion is to keep slices and strings as separate types and provide both a fast `slice` and a copying `substr` function. Where slices reference some memory and strings always allocate and owns its memory.

That would make it easier to see that a slice might be part of a large string.
The compiler can see that the string should be freed at some point but the slice doesn't.
Type checking could stop the user from sending a slice to a C function since it might not be null terminated but allow strings.

The `free` function on strings is a bit problematic if there isn't a way to tell the difference between strings that owns the memory it points to and a slice that can start inside allocated memory. If the programmer doesn't know what a function returned then the compiler will most likely have a hard time as well.

This would be similar `&str` and `String` in Rust and can be applied to arrays as well.

**Comment by medvednikov** [comment]
@Rendims @ntrel yes, that's what's going to happen. Similar to what C++ did with the string_view.

We get the extra performance when needed, and the memory problem is solved, since the compiler no longer needs to figure whether it's a string or a string view.

**Comment by ntrel** [comment]
> it makes compile time memory management much easier and faster.

It would be great if you could explain a bit about V's CTMM in a GitHub issue.

> It's not as expensive as it sounds. The V compiler uses lots of .substr(), and it didn't get any slower.

That's one data point, but the compiler doesn't free strings everywhere AFAIK so this may be an unfair test.

There are places like `builtin/string.replace` where substr allocations will have a big performance impact.

**Comment by medvednikov** [comment]
I'm bringing it back @ntrel 

The substring will be cloned by the compiler if it escapes.
