### ISSUE TITLE
Opaque C structure compiler error

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#13063]
**V version:** 0.2.4
**OS:** Linux

Sample project attached here
[c_struct_stack.zip](https://github.com/vlang/v/files/7823382/c_struct_stack.zip)

**What did you do?**

A C structure as been defined as opaque
`typedef struct CStruct_struct CStruct;`

(A real world example can be found in the `alc.h` header)
```c
/** Opaque device handle */
typedef struct ALCdevice_struct ALCdevice;
/** Opaque context handle */
typedef struct ALCcontext_struct ALCcontext;
```

Then a test that creates two variables of `CStruct` on the stack is ran.
```v
fn test_instance() {
	one := C.CStruct{}
	two := C.CStruct{}
}
```

**What did you expect to see?**

The tests to run successfully .
 
**What did you see instead?**

A compiler bug `error: '{' expected (got "(")` for line `CStruct one = (CStruct){EMPTY_STRUCT_INITIALIZATION};`

**Comment by duarteroso** [comment]
I found these errors while trying to use the `AL` & `ALC` C headers

**Comment by spytheman** [comment]
You can not create instances of a C struct, that has incomplete type (since the C compiler does not know how large is the struct without its complete definition), however you can have pointers to them (since the size of the pointers is always the same for every type).

In the header `/usr/include/AL/alc.h`, all the usages of `ALCdevice` are for pointers (`ALCdevice *`) too.

That technique is often used as a form of encapsulation by C APIs, when the authors want to prevent you from creating the structs yourself, instead they more or less force you to call one of their APIs that return `ALCdevice *`, and then to use that pointer for all the rest of the calls.

Initializing pointers is done with `one := &C.CStruct(0)`, not `one := &C.CStruct{}` which look similar, but in fact will produce code for creating a new CStruct on the heap, and returning a pointer to it.

We could perhaps add support for `[noinit]` for C. structs too (currently that works only for V structs), to handle such situations, so that V could produce an error earlier, instead of failing later in the C compiler 🤔 .
