### ISSUE TITLE
Now, run error occurs: v/examples/log is not a directory.

### ISSUE THREAD

**Issue by changrui** [vlang/v#1317]
**V version:** 
v 0.1.16
**OS:** 
WSL ubuntu 18.04 lts
**What did you do?**
`v run v/examples/log.v`

**What did you expect to see?**
running correctly.
 
**What did you see instead?**
but `... is not a directory` .

**Comment by spytheman** [comment]
That seems to happen when 'v run log.v' is started twice in a row.

```
0[11:25:49]/v/v/examples $ 
/v/v/v run log.v
============ running log ============
[I]info
[W]warn
[E]error
[D]debug
V panic: fatal
[I]info
[W]warn
[E]error
[D]debug
V panic: fatal
failed to run the compiled program
1[11:26:10]/v/v/examples $ 
/v/v/v run log.v
V panic: /v/v/examples/log isn't a directory
1[11:26:19]/v/v/examples $ 
rm log
0[11:26:21]/v/v/examples $ 
/v/v/v run log.v
============ running log ============
[I]info
[W]warn
[E]error
[D]debug
V panic: fatal
[I]info
[W]warn
[E]error
[D]debug
V panic: fatal
failed to run the compiled program
1[11:26:24]/v/v/examples $ 
```

**Comment by spytheman** [comment]
I think the problem is due to the following:
1) the example file is named log.v
2) the file contains import log
3) the folder initially does NOT contain file named 'log'.
4) v run log.v 
-> produces an executable 'log' in the current directory where the file log.v is.
5) the second time that 'v run log.v' is run, it encounters again 'import log', then tries to locate log folder in the current folder, this time, there is a file named 'log', so it sees that the executable 'log' exists, then checks whether it is a folder, and since it is not, it bails out with an error message.

**Comment by spytheman** [comment]
Running '/v/v/v run examples/log.v' *outside* of the examples folder does not produce the error, no matter how many times it is run.
https://url4e.com/gyazo/images/9e3a27ad.jpg

**Comment by spytheman** [comment]
The same problem happens with the examples/json.v - it also imports a module, named just like the .v file, so the second time, it fails with:
```
0[20:03:40]/v/v/examples $ 
/v/v/v run json.v 
V panic: /v/v/examples/json isn't a directory
1[20:03:41]/v/v/examples $ 
```

**Comment by medvednikov** [comment]
Fixed.

**Comment by joe-conigliaro** [comment]
@medvednikov sure ill have a look

**Comment by joe-conigliaro** [comment]
Fixed here: https://github.com/vlang/v/pull/1337

It was just as i suspected in my last comment, however the reason is very strange.

**Comment by medvednikov** [comment]
Thanks.
