### ISSUE TITLE
Shared array can be cloned without lock?

### ISSUE THREAD

**Issue by naoki9911** [vlang/v#13329]
**V version: V 0.2.4 a4fb5d2** 
**OS: Ubuntu 20.04.3** 

**What did you do?**
```
module main

fn test_shared_array() {
	shared a := []string{}
	t2 := a.clone()
	println(t2.len)
}
```

**What did you expect to see?**
`clone()` is implemented as `pub fn (a &array) clone() array` so that above code should be error.
 
**What did you see instead?**
No error occured.

**Comment by petaqb** [comment]
Sorry, why you think that this should be an error? It looks fine IMO

**Comment by naoki9911** [comment]
@petaqb Thanks you for your reply!

`clone()` without lock generates below C code.
The code shows that `clone()` copies the array without any locks.
If other threads are doing some operation on the cloned array, I think that the result of `clone()` can be broken or can cause unexpected behavior. 

```c
array array_clone_to_depth(array* a, int depth) {
        int size = a->cap * a->element_size;
        if (size == 0) {
                size++;
        }
        array arr = (array){.element_size = a->element_size,.data = vcalloc(size),.offset = 0,.len = a->len,.cap = a->cap,.flags = 0,};
        if (depth > 0 && _us32_eq(sizeof(array),a->element_size) && a->len >= 0 && a->cap >= a->len) {
                for (int i = 0; i < a->len; ++i) {
                        array ar = (array){.element_size = 0,.data = 0,.offset = 0,.len = 0,.cap = 0,.flags = 0,};
                        vmemcpy(&ar, array_get_unsafe(/*rec*/*a, i), ((int)(sizeof(array))));
                        array ar_clone = array_clone_to_depth(&ar, depth - 1);
                        array_set_unsafe(&arr, i, &ar_clone);
                }
                return arr;
        } else {
                if (!isnil(a->data)) {
                        vmemcpy(((byte*)(arr.data)), a->data, a->cap * a->element_size);
                }
                return arr;
        }
        return (array){.element_size = 0,.data = 0,.offset = 0,.len = 0,.cap = 0,};
}

VV_LOCAL_SYMBOL void main__test_shared_array(void) {
        __shared__Array_string* a = (__shared__Array_string*)__dup_shared_array(&(__shared__Array_string){.mtx = {0}, .val =
        __new_array_with_default(0, 0, sizeof(string), 0)}, sizeof(__shared__Array_string));
        Array_string t2 = array_clone_to_depth(&a->val, 0);
        println(int_str(t2.len));
}
```

**Comment by dumblob** [comment]
This is a very general problem - basically all non-primitive types (arrays, maps, nearly **all** struct-backed types...) in *V* are thread-**unsafe**. There was so far no explicit discussion about making them thread-safe. There were other numerous thread-safety related discussions though - e.g. https://github.com/vlang/v/issues/1868 .

And I'm afraid *V* can not afford making these structures thread-safe due to performance reasons unless the `-no-parallel` compile option would change its meaning. In other words, *V* shall at least document that all stuff (except of channels) is thread-unsafe and shall be wrapped with `lock` statements.

OTOH it's probably not such a big deal as `lock` is being considered an optimization and advanced use of *V*. For anything else (i.e. the vast majority of stuff) one shall **always** use channels.

**Comment by andersk** [comment]
The home page claims that V has “No undefined behavior”. If it aspires to keep this promise, then either every type needs to be thread-safe (or at least memory-safe in its thread-unsafety), or there needs to be a mechanism to restrict sharing of thread-unsafe types (like Rust’s `Send`/`Sync` traits).

Perhaps this promise is too ambitious and needs to be weakened—even [Go has memory-unsafety](https://blog.stalkr.net/2015/04/golang-data-races-to-break-memory-safety.html) in the presence of threads.
