### ISSUE TITLE
`v doc` causes cloning error

### ISSUE THREAD

**Issue by ntrel** [vlang/v#13672]
**V version:** 
**OS:** 
```
OS: windows, Microsoft Windows 8.1 v9600 64-bit
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc --version

getwd: C:\git\v
vmodules: C:\Users\Czastka Family\.vmodules
vroot: C:\git\v
vexe: C:\git\v\v.exe
vexe mtime: 2022-03-07 13:52:09
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 e6270b0

Git version: git version 2.35.1.windows.2
Git vroot status: weekly.2022.09-34-ge6270b05
.git/config present: true
thirdparty/tcc status: master 17d18c13
```

**What did you do?**

```
C:\git\v>v doc vlib/arrays
V panic: cloning failed, details: fatal: Too many arguments.
```

**Comment by spytheman** [comment]
I think it is due to the space in: `vmodules: C:\Users\Czastka Family\.vmodules`
`v doc` tries to install the `markdown` module, by cloning it into `~/.vmodules/markdown` with:
`cloning_res := os.execute('git clone $murl $mpath')`
in vlib/v/util/util.v .

I've changed it to:
 `cloning_res := os.execute('git clone ${os.quoted_path(murl)} ${os.quoted_path(mpath)}')`

in f6aba9a , and it seems to work on Linux at least:
![image](https://user-images.githubusercontent.com/26967/157208776-c669efd3-c927-4559-bf70-23cb6a6904c0.png)

Please test again with latest V, if it works in your case too.

**Comment by ntrel** [comment]
I was trying to find out what was causing the tcc error. tcc wasn't very helpful so I tried gcc and manually running the link command:
```
C:\tmp\vmodules\cache\d6\d6220f34bc88e2925e599189e4d9601a.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
```
Then I tried this and it worked!:
`./v -cc gcc cmd/tools/vdoc`

**Comment by ntrel** [comment]
I was getting another error today:
```
$ /c/git/v/v doc vlib/builtin/
failed    cmd: "C:\git\v\v.exe" -skip-unused "C:\git\v\cmd\tools\vdoc"
failed   code: 1
cmd/tools/vdoc/html.v:6:1: builder error: cannot import module "" (no .v files in "C:\git\v\")
    4 | import net.urllib
    5 | import strings
    6 | import markdown
      | ~~~~~~~~~~~~~~~
```
That was also solved by:
```
./v -cc gcc cmd/tools/vdoc
```

**Comment by Delta456** [comment]
Works with the latest commit of V:

![image](https://user-images.githubusercontent.com/28479139/187083574-367b1768-4238-4408-a858-625ac9b66a88.png)
