### ISSUE TITLE
Return option function cause pacnic.

### ISSUE THREAD

**Issue by changrui** [vlang/v#14074]
**V version:** 
`0.2.24` latest
**OS:** 
`devbits.app/play`

**What did you do?**
```
fn abc(a int) ?string {
    if a > 5 {return error('error')}
    return '<5'
}
println(abc(7)?)
```
**What did you expect to see?**
`error`
 
**What did you see instead?**
```
V panic: optional not set (error)
v hash: 56a3539
/tmp/v_1000/main.1364901734277335616.tmp.c:6276: at _v_panic: Backtrace
/tmp/v_1000/main.1364901734277335616.tmp.c:6246: by panic_optional_not_set
/tmp/v_1000/main.1364901734277335616.tmp.c:11441: by main__main
/tmp/v_1000/main.1364901734277335616.tmp.c:11808: by main
```

**Comment by StunxFS** [comment]
what is the problem? This behavior is correct. `?` is a short form for `or { panic(err) }`

**Comment by changrui** [comment]
I know, but what's the meaning of `V panic: optional not set (**error**)`? How should I do? I do not need a panic!

**Comment by JalonSolov** [comment]
The problem is that you're not handling the error in the `println` statement.  By just having `abc(7)?` you are telling V to propagate the error upwards, and in main, that means exiting with a panic.

There are 2 ways to fix this.  You can only return a string from `abc()` instead of an optional, as in
```v
fn abc(a int) string {
    if a > 5 {return 'error'}
    return '<5'
}
println(abc(7))
```
Or, you can handle the optional before trying to print the value
```v
fn abc(a int) ?string {
    if a > 5 {return error('error')}
    return '<5'
}
s := abc(7) or {'error'}
println(s)
```

**Comment by changrui** [comment]
Thanks, closed this issue.

**Comment by changrui** [comment]
`s := abc(7) or { '$err' }`
