### ISSUE TITLE
Adding to Debian Repository

### ISSUE THREAD

**Issue by patranger** [vlang/v#14221]
Once I heard that probably along with the V 2 language version it was supposed to be added to the Debian repository. It still hasn't happened, and it would help a lot in using the V language.

**Comment by ylluminate** [comment]
Please see the following installation discussions and if you have trouble or any experience you'd like to share, please document it by following the examples of other entries here:
https://github.com/vlang/v/discussions/categories/installation-issues

As spytheman explains, there's no reasonable reason to implement packages at this stage in development (pre 1.0) since changes come too frequently that are important. It's better for those who use V to learn to use the very easy `v up` update cycle following installation, see:
https://github.com/vlang/v#installing-v---from-source-preferred-method
