### ISSUE TITLE
`TypeName!` syntax for generic function type inference

### ISSUE THREAD

**Issue by ntrel** [vlang/v#147]
I've written a short article proposing syntax for inferring generic function types:
https://github.com/ntrel/vdev/blob/master/arg-infer.md

It discusses why this syntax for inference is not ideal:
```rust
fn (r Repo<T>) find_by_id(id int) T? {...}
```
And proposes `TypeName!` instead:
```rust
fn print(v T!) {...}
fn (r Repo<T!>) find_by_id(id int) T? {...}
```
(I'll probably post this to the forum too later).

**Comment by zac-garby** [comment]
Another way to distinguish between concrete types and type parameters is by writing type parameters in lowercase, such as in Haskell. I personally prefer this way because it prevents the need to add extra punctuation.

The only downside of this would be that concrete types couldn't begin with lowercase letters, but in reality this isn't a problem.

So this would make the `print` example look like:

```rust
fn print(v t) { ... }
```

**Comment by ntrel** [comment]
> by writing type parameters in lowercase

Some type parameters can be inferred, some not (e.g. new_repo in the docs). Writing non inferred type parameters in lower case too doesn't solve the inference problem. 

Also compare the receiver parameter `Repo<T!>` to `Repo<t>`, which one stands out the most as saying that the function is generic?

As well as this, V already has lower case type names, int, bool etc.

**Comment by ntrel** [comment]
Another issue is that for `Repo<t>`, lowercase identifiers like `t` are also used for variables. Like D and C++, it's possible V might later want to allow template parameterization on a constant or even variable name (see D alias parameters if interested). Lowercase type parameters for inference would conflict with that.

**Comment by medvednikov** [comment]
Thanks for the write up. I don't have an opinion yet, will need to think about it and do research.

Just one thing: there's already a rule on naming types. V types must start with a capital letter. So perhaps we can just prohibit creating types that have only one letter and use them for generics. That solves the original problem you described.

**Comment by ntrel** [comment]
> perhaps we can just prohibit creating types that have only one letter and use them for generics

The problem is we need a way of marking a generic type as inferred, this means we don't need to write it in the template argument list. Not all generic type parameters can be inferred, so that wouldn't solve the problem.

**Comment by ntrel** [comment]
BTW your idea would work if non-inferred generic type arguments weren't allowed to use a single letter.

**Comment by zac-garby** [comment]
What conditions could cause a type parameter to be ambiguous and not be able to be inferred?

**Comment by ntrel** [comment]
Zac:
```
fn new_repo<T>() {
  return Repo<T>{}
}
```

**Comment by zac-garby** [comment]
What can't be inferred here? I might be missing something - I'm more used to generics in Haskell which may be slightly different.

(Also, I think you may be missing the return type on that function)

**Comment by ntrel** [comment]
T can't be inferred there because there's no argument to infer it from, it's a user-supplied type argument. The return type is `Repo<T>`. This function is from the docs, (slightly simplified by omitting `db`, which isn't relevant).

**Comment by zac-garby** [comment]
But surely `T` in `Repo<T>` could be inferred from the context in which it is used once it has been returned from the function? In that, the function could be written like:

```
fn new_repo<T>() {
  return Repo{}
}
```

And be either unambiguous (if the specialisation of `Repo` can be derived from its usage); or, be ambigous, in which case a programmer-specified type could not be correct according to the language's type system because:

 - If it was the _only_ correct type, then the language could derive the specialisation.
 - If it was not the only correct type, the context where the return value is used could be one of a number of things and so the programmer-specified type parameter wouldn't always be correct.

On top of this, since the function is _actually_ defined as:

```
fn new_repo<T>() Repo<T> {
  return Repo<T>{}
}
```

The specialisation of the `Repo<T>{}` return value can easily be derived since it must fit the type of the return value.

**Comment by ntrel** [comment]
Zac the return type of new_repo can indeed be inferred from the function body (that's why I didn't write it earlier).

But until the Repo is created, the type parameter of new_repo cannot be known. That function creates the Repo struct instance. Doing complex inference based on how new_repo's result is used in the caller's code does not seem like a straightforward or reliable strategy. Supplying the type manually is the sensible thing to do here.

**Comment by ntrel** [comment]
Let's make it less abstract, suppose we want to wrap creation of an empty array:
```
fn array<T>() {return []T}
``
Do you see that T can be any type, just like with Repo<T> in C's generic docs?

**Comment by zac-garby** [comment]
Sorry about the late reply. Yeah, I see that T can be any type. I agree that the inference based on the calling code would not be straightforward (I have absolutely no idea how it would be implemented myself), but it’s absolutely reliable.

**Comment by ntrel** [comment]
There are cases where the type can't be inferred even from how the caller uses the result:
```
fn create_struct<T>() {return T{}}
s := create_struct()
println(s)
```
All structs may be printable, so we can't infer T. Same for calling s.str(). There will always be ambiguous cases where supplying T manually is required. As well as compiler code complexity of this inference, it would also be slow. I don't think it's worth having.

**Comment by zac-garby** [comment]
The problem here is that, since the struct is empty, it would always just be printed as an empty struct, regardless of its specialisation, so no problem has actually occurred (the value can remain a generic type). If, however, some value was added inside the struct, its type could be inferred.

If there are cases where the type can't be inferred, just as in other languages, optional type annotations should be able to be included. I'm not sure if the syntax already exists in V - I'm not too familiar with the language yet - but it could look something like the following:

```
fn create_struct<T>() {return T{}}
s := create_struct() :: <some type>
println(s)
```

The `:: <some type>` annotation says that the type of the return value of `create_struct()` can be assumed by the compiler to be the given type, meaning it can be successfuly inferred.

Going back to my first point. If it is not wanted for a type to remain generic (which is reasonable, and probably a good idea in fact), the code you posted could be a compiler error and the modified code which I posted could be the way to make it compile.

**Comment by ntrel** [comment]
I've not used it, but I think Hindley–Milner type inference is closer to what you want, and Rust seems to have it:
https://doc.rust-lang.org/rust-by-example/types/inference.html

That example relies on the compiler knowing that vec is some instance of Vec, so when a method is called it can match the argument type with the instance type parameter. I think this is more limited than what you're asking for, but even Rust inference slows down compilation and makes error messages less precise.

**Comment by zac-garby** [comment]
That's the one I was thinking of, yeah. It's a good point about compilation speed, because I know that compile time is one of the goals for V, so perhaps it's not such a good idea for these types to be inferred after all.

**Comment by ntrel** [comment]
>  the return type of new_repo can indeed be inferred from the function body

Return type inference is very useful in generic code. If we go with `Type!` parameter syntax, return type inference could be written with `!` after the function parameter list:
```rust
fn min(a!, b!)! {return if a < b {a} else {b}}
assert min(2, 3) == 2
```
Writing the return type for `min` would be quite complicated otherwise (I think we'd need a `typeof(expr)` feature). Note: *If expression* was proposed [here](https://github.com/vlang/v/issues/130#issuecomment-485090357).

**Comment by zac-garby** [comment]
I like it, but the `!` doesn't really say "inference" to me. Maybe `?` could be used instead, since it kind of implies that the type isn't necessarily known and can be worked out by the compiler.

This could be generalised to the point where `?` is a valid type/parameter, so you could write a function like this:

```rust
fn ignore_arg(?) str {
    return "hello world"
}
```

But if the value of the parameter was to be used, it would look like `a?`, or `foo?`, or whatever, and its value would be stored in the variable `a` or `foo`. And for return types the same thing applies, either the exact same syntax (which would introduce named return values - I'm not sure whether they already exist in V), or only `?` could be allowed (no binding variable).

**Comment by ntrel** [comment]
> the ! doesn't really say "inference" to me

The exclamation mark says that the identifier is special, there's something more to it than just writing a normal identifier, in the same way an exclamation mark at the end of a sentence changes the tone of the sentence.

> fn ignore_arg(?) str

In Go and Rust `_` is used as a placeholder for an unused variable name - I would write that function as `fn ignore_arg(_ T!) str`. It's rare that a function parameter is not used.

> Maybe ? could be used instead

`T?` currently means optional type. (It hopefully will change to `?T` - see the [thread here](https://github.com/vlang/v/issues/67#issuecomment-480364217), but for `?` to have two different meanings, each in type context, would be confusing IMO).

**Comment by lutherwenxu** [comment]
This issue has been closed due to the inactivity.
Please reopen this issue if you want to continue the discussion.
