### ISSUE TITLE
too strict of `warning: unused variable` 

### ISSUE THREAD

**Issue by ghost** [vlang/v#14939]
**V version: 0.3.0 584c035** 
**OS: ArchLinux** 

**What did you do?**
```v
fn main() {
    arr := [1, 2, 3]
    mut sum := 0
    for a in arr {
        sum += a
    }
}
```

**What did you expect to see?**
No warnings like in Go https://go.dev/play/p/eySyUqusax5
 
**What did you see instead?**
```
bug.v:3:9: warning: unused variable: `sum`
    1 | fn main() {
    2 |     arr := [1, 2, 3]
    3 |     mut sum := 0
      |         ~~~
    4 |     for a in arr {
    5 |         sum += a
```

**Comment by medvednikov** [comment]
Confirmed. Thanks for the report.

**Comment by depperm** [comment]
Is this a bug? `sum` is added to (would be the same as initializing it to some number) but never printed or referenced otherwise.

**Comment by JalonSolov** [comment]
That's my feeling.  If Go doesn't report it as a problem, that's a bug in Go.

**Comment by kahsa** [comment]
@JalonSolov  Report to Go's Issue.
I am interested to see what kind of reply they get back.

**Comment by medvednikov** [comment]
No, it's not a bug. That's how unused warnings work in Go and V.

Otherwise each time you remove a print, you have to remove 10 operations on a variable to make it compile.

**Comment by kahsa** [comment]
I agree. It is not a matter of bug or not.
It is a matter of specifications.

**Comment by JalonSolov** [comment]
So you would rather have lots of dead code in the final program, than get a warning about unused variables at compile time?

**Comment by JalonSolov** [comment]
Ok, then let's turn off the auto-warning-to-error stuff, too.  After all, doesn't that just get in your way when compiling with `-prod`?

**Comment by kahsa** [comment]
> auto-warning-to-error stuff
What is it?

**Comment by JalonSolov** [comment]
"auto-warning-to error" meaning where all warnings in regular mode are turned into errors if `-prod` is used.

The problem is that the value of the variable is never used for anything, hence it is unused.  Exactly as the current message says.

**Comment by kahsa** [comment]
1) I have a slightly longer code.
But it is incomplete.
Even if it is not read, the fact that it is written means that the intention is to use the variable.
However, it is not read out because it is incomplete.
The variable will be read when the function is completed.
But at the moment, it is incomplete.
But it will be completed sooner or later.

2) On the other hand, there are variables that remain in the code even though there is no real intention to use them.
I would appreciate it if you could warn me about such variables, as they are completely useless.

3) In the second situation, there are cases where an `import` is left in the code that is not needed at all.
In this case, it would be nice to be warned that the import is unnecessary.

My idea of "unnecessary" code is the second case and the third case that goes along with it.
In this case, a warning that there is unused code would be useful.

But in the first case, the code isn't unused, it's just unfinished. It is not unnecessary. It is incomplete, but necessary. I'm going to use it later.
In this case, the warning is a bit annoying.

**Comment by kahsa** [comment]
1) Assist developers with the above objectives.
Assist developers to develop more comfortably.
I believe that warnings are part of this.
This is my opinion based on such a perspective.

2) As already mentioned above, there is also the code performance perspective, but from that perspective, I don't know to what extent this warning about `unused variables` affects performance, so I don't have any conclusions.

3) Like vfmt, from the perspective of code consistency, I have no particular opinion on this matter, but I think the first is more important than this.

**Comment by JalonSolov** [comment]
As soon as you allow one warning to pass, someone can make a case to allow a second one.  Then a third.  Then more.

Then you might as well not mark any warnings as errors.

I don't know what the Go developers were thinking, but I disagree with their decision.  It may have been as simple as "Oh, the optimizer will handle it."  It really doesn't matter why.

In your scenario of "it's not unused, just incomplete", that means we should also disable the warnings about _all_ unused things, in case they might just be incomplete/not used yet.

**Comment by kahsa** [comment]
> It really doesn't matter why.

I think the reasons are more important.
I think it is far more important why the code was designed to work the way it does than how it works.

> In your scenario of "it's not unused, just incomplete", that means we should also disable the warnings about all unused things, in case they might just be incomplete/not used yet.

No. As clearly stated above, there are conditions under which warnings are appreciated. Therefore, I do not believe that all warnings should be disabled.

**Comment by kahsa** [comment]
> As soon as you allow one warning to pass, someone can make a case to allow a second one. Then a third. Then more.

In this regard, it is sufficient to specify why an `unused variable` warning is provided.
That way, if someone later comes along who is as you claim, we can point this out and dismiss it.

This is why I said above that it is more important *why it was designed that way* than how it works.
The reason for such a design, the purpose of the design, is of paramount importance.
For that purpose, the feature was made to work that way.

We begin to stray because we forget the reason for the original design.

**Comment by kahsa** [comment]
This is why I have repeatedly stressed the need for specifications.

In most cases, it is sufficient to explain how it works, but in some situations, it is more important to describe why it is designed to work the way it does.
This is true for cases where there are a wide variety of opinions.

We can call it a philosophy.
Design policy.
It keeps people from getting lost.

**Comment by kahsa** [comment]
I really like the spirit of V.

1) Fast
2) Easy to understand syntax
3) Multi-platform

The sacrifices are
1) Some functions don't check, don't give errors, etc.
2) No sugar-syntax, etc.
3) Not all OS APIs can be used, as represented by Sokol, etc.

These are trade-offs, but they are acceptable because they serve the above purposes.

So which of the `unused variable` warnings apply? That's what I mean.
User-friendly development environment? (Not mentioned above though)
High speed?
Or what?

**Comment by kahsa** [comment]
But this time I understand some of your basic thought @JalonSolov 

1) You don't care about the purpose, only how it works.
2) Your primary fear is that if you allow one thing to happen first, it will collapse one after the other, like a dam breaking process.

I understand why you and I are not on the same wavelength.

**Comment by medvednikov** [comment]
> In my opinion, if the presence of unnecessary code has a serious negative impact on performance

it doesn't, it gets completely removed by `-prod`

**Comment by medvednikov** [comment]
I didn't expect such a big discussion on this topic.

Making it more strict will mean that even `_ = foo` won't work now to hide the warning. The developer will have to go through dozens of uses and comment them out. And then uncomment them when the variable is needed again. Over and over again.

Can anyone submit this bug at https://github.com/golang/go to see their reasoning? I'm sure there are more reasons not make this a warning.

**Comment by felipensp** [comment]
What is your actual opinion here @medvednikov ?

**Comment by medvednikov** [comment]
@felipensp I think this issue can be closed.

V's behavior is correct here.
