### ISSUE TITLE
vmod: contents of manifest are not accessible for some reason as const in different file

### ISSUE THREAD

**Issue by hungrybluedev** [vlang/v#15049]
**V doctor:**
```
OS: linux, Pop!_OS 22.04 LTS
Processor: 6 cpus, 64bit, little endian, AMD Ryzen 5 4500U with Radeon Graphics
CC version: cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

getwd: /home/astro/Projects/V/scratch/missing_metadata
vmodules: /home/astro/.vmodules
vroot: /home/astro/Projects/V/v-main
vexe: /home/astro/Projects/V/v-main/v
vexe mtime: 2022-07-13 07:15:56
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 81d694b.4238e5f

Git version: git version 2.34.1
Git vroot status: weekly.2022.28-2-g4238e5f6
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 827f7452

```

**What did you do?**
`v run .`

**missing_metadata.v**

```v
module main

fn main() {
	println(manifest)
	println(version)
}
```

**metadata.v**

```v
module main

import v.vmod

pub const manifest = vmod.from_file('v.mod') or { panic(err) }

pub const (
	version = manifest.version
	name    = manifest.name
)
```

**What did you expect to see?**

```
v.vmod.Manifest{
    name: 'missing_metadata'
    version: '0.1.0'
    description: 'Project to demonstrate error while using vmod'
    dependencies: []
    license: 'MIT'
    repo_url: ''
    author: ''
    unknown: {}
}
0.1.0 # <---- Expected to see the valid version
```

**What did you see instead?**

```
v.vmod.Manifest{
    name: 'missing_metadata'
    version: '0.1.0'
    description: 'Project to demonstrate error while using vmod'
    dependencies: []
    license: 'MIT'
    repo_url: ''
    author: ''
    unknown: {}
}
println(NIL) # <------ version is not accessible, or get a nil value for some reason
```

**Comment by martinkeefe** [comment]
Getting same issue here. Just started learning V today and used the geo tutorials. A unit test fails because "Description" is missing from output when using "--help" flag. Tried a println and saw NIL (as above).

V doctor:
`OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 3700X 8-Core Processor  
CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.        
 cmd: cc --version

getwd: D:\my\temp\v\geo
vmodules: C:\Users\Martin\.vmodules
vroot: C:\Users\Martin\scoop\apps\v\0.3.2
vexe: C:\Users\Martin\scoop\apps\v\0.3.2\v.exe
vexe mtime: 2023-01-20 18:45:55
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 9a43fa9

Git version: git version 2.37.3.windows.1
Git vroot status: weekly.2023.03-35-g9a43fa96
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 1e6e7c6f`

**Comment by spytheman** [comment]
The content of the v.mod file is:
```
Module {
        name: 'missing_metadata'
        description: 'Project to demonstrate error while using vmod'
        version: '0.1.0'
        license: 'MIT'
        dependencies: []
}
```

It was produced by `v new missing_metadata`, then answering the questions with the answers from above.
