### ISSUE TITLE
vweb: vweb.Context embed App class, App class self attribute value lost

### ISSUE THREAD

**Issue by wilesun** [vlang/v#15074]
**V version:** V 0.3.0 0d6d6f7
**OS:** ubuntu 18.04

**What did you do?**
```
import  vweb

struct T1App {
	vweb.Context
	pub:
	a string
}

['/hello']
pub fn (mut app T1App) hello() vweb.Result {
	return app.text(app.a)
}

fn main() {
	mut app := T1App{
		a: "this is a test"
	}
	println(app.a)
	vweb.run(&app, 18082)
}
```
curl -v http://localhost:18082/hello
**What did you expect to see?**
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 18082 (#0)
> GET /hello HTTP/1.1
> Host: localhost:18082
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 14
< Server: VWeb
< Connection: close
< 
* Closing connection 0

```
 
**What did you see instead?**
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 18082 (#0)
> GET /hello HTTP/1.1
> Host: localhost:18082
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 0
< Server: VWeb
< Connection: close
< 
* Closing connection 0
```

**Comment by jminor** [comment]
For clarity, the bug is that Content-Length is 0 when it should have been 14. The value of `app.a` inside `hello()` is an empty string when it should have been `this is a test`

I am seeing the same problem in my vweb application. As a workaround I used a shared State struct like in this example: https://github.com/vlang/v/blob/master/examples/vweb/vweb_example.v

For state values that are mutable this strategy makes sense, but for immutable values defined when the app starts, as illustrated in this bug report, using shared state is awkward because it requires locking.

Why is the value of `a` lost between `main()` and `hello()`?

**Comment by jminor** [comment]
I think I see why this is happening. In the vweb code here: https://github.com/vlang/v/blob/cc43a23f29bd144b58a2c33f856f37fce1f60a60/vlib/vweb/vweb.v#L410 you can see that it does a special field-by-field copy of the provided App struct (type `T` inside `run_at<T>`). Any fields not marked as `shared` or with the `vweb_global` attribute are ignored.

So you can make your example work by adding an attribute to your field like this:
```
struct T1App {
	vweb.Context
	pub:
	a string [vweb_global]
}
```

I don't see this documented anywhere, and it is very surprising. I wonder why vweb does this special copy?
