### ISSUE TITLE
C2V Demo Translating SDL2 not found

### ISSUE THREAD

**Issue by extremety1989** [vlang/v#15130]
i am following tutorial on C2V Demo Translating to DOOM from C

i get following error

```
 cmake .
-- Could NOT find SDL2 (missing: SDL2_INCLUDE_DIR SDL2_LIBRARIES) (Required is at least version "2.0.1")
-- Could NOT find SDL2_mixer (missing: SDL2_MIXER_INCLUDE_DIR SDL2_MIXER_LIBRARY) (Required is at least version "2.0.0")
-- Could NOT find SDL2_net (missing: SDL2_NET_INCLUDE_DIR SDL2_NET_LIBRARY) (Required is at least version "2.0.0")
-- Could NOT find samplerate (missing: SAMPLERATE_INCLUDE_DIR SAMPLERATE_LIBRARY)
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
-- Configuring done
CMake Error at textscreen/CMakeLists.txt:28 (target_link_libraries):
  Target "textscreen" links to:

    SDL2::SDL2

  but the target was not found.
```
i m new to c programming , if someone can help me where should i put or link SDL2 ?

**Comment by JalonSolov** [comment]
You'll need to install the SDL2 dev headers, which is different on each system.  Which OS are you on?

**Comment by extremety1989** [comment]
@JalonSolov win10 64

**Comment by extremety1989** [comment]
@JalonSolov i followed tutorial with sdl2 , it says i need to copy include and lib folder to project folder, but i do not understand what i should do next ,how to make it run

**Comment by JalonSolov** [comment]
I don't do Windows any longer (haven't for a while).  Perhaps @Larpon can help (since he created that sdl port).

**Comment by extremety1989** [comment]
@extremety1989 okey thanks.

**Comment by Larpon** [comment]
This has nothing to do with `vlang/sdl`, I think. This is about cmake not being able to find development headers on Windows - I don't know how cmake detect SDL2 on Windows since there's no official package system on Windows. A guess would be that you'll have to download SDL2 (and all the other missing on the list) source archives, unpack them and tell cmake via e.g. environment variables where the SDL2 (and other) sources reside and then run cmake again. But it's pure guesswork 😅
