### ISSUE TITLE
use V without OOP

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [vlang/v#15407]
its possible to use V features without being forced to use OOP features... like

trim_spaces(name) instead of name.trim_spaces()? otherwise the language will become instantly unusable to me.

**Comment by medvednikov** [comment]
V is not an OOP language, I would even say it's anti-OOP. It promotes usage of simple functions and structs. There's syntax sugar for methods (x.foo()), but that doesn't make it OOP.

**Comment by Vortex5ber** [comment]
The ideal paradigm of V is, "in most cases there's only one way to do something". That is totally beneficial in many sense, like easier maintainability of codes, easier collaboration, ease of study and instruction especially for the younger generation. Complex is very expensive. As Edsger Dijkstra said, "Simplicity is prerequisite for reliability".

**Comment by Wajinn** [comment]
> `name.trim_spaces() `

**Dot notation** is not OOP, but rather a convenience, and is something you can use with structs (C family) or records (Pascal/Ada), which are found in many languages.

**Uniform Function Call Syntax** (sometime referred to with Unified or Universal vs Uniform), is not OOP either.  It comes from **function chaining**, which I believe comes from the functional programming languages, and then was adopted by OOP languages.

Instead of chaining functions together like this- `add(mix(collect(var)))` (which is very hard to read), you would do something like this- `var.collect().mix().add()`.

**Comment by MyTDT-Mysoft** [comment]
well the raytracer project pointed by main site even have OPERATORS for the OBJECTs of VEC3 that it creates which makes it 101% OOP... and yes i want to call functions from the function... not function from the objects... calling functions from the object (and being forced to do that... makes it Object Oriented, instead of function oriented)

**Comment by medvednikov** [comment]
It doesn't, you need to look up the definition of OOP.

**Comment by MyTDT-Mysoft** [comment]
right calling functions and operators in an OBJECT is not "object oriented programming" omg...
you guys are soo disappointing... thanks for yet another useless language then

**Comment by JalonSolov** [comment]
There are lots of languages out there, if you don't care for V.  No reason to make yourself unhappy about it.

**Comment by caryyu** [comment]
> right calling functions and operators in an OBJECT is not "object oriented programming" omg... you guys are soo disappointing... thanks for yet another useless language then

LOL, I'd better to keep staying in Pascal. didn't see the advantages comparing to Zig so far.
