### ISSUE TITLE
cannot compile on `windows`

### ISSUE THREAD

**Issue by LollipopFt** [vlang/v#15598]
error:
```
vlib/os/os.c.v:778:25: error: the final expression in `if` or `match`, must have a value of a non-void type
  776 | // chdir changes the current working directory to the new directory in `path`.
  777 | pub fn chdir(path string) ? {
  778 |     ret := $if windows { C._wchdir(path.to_wide()) } $else { C.chdir(&char(path.str)) }
      |                            ~~~~~~~~~~~~~~~~~~~~~~~
  779 |     if ret == -1 {
  780 |         return error_with_code(posix_get_error_msg(C.errno), C.errno)
```

command used: `make.bat` in `v` directory (downloaded from releases)

**Comment by JalonSolov** [comment]
Do `git pull` then `.\make.bat` again.

**Comment by LollipopFt** [comment]
```
vlib/builtin/array.c.v:1:1: error: invalid expression: unexpected keyword `module`
    1 | module builtin
      | ~~~~~~
```

**Comment by LollipopFt** [comment]
and when `v self -prod`, how do i know if i am using `clang`, `cl` or `tcc`?

**Comment by JalonSolov** [comment]
No idea why it would complain about the `module` keyword.  Something seems very wrong with your V install.  I would delete what you have and start over by cloning the repo - that's the preferred way to install V:  https://github.com/vlang/v#installing-v---from-source-preferred-method

As for the compiler, you can force which one to use with the `-cc` option, as in
```
v -cc clang -prod self
```
It's better to do the initial `make.bat` with tcc, as it's a _much_ faster compiler, which also means it will fail faster if there's something wrong.  Then if you really want to have an optimized version of the compiler, use the command above, or just `v -prod self` since that will force using something other than tcc.

If you haven't already, I highly recommend installing gcc/clang from https://winlibs.com - that version definitely gives the best experience on Windows.  Other versions are... problematic (and usually not the latest).

**Comment by LollipopFt** [comment]
thanks for this comprehensive answer! i'm excited to see what i can do with it.
