### ISSUE TITLE
% 0 operation causes core dump

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#1571]
**V version:**  0.1.17
**OS:**  Windows 10 or Linux

**What did you do?**

println(100 % 0)

**What did you expect to see?**

compiler error 

**What did you see instead?**

Program compiles, but at execution gives:  Floating point exception (core dumped)

**Comment by iredmail** [comment]
This is interesting. Here's my code:

```
fn main() {
    a := (100%0)
    println(a)

    println(100%0)
}
```

Running result:

```
$ v a.v 
$ ./a
23290192
73896

$ ./a
194900304
73896

$ ./a
117129552
73896
```

**Comment by MaD70** [comment]
Division by zero is usually a run-time error because it's hard or impossible to catch at compile-time except in trivial cases like this.

Consider for example the case `println(100 % a)` where `a` is an integer inputted from the user at run-time. How do you catch this at compile-time?

Another case: `a` may be the result of a complex calculation. If this complex calculation can be carried out completely at compile-time one could think to let the compiler emit a compilation error. But this require [constant propagation](https://en.wikipedia.org/wiki/Constant_folding) to be quite sophisticated.

**Comment by medvednikov** [comment]
Fixed.

Simple cases like this should be handled @MaD70.
