### ISSUE TITLE
Anonymous struct declared inside another struct cannot be used by external module

### ISSUE THREAD

**Issue by JGabrielGruber** [vlang/v#15763]
Hello there!

V full version: V 0.3.1 f2f6ea5

I've defined a struct:

```v
module models

pub struct Settings {
	pub mut:
		user_settings struct {
			pub mut:
				default_active bool = true
				default_verified bool	
		}
}
```

And tried to use it:

```v
module tests

import models

fn test_settings_model_creation() {
    settings := models.Settings{
        user_settings: struct {
            default_verified: true
        }
    }
    assert settings.user_settings.default_verified == true
}
```

It gave me this error:

```v
src/tests/models_test.v:22:31: error: struct `models._VAnonStruct1` was declared as private to module `models`, so it can not be used inside module `tests`
   20 | fn test_settings_model_creation() {
   21 |     settings := models.Settings{
   22 |         user_settings: struct {
      |                               ^
   23 |             default_verified: true
   24 |         }
```

(I'm aware that I'm anti the recommended V pattern, I'm sorry for that)

One option would be to declare the **user_settings** struct, but, is there another option?

**Comment by shove70** [comment]
This looks like a checker error

**Comment by shove70** [comment]
@All

Thank you for your advice.

Because there is no definition syntax such as "pub" for anonymous structures, when "parser. struct_decl()" reads and parses the "token" stream, The "is_pub" attribute is always assigned a value of false.

In other words, in the original design of V, it is not allowed to access anonymous structures in different modules.

This is very understandable for us.

However, users may have some doubts, especially when the parent structure is defined as "pub", or the anonymous structure itself is within the scope of "pub" (such as the "user_settings" field in this case).

We suggest that this design should remain unchanged, or can it inherit "pub" upward?

Thank you!
