### ISSUE TITLE
generics with module name does not work

### ISSUE THREAD

**Issue by ghost** [vlang/v#16081]
**V version: 0.3.1 6e46933** 
**OS: ArchLinux** 

**What did you do?**
```
> tree .
.
├── bug.v
├── mod
│   └── mod.v
└── v.mod
```
bug.v
```v
module main

import mod

struct List<T>{
	data []T
}

struct Foo{}

fn foo<T>(){}

fn main(){
	_ := mod.List<Foo>{}
	foo<List<Foo>>()
	foo<mod.List<Foo>>()
}
```
mod.v
```v
module mod

pub struct List<T>{
	data []T
}
```

**What did you expect to see?**
No error
 
**What did you see instead?**
```
> v run bug.v
bug.v:16:19: error: unexpected token `>`, expecting `{`
   14 |     _ := mod.List<Foo>{}
   15 |     foo<List<Foo>>()
   16 |     foo<mod.List<Foo>>()
      |                      ^
   17 | }
```

**Comment by i582** [comment]
Interestingly, if you add `[]`:

```v
foo<[]mod.List<Foo>>()
```

Then everything works, apparently the function `Parser.is_generic_call()` mistakenly thinks that `foo<mod.List<Foo>>()` is not a generic call.

**Comment by kahsa** [comment]
I haven't looked closely at the compiler code, so I can only guess, but I imagine that because the author is concerned about compile speed and small file size, the compiler program assumes that the user's source code is written correctly and does not assume that mistakes will be made. I imagine that the compiler program is structured in such a way that it assumes that the user's source code is written correctly and does not assume that mistakes will be made.

I've never written a compiler, so I'm not sure, but I would think that it would be designed with a robust systematic structure first, and such speed and such would be adjusted after development enters the speed optimization phase.

**Comment by Delta456** [comment]
The above code compiles when using the new generic syntax.

bug.v

```v
module main

import mod

struct List[T]{
	data []T
}

struct Foo{}

fn foo[T](){}

fn main(){
	_ := mod.List[Foo]{}
	foo[List[Foo]]()
	foo[mod.List[Foo]]()
}
```

mod.v

```v
module mod

pub struct List[T]{
	data []T
}
```
