### ISSUE TITLE
Omission of global function body triggers a compiler bug

### ISSUE THREAD

**Issue by srackham** [vlang/v#16212]
**V version:** V 0.3.1 572e262
**OS:** linux, Ubuntu 22.04.1 LTS (VM)

**What did you do?** Executed the following code with the `-enable-globals` compiler option:
```v
__global f = fn ()
```

**What did you expect to see?** A `missing function body` error.
 
**What did you see instead?**
```
$ v -enable-globals run bug.v 
==================
tcc: error: undefined symbol 'anon_fn_70a6b7e29084d475__19'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.
```

**Comment by Wajinn** [comment]
I'm kind of confused at what is trying to be done.  If one wants `f` to be a global variable, you don't need to add a function to it.  You can assign a function, later.

As for the function, it appears what is being looked for is type declaration/function signature (https://github.com/vlang/v/blob/master/doc/docs.md#function-types).

I suppose its hard to tell, because the amount of code is so little, and its not explained what is the goal.

**Comment by srackham** [comment]
@Wajinn The code is not trying to do anything other than reveal a compiler bug (as per the V Bug template: "Please include the standalone minimal reproducible code").

FWIW, the actual code arose while porting some Go code verbatim. The fix was trivial: just append `{}` to the declaration, but that's not the point.

**Comment by JalonSolov** [comment]
Yes, any time you see a C error, it is a bug in V.  V should have at least noticed something was wrong, and given an error message before the code was ever handed off to the C compiler.
