### ISSUE TITLE
`Pair<K, V>` built-in

### ISSUE THREAD

**Issue by kahsa** [vlang/v#16252]
It can be called from anywhere _without a module prefix_, so I would like this to be **built-in**.
```v
pub struct Pair<K, V>{
pub mut:
	key K
	value V
}

pub fn pair<K,V>(key K, value V) Pair<K,V>{
	return Pair<K,V>{
		key: key
		value: value
	}
}
```
Key-Value pairs are often used, although they can be substituted with a map, but that can be inconvenient.

**Comment by spytheman** [comment]
Please show some usage patterns.

**Comment by kahsa** [comment]
This can be used in many situations.
However, a `map` can be a good substitute if it can

1. accessible by index 
2. duplicate keys

However, there is no plan to make the map such a specification in the future, is there?
That is why this Pair structure is useful.

**Comment by kahsa** [comment]
```v
mut key := ''
mut value := ''
for k, v in one_element_map{
    key = k
    value = v
}
```
This is one of the messy examples with map.

**Comment by kahsa** [comment]
If the order in which the maps are added is guaranteed, I think we could do `k, v := map.index(0)`.

**Comment by kahsa** [comment]
I got an idea!
Is there a mechanism to call a specific module without a module prefix as well as the built-ins?
That would solve this problem.
@spytheman

**Comment by spytheman** [comment]
> This can be used in many situations.

That is what I am asking for, please describe some of them more concretely.

**Comment by spytheman** [comment]
> I got an idea! Is there a mechanism to call a specific module without a module prefix as well as the built-ins? That would solve this problem. @spytheman

afaik there is not a custom one; you can use preludes, but they are only used as part of your `main` module 🤔 .

**Comment by spytheman** [comment]
> Is there a mechanism to call a specific module without a module prefix as well as the built-ins?

Another thing you can do, that while not exactly what you want, could help a little with "extending" the `builtin` module, without actually modifying it, is abusing `v run .` and putting a toplevel file, that starts with `module builtin`:
![image](https://user-images.githubusercontent.com/26967/198870991-ab790e31-51a7-469c-a480-727e3dc83747.png)

Note how the program works, even though `./mymodule/abc.v` does not import explicitly `my_builtins.v` from the top level, because it is compiled as part of `builtin` due to the `module builtin` at its top.

**Comment by kahsa** [comment]
Thanks for thinking about it !
