### ISSUE TITLE
v0.1.18, Compile error on mingw64:  

### ISSUE THREAD

**Issue by changrui** [vlang/v#1626]
**V version:** 
v0.1.18

**OS:** 
Windows 10

**What did you do?**
gcc -std=gnu11 -w -o v1.exe v.c -lm

**What did you expect to see?**
compile OK.
 
**What did you see instead?**
$ gcc -std=gnu11 -DUNICODE -D_UNICODE -w -o v1.exe v.c
vc/v.c: In function 'os__ls':
vc/v.c:4824:32: error: dereferencing pointer to incomplete type 'struct dirent'
     string name = tos_clone(ent->d_name);

**Comment by Tembocs** [comment]
I'm on Windows 10 x64, and can confirm that had the same error.

**Comment by AtjonTV** [comment]
@changrui You actually posted two different gcc commands!?

Which one did you run?

A:
```
gcc -std=gnu11 -w -o v1.exe v.c -lm
```

B:
```
gcc -std=gnu11 -DUNICODE -D_UNICODE -w -o v1.exe v.c
```

(I am on linux and the B command fails here too, but the A command works just fine; Note: gcc is a alias to Clang 8)

**Comment by spytheman** [comment]
The error is caused by using v.c produced on *nix on windows .

A temporary fix is:
1) curl -o v.c -LsSf https://raw.githubusercontent.com/vlang/vc/master/v.c
2) edit v.c line 114:
`
#ifndef _WIN32
#include <dirent.h>
#endif
`
should become just
`
#include <dirent.h>
`
3) gcc -std=gnu11 -DUNICODE -D_UNICODE -w -o v2.exe v.c
4) v2.exe -o v.exe compiler

**Comment by INFINITEBUG404** [comment]
> 该错误是由在Windows上使用* nix生成的vc引起的。
> 
> 临时修复是：
> 
> 1. curl -o vc -LsSf [https://raw.githubusercontent.com/vlang/vc/master/vc](https://raw.githubusercontent.com/vlang/vc/master/v.c)
> 2. 编辑vc第114行：
>    `#ifndef _WIN32 #include <dirent.h> #endif`
>    应该变得公正
>    `#include <dirent.h>`
> 3. gcc -std = gnu11 -DUNICODE -D_UNICODE -w -o v2.exe vc
> 4. v2.exe -o v.exe编译器



> 该错误是由在Windows上使用* nix生成的vc引起的。
> 
> 临时修复是：
> 
> 1. curl -o vc -LsSf [https://raw.githubusercontent.com/vlang/vc/master/vc](https://raw.githubusercontent.com/vlang/vc/master/v.c)
> 2. 编辑vc第114行：
>    `#ifndef _WIN32 #include <dirent.h> #endif`
>    应该变得公正
>    `#include <dirent.h>`
> 3. gcc -std = gnu11 -DUNICODE -D_UNICODE -w -o v2.exe vc
> 4. v2.exe -o v.exe编译器


C@DESKTOP-AH8C2AC MINGW64 /e/v (master)
$ gcc -std=gnu11 -DUNICODE -D_UNICODE -w -o v2.exe v.c
v.c: In function 'init_consts':
v.c:19843:29: error: '_O_U8TEXT' undeclared (first use in this function); did you mean 'O_TEXT'?
   _setmode(_fileno(stdout), _O_U8TEXT);
                             ^~~~~~~~~
                             O_TEXT
v.c:19843:29: note: each undeclared identifier is reported only once for each function it appears in

**Comment by spytheman** [comment]
I am not sure for the proper solution for this problem.

The underlying problem is the way _nix.v vs _win.v files are compiled.

The idea behind them, is to split platform specific implementations into their own files, instead of littering v source with compile time conditionals.

Right now, v just skips the _platform.v files that do not match the current platform, on which the .c file is produced. It also puts #includes from _platform.v files in the resulting .c file, surrounded by conditional #ifdef guards (which was needed for compilation with msvc). 

The actual body of the generated c functions from the _platform.v file is not guarded.

That leads to the current situation, where os.ls was moved to os_nix.v and os_win.v , v.c was generated on a *nix platform, so v.c contained a guarded #include <dirent.h>, and os.ls implementation comes from os_nix.v, and needs a definition for the C dirent struct, which is not provided on windows, because of the guarded include.

Possible solutions:
A) Most generic (and timeconsuming for the moment): compile *all* _platform.v files in the same v.c file. Guard not only the #include lines, but the generated C definitions as well. In this way v.c will be bigger, but each platform would get exactly what it can handle, there will be no missing parts so to speak. Skipping stuff for other platforms will be done by the C preprocessor guards.

B) Most expedient solution: provide a proper C dirent struct definition for windows mingw64, by using
$if windows {
}
inside os_nix.v

According to my mingw64 headers, it is:
struct dirent
{
 long d_ino;
 unsigned short d_reclen;
 unsigned short d_namlen;
 char d_name[260];
};

C) Generate separate v.c files for all the supported platforms ?

**Comment by medvednikov** [comment]
I'll fix this by generating a v_win.c

I've wanted to do this for a while.

**Comment by medvednikov** [comment]
Fixed.
