### ISSUE TITLE
request: Rename the float types to mark the backward compatibility to C like "f32c" and "f64c", and add some new ones with the old names and correct math

### ISSUE THREAD

**Issue by debilosaurus** [vlang/v#16429]
playground

```
println("f32: 0.1\*0.5 = "+(f32(0.1)*f32(0.5)).str()+" -> okay")
println("f32: 0.1\*0.1 = "+(f32(0.1)*f32(0.1)).str()+" -> why so much zeroes?")
println("f64: 0.1\*0.1 = "+(f64(0.1)*f64(0.1)).str()+" -> i dont trust you ...")
```

**What did you expect to see?**
I am no computer scientist, so maybe this values make sense in some way,
but I expected somehow mathematical correct values.
 
**What did you see instead?**
```
f32: 0.1*0.5 = 0.05 -> okay
f32: 0.1*0.1 = 0.01000000 -> why so much zeroes?
f64: 0.1*0.1 = 0.010000000000000002 -> i dont trust you ...
```

**Comment by JalonSolov** [comment]
The numbers can be explained fairly easily by knowing that floating point is implemented to the IEEE-754 standard... which can show round-off errors, etc., such as shown in your example.

Your example can also be simplified a bit...
```v
println('f32: 0.1*0.5 = ${f32(0.1)*f32(0.5)} -> okay')
println('f32: 0.1*0.1 = ${f32(0.1)*f32(0.1)} -> why so much zeroes?')
println('f64: 0.1*0.1 = ${f64(0.1)*f64(0.1)} -> i dont trust you ...')
```
IEEE-754 standard is the most common floating point implementation, used by V, C, and most other programming languages, as well as most floating point hardware.

**Comment by medvednikov** [comment]
In Go it's handled nicely:

https://go.dev/play/p/2pdcG5LbfiB

```
f32: 0.1*0.5 = 0.050000 
f32: 0.1*0.1 = 0.010000  
f64: 0.1*0.1 = 0.010000  
```

**Comment by JalonSolov** [comment]
Yep... because they force rounding, etc.  V doesn't.  There are lib routines to do it if you want.

**Comment by JalonSolov** [comment]
It would actually be more preferable if correctness were the main goal, except that it would be completely against the way almost everything else works.

For example, if you translate C code to V code, you could wind up with different results between the 2 versions, even though the code "looks" correct, because V would doing the math more correct than the C code, without changing anything.

Otherwise, during your conversion, you couldn't just keep `0.1 * 0.1`, you would have to translate that to `math.ieee754.mult(0.1, 0.1)` or similar, making translating code much harder.

Perhaps when there is as much V code as there is C code, this would be acceptable.  Right now, it actually makes sense to support ease of translation, while allowing users to have the more correct values _if_ they decide they want them.

**Comment by spytheman** [comment]
> Yep... because they force rounding, etc. V doesn't. There are lib routines to do it if you want.

There is also the builtin string interpolation formatting:
```v
println('f32: 0.1*0.5 = ${f32(0.1)*f32(0.5):0.6f}')
println('f32: 0.1*0.1 = ${f32(0.1)*f32(0.1):0.6f}')
println('f64: 0.1*0.1 = ${f64(0.1)*f64(0.1):0.6f}')
```
which produces:
```
f32: 0.1*0.5 = 0.050000
f32: 0.1*0.1 = 0.010000
f64: 0.1*0.1 = 0.010000
```
