### ISSUE TITLE
Bitshift issue / u64 not converted (automatically)

### ISSUE THREAD

**Issue by mvlootman** [vlang/v#1666]
**V version:0.1.18** 
**OS: macOS Mojave** 

**What did you do?**
bitshift 1 by n places ( > 30 )
```
println( u64(1) << u64(30))
println( u64(1) << u64(31))
println( u64(1) << u64(32))
```

**What did you expect to see?**
1073741824
2147483648
4294967296
 
**What did you see instead?**
1073741824    (ok)
-2147483648 (err)
0  (err)

workaround was adding an additional conversion, which yields the correct result
```
println( u64(u64(1) << u64(30)))
println( u64(u64(1) << u64(31)))
println( u64(u64(1) << u64(32)))
```

As a sidenote this also does not work:
```
mut a := u64(0)
a = u64(1) << u64(31)
println(a)
```

**Comment by baziotis** [comment]
The problem is that the compiler regards any `<<` expression (meaning arithmetic, not arrays) as having `int` type hence the problem.
Check:
https://github.com/vlang/v/blob/master/compiler/parser.v#L2126
For example, if you change this to `u64`, it works for your cases. But of course, a more thoughtful type-checking has to happen there. Plus, the left-shift has UB considerations on it, which C will handle for now.

**Comment by Henrixounez** [comment]
Generated C code is : 
```
/*opt*/printf ("%llu\n", ((u64)(((u64)(1)) << ((u64)(30)))));
/*opt*/printf ("%llu\n", ((u64)(((u64)(1)) << ((u64)(31)))));
/*opt*/printf ("%llu\n", ((u64)(((u64)(1)) << ((u64)(32)))));
```
Seems fine to me

**Comment by baziotis** [comment]
This is the generated code if you use the workaround, which is correct because it uses `%llu`.
And this is because in the workaround, he casts the expression to a `u64` hence the correct specifier is used.
But without it, it defaults to `int`, and `%d` is used. It shouldn't. At least if we follow C/C++.
`uint64_t << uint64_t` yields a `uint64_t`.

**Comment by mvlootman** [comment]
Retested this with V0.1.23 d71532b and now gives the expected result.
