### ISSUE TITLE
checker: `match` expression with bail conditions requires expression

### ISSUE THREAD

**Issue by l1mey112** [vlang/v#16696]
### Describe the bug

Expression based match statements require expressions on each branch. Sometimes match branches can be error conditions requiring a panic or leave from a function without an expression. In some edge cases the checker would require an unneeded expression, this is where the bug presents itself.

### Expected Behavior

This works fine, panic/noreturn calls are checked.

```v
fn this_works_perfectly_fine() {
	a := match true {
		true {
			2
		}
		false {
			panic("err") // panics are checked fine
		}
	}
}
```

Return statements, which constitute should act the same as a panic call, cause the checker to fail on a missing expression.

```v
fn opt()! {
	a := match true {
		true {
			2
		}
		2 == 2 {
			return error("hello")
		}
	}
}
```

```
a.v:10:4: error: `match` expression requires an expression as the last statement of every branch
    8 |         }
    9 |         2 == 2 {
   10 |             return error("hello")
      |             ~~~~~~~~~~~~~~~~~~~~~
   11 |         }
   12 |     }
```

This is a dirty hack employed in my code.

```v
fn always_err(msg string)! {
	return error(msg)
}

fn this_works()! {
	a := match true {
		true {
			2
		}
		false {
			5
		}
		2 == 2 {
			always_err("hello")!
			0 // unneeded expr
		}
	}
}
```

### Current Behavior

(refer above)

### Reproduction Steps

(refer above)

### V version

V 0.3.2 b54f9c2.65a020e

### Environment details (OS name and version, etc.)

OS: linux, "Arch Linux"

**Comment by yuyi98** [comment]
I think that's reasonable for the error message, let's not complicate things.

**Comment by l1mey112** [comment]
But panics are okay? It seems that the V checker checks for circumstances where a `noreturn` function is being called but fails to check for early returns. Being able to return an error or return early should be possible in expression match statements.

**Comment by JalonSolov** [comment]
Panic is ebil.  Should never be used unless continuing would cause your hard drive to be wiped, or other totally catastrophic failures.  The reason is that is is _AN IMMEDIATE ABORT_ from your code - nothing is cleaned up, no files are closed, etc.

So of course a panic will "work" in this case.

Try your match without trying to assign the value to a variable.  In other words, something like this:
```v
	mut a : = 0
	match true {
		true {
			a = 2
		}
		2 == 2 {
			return error("hello")
		}
		else {}
	}
```
the problem seems to be that V is triggering on the fact that `return` is a statement, not an expression, so there's nothing that can be stored in `a` from that branch.

Should it work this way?  Perhaps not... but that's a discussion point, not a bug.  (My example just complains that `a` is unused.)
