### ISSUE TITLE
Cannot use enum field as fixed array length

### ISSUE THREAD

**Issue by i582** [vlang/v#18310]
### Describe the bug

Code: https://vosca.dev/p/8f50b6dcd2

```v
enum Foo {
	first
	second
	
	_end
}

a := [Foo._end]int{}
println(a)
```

### Expected Behavior

No errors

### Current Behavior

Output:

```
code.v:8:7: error: fixed array size cannot use non-constant value
    6 | }
    7 | 
    8 | a := [Foo._end]int{}
      |       ~~~~~~~~
    9 | println(a)
   10 |
Exited with error status 1
```

### Reproduction Steps

Run code above

### V version

V 0.3.4 fc4c431.45f16a2

### Environment details (OS name and version, etc.)

```
V full version: V 0.3.4 fc4c431.05b832a
OS: linux, Ubuntu 22.04.2 LTS
Processor: 2 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz

getwd: /home/pmakhnev/playground
vexe: /home/pmakhnev/v/v
vexe mtime: 2023-05-29 18:00:08

vroot: OK, value: /home/pmakhnev/v
VMODULES: OK, value: /root/.vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.34.1
Git vroot status: weekly.2023.21-45-g05b832a3
.git/config present: true

CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

**Comment by JalonSolov** [comment]
First, it can only work if the implementation of `enum` stays as it is.

2nd, it's _extremely_ fragile, because if you add another enum, the values can change "unexpectedly" (as far as how large an array gets created).

Example:  Your code will cause `a.len == 2`.  If you add an `enum` such as
```v
enum Foo {
	first
	second
	third
	
	_end
}
```
now `a.len == 3`.

Is there a real reason to use `enum`s instead of `const`s?  At least `const` values won't change unless you manually edit them.
