### ISSUE TITLE
Array of runes, remove ustring

### ISSUE THREAD

**Issue by Molochnikov** [vlang/v#1843]
Your tutorial doesn't have an example how to covert **string** of bytes to array of **runes**. Can you add it please?

For example in Go we can do this:

`s := "Hello World 👋"`
` r := []rune(s)`

**Comment by ntrel** [comment]
This should be done with a function rather than a built-in IMO. It's not just casting UTF-8.

**Comment by Molochnikov** [comment]
> This should be done with a function rather than a built-in IMO. It's not just casting UTF-8.

So does this functionality exists now? Can't find this funtion.

**Comment by ntrel** [comment]
In vlib/builtin/string.v there's ustring, but I've not used it. I don't think it's documented. That has a field called runes, which is an array of int. It's a shame if V has decided to remove the `rune` distinct type, confusing the two is bug prone.

**Comment by ntrel** [comment]
In builtin there's also a file utf8.v, that has a function utf32_code which converts the first character in a UTF-8 string to an int (sigh) that represents a rune. This code could be adapted to write a UTF-8 string to rune array function.

**Comment by medvednikov** [comment]
> It's a shame if V has decided to remove the rune distinct type, confusing the two is bug prone.

It was not removed, it's simply not implemented yet :)

**Comment by medvednikov** [comment]
@Molochnikov for now you have to use a hacky `str.ustring()`

It's not documented because it's a temporary solution.

**Comment by Molochnikov** [comment]
> @Molochnikov for now you have to use a hacky `str.ustring()`
> 
> It's not documented because it's a temporary solution.
> 
> Check out freetype.v for an example.

Thanks! But why we have 7th index here:

`s := 'Привет⏳️World'`
`us := s.ustring()`
`println(us.len.str())`
`println(us.runes.len.str())`
`for j := 0; j < us.len; j++ {`
`	print(j)`
`	print(' ')`
`	print(us.at(j))`
`	print(' ')`
`	println(us.runes[j])`
`}`

13                                                                                                                                   
13
0 П 0
1 р 2
2 и 4
3 в 6
4 е 8
5 т 10
6 ⏳ 12
7 ️ 15
8 W 18
9 o 19
10 r 20
11 l 21
12 d 22

**Comment by shadowninja55** [comment]
this is done.

**Comment by JalonSolov** [comment]
Perhaps an explanation...  :-)

A recent change to V now supports a `.runes()` method on strings.  `ustring` has been removed.

However, it does still seem to be printing that 7th item...
```v
s := 'Привет⏳️World'
println(s.len)
println(s.runes().len)

for i, r in s.runes() {
        println('$i $r')
}
```
Output is:
```
23
13
0 П
1 р
2 и
3 в
4 е
5 т
6 ⏳
7 ️
8 W
9 o
10 r
11 l
12 d
```

I'll reopen so someone (@danieldaeschle  ?) can take a look.

**Comment by danieldaeschle** [comment]
Oh no :D

**Comment by danieldaeschle** [comment]
I think it's valid because the code behind that is this:
![image](https://user-images.githubusercontent.com/30751516/124878255-31fe3d80-dfcc-11eb-9eaf-6e9fc9a742f7.png)

```
Breakpoint 1, main__main () at /tmp/v/../../../../../../home/daniel/Projects/modulebasics/main.v:5
5               println('$i $r')
(gdb) n
7 ️
6       }
(gdb) p i
$5 = 8
(gdb) p r
$6 = 65039
```

Here is the wikipedia article: https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)

@hungrybluedev What do you think?

**Comment by hungrybluedev** [comment]
It's similar to the skin tone selector for emojis. This problem occurs because like Daniel mentioned, it is a control character. 32 bits is not enough to represent all emojis (for example) along with all possible variations.

Therefore this character (although invisible) indicates to the renderer that "this particular variant of the previous character must be used". We cannot disregard these control characters because then we risk losing the variant information. But we cannot combine the two into a single `rune` because that would inflate the size.

I think it's better to accept it as recognised behaviour and that some emojis and other compound characters require 2 runes. Like in this example, the hourglass.

**Comment by danieldaeschle** [comment]
Go has the same behaviour: https://play.golang.org/p/I_aPNto5MBi
