### ISSUE TITLE
Crash when interpolating structure in structure's str method (infinite recursivity)

### ISSUE THREAD

**Issue by Henrixounez** [vlang/v#1905]
**V version:** 0.1.18
**OS:** Linux

**What did you do?**
```
struct Test {
	a int
}

fn (t Test) str() string {
  return '$t'
}

fn main() {
	a := Test{}
	println(a.str())
}
```

**What did you expect to see?**
Not compile ? Not crash ?
 
**What did you see instead?**
```
fish: “./test” terminated by signal SIGSEGV (Address boundary error)
```
The generated C code :
```
string Testy_str(Testy t) {
	return  _STR("%.*s ", Testy_str(t).len, Testy_str(t).str) ;
}

int main(int argc, char** argv) {
 	init_consts();
	Testy a = (Testy) { .a = 0 };
	println(Testy_str( a )); 
}
```

**Comment by spytheman** [comment]
I think v may produce a warning in this case (when the parameter of a method str() is used in interpolation done inside the str() method), may be`possible infinite recursion`, but recursion in general should be supported, and there may have been other statements before the '$t', that modified/simplified t, so that the recursion is not infinite regress does not happen.

**Comment by spytheman** [comment]
Actually no, changing things while getting their string representation is not a good idea in general. It should be an error.
