### ISSUE TITLE
Constructors for structs

### ISSUE THREAD

**Issue by oleg-kachan** [vlang/v#2203]
It seems that structs are missing constructors now.

Any intent to add them?

**Comment by medvednikov** [comment]
No, just like in Go, structs can be constructed with functions, like `new_foo()`.

**Comment by oleg-kachan** [comment]
I mean what if some background work should be done on initialization? Assigning unique hash to _id field, for example:

```
struct Mystruct {
  _id int
  value string
}

fn (m mut Mystruct) __constructor() {
  m._id = unique_hash_id()
}

mut my := Mystruct{value: "value"}
```

**Comment by medvednikov** [comment]
Yes, you can use a function for that:

```
fn new_mystruct(value string) MyStruct{
  return MyStruct{
   value: value
   _id = unique_hash_id()
  }
}
mut my := new_mystruct(value)
```

V is a simple language.  Besides, structs are not classes, there's no OOP in V.

**Comment by yashsamit** [comment]
`
//THIS is not POSSIBLE
pub struct Margin {
    top f64
    right f64
    bottom f64
    left f64
}

// if the static method allowed 
pub fn new()  Margin {}

pub type Padding = Margin
pub type Rect = Margin

Padding::new()
Margin::new()
Rect::new()


// Alternate seems ugly
// We have to add new_margin() and use the same fn for other types or create many new variants. 
// It becomes ugly when we have other constructors also like 
from_vals(a, b, c, d) 
from_val(a)

//etc


`

We can't name the module in any file because it is based on dir. I have all files inside types dir.
If the custom name of the module is allowed then it will very neat and clean.

It will like

`
//margin and padding are module names
margin.new()
padding.new()

//Right now to achieve this, I have to create 4 folders for small files. 


`
In the doc, it mentioned that v is very modular. I feel without a filename based module name, it's not that much modular.

Solutions:
- Support custom module name based on file but not folder. 
- Add support https://github.com/vlang/v/issues/11532
- Constructor support.
