### ISSUE TITLE
tcc compiler not detected without path

### ISSUE THREAD

**Issue by lcheylus** [vlang/v#22204]
### Describe the bug

On OpenBSD (current/amd64), TCC compiler is not available in Vlang repository (https://github.com/vlang/tccbin). I have installed it via OpenBSD package (`pkg_add tcc`).

If I tried to compile/run V code with tcc compiler, its installation path is not detected and the default compiler (defined via `cc`) is used.

### Reproduction Steps

- Clone V sources on OpenBSD (current/amd64)
- Build with Clang 16.0.6 (`./v version => V 0.4.7 e0422de`)
- TCC compiler installed on OpenBSD via `tcc` package
```bash
$ doas pkg_add tcc

$ which tcc
/usr/local/bin/tcc
$ tcc -v
tcc version 0.9.27 2023-07-05 mob@5b28165 (x86_64 OpenBSD)
```

- V code to get compiler used during build/run:
```v
fn main() {
        $if tinyc {
                println("tcc")
                exit(0)
        } $else $if clang {
                println("clang")
                exit(0)
        } $else $if gcc {
                println("gcc")
                exit(0)
        }

        println("different compiler")
}
```

### Expected Behavior

TCC compiler installed via packages/ports, available in system paths (defined via env. `$PATH`) should be detected during build.

### Current Behavior

- Run code with `clang`: **OK Clang detected**
```bash
$ ./v -cc clang run ~/tmp/get_compiler.v
clang
```

- Run code with `gcc` (GCC binary named `egcc` on OpenBSD): **OK GCC detected**
```bash
$ ./v -cc egcc run ~/tmp/get_compiler.v
gcc
```

- Run code with `tcc` with path (`dynamic_boehm` option necessary on OpenBSD for TCC, see issue #22156): **OK TCC detected**
```bash
$ ./v -d dynamic_boehm -cc /usr/local/bin/tcc run ~/tmp/get_compiler.v
tcc
```

- Run code with `tcc` without path: **NOK TCC not detected**
```bash
$ ./v -d dynamic_boehm -cc tcc run ~/tmp/get_compiler.v
different compiler
```

### Possible Solution

After some debug/tests, detection of `tcc` binary is done in `default_tcc_compiler` function (`vlib/v/pref/default.v`). 

I propose to improve the detection of TCC compiler if installed in system paths. I already have a working code for this.

### V version

V 0.4.7 e0422de

### Environment details (OS name and version, etc.)

V full version: V 0.4.7 e0422de
OS: openbsd, 7.6, GENERIC.MP#307
Processor: 2 cpus, 64bit, little endian

getwd: /home/fox/dev/vlang.git
vexe: /home/fox/dev/vlang.git/v
vexe mtime: 2024-09-12 08:58:07

vroot: OK, value: /home/fox/dev/vlang.git
VMODULES: OK, value: /home/fox/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.46.0
Git vroot status: weekly.2024.36-47-ge0422de8-dirty
.git/config present: true

CC version: OpenBSD clang version 16.0.6
thirdparty/tcc: N/A
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
The reason V doesn't use the system installed tcc is because of exactly what you showed in the version above - that version of tcc is far too old to work correctly for V.

If you run `make`, it will try to install a "good" version of tcc for you under the `thirdparty/tcc` directory under the V install dir.  However, since there isn't a version of tcc built for your system, it won't be able to install anything.

You can force V to use the system installed version of tcc by supplying the full path with the `-cc` option, but that isn't likely to work as well, since it's an older version.

The other option is to submit a PR to https://github.com/vlang/tccbin to add a version of tcc for your system, using the instructions on that page to build an appropriate version.

Or you can just build it and install it yourself under `thirdparty/tcc`.  Note that V expects the executable to be named `tcc.exe` - this is for consistency, since Windows requires the extension, but none of the other systems care about it.

**Comment by lcheylus** [comment]
PR created just now for a prebuilt TCC binary for OpenBSD/amd64 => https://github.com/vlang/tccbin/pull/54

**Comment by lcheylus** [comment]
Closed: tcc works for compilation with V on OpenBSD/amd64 :)
- `tcc` compiler now available for OpenBSD/amd64 in `vlang/tccbin` repository
- issue #22156 resolved
