### ISSUE TITLE
Mutating container elements

### ISSUE THREAD

**Issue by ntrel** [vlang/v#234]
In #230, we discussed functions returning mutable references. Alex suggested it would be simpler to support index operator overloading e.g. `container[0] = 42`. This issue explores this.

To avoid having the index function return a reference, the container could overload index and assign combined:
```rust
fn (mut c Container) [i usize] = (rhs Element)
```
Some containers can't support indexing efficiently, e.g. linked lists. (So we might also want a generic way to mutate the current element as the container is iterated).

BTW if a container can overload indexing to mutate data, I think an iterator can too using the same language features.

**Comment by ntrel** [comment]
> we might also want a generic way to mutate the current element as the container is iterated

An iterator could have a method:
```rust
fn (mut it Iter) set_current(e Element)
```
(This would panic if the iterator is empty). So I was wrong to say that allowing a function to return a reference is important for iterators, that would only be minor syntax sugar.

**Comment by medvednikov** [comment]
Thanks.

Just like generics, this a big topic. I'll do research on this after the language is open-sourced.

**Comment by ntrel** [comment]
> the container could overload index and assign combined

One problem is that indexed expressions can't be passed as a mutable argument to a function:
```rust
swap(container[i], container [n-1])
```

**Comment by medvednikov** [comment]
And that's a good thing. For clarity, everything should be explicit.

**Comment by medvednikov** [comment]
By the way, I know it's not about `swap`, but it'll be possible to do `container[i], container[n-1] = container[n-1], container[i]`.

**Comment by ntrel** [comment]
&gt; everything should be explicit

How would we explicitly reverse an element of a container of arrays without copying the array twice?

reverse(container[3])

**Comment by ntrel** [comment]
Nevermind, arrays are reference types (assuming we don't support fixed size arrays).

One issue with using a temporary it's that it's lies efficient

**Comment by dumblob** [comment]
>`m[str] = tmp // index has to rehash `str` and find the slot again`

But this can't be avoided with any of the proposed solutions (i.e. it must get rehashed and inserted again at the right place in the container anyway) as otherwise it would break consistency of the container. Sure, there are definitely containers in which consistency won't be broken after such "internal" change (i.e. in-place changes of data), but that still can be implemented in *V* by not mapping such container to *V*s syntax, but rather having a `struct` with methods.

Generally many (most?) containers have problems with efficiency (because they're too often not contiguous in memory and thus not using CPU caches at all - e.g. a [linked list is significantly worse even for gigabytes of data than plain old C array](https://www.youtube.com/watch?v=YQs6IC-vgmo )), so try to avoid containers (and any references/pointers in structs) as much as possible.

Btw. due to these memory issues a very good programming language was designed during the last years - it's https://github.com/BSVino/JaiPrimer - it's worth taking a look what will make *V* potentially slow and adjust *V* semantics accordingly to avoid future performance issues due to anti-performance semantics of *V* (I'm currently a bit lost in the *V*s syntax & semantics due to many rapid changes, so I can't investigate on my own - @medvednikov could you keep the stuff described in the JaiPrimer in mind and adjust *V* accordingly if needed?).

**Comment by lutherwenxu** [comment]
This issue has been closed due to the inactivity.
Please reopen this issue if you want to continue the discussion.
