### ISSUE TITLE
The compiler lets me assign to an array after calling `.free()` on it

### ISSUE THREAD

**Issue by netmute** [vlang/v#2375]
**V version:** V 0.1.21 99e0771
**OS:** macOS 10.14.6

**What did you do?**
```
mut arr := []string
arr.free()
arr << "foo"
```
**What did you expect to see?**
The compiler throwing it in my face.
 
**What did you see instead?**
It did compile. And segfaulted at runtime.

**Comment by Bowero** [comment]
V 0.1.21 c18578a

This does not segfault here.

**Comment by netmute** [comment]
Can't get it to segfault in V 0.1.21 6890034 either.

But this, for example, still compiles and crashes:
```v
fn main() {
  mut arr := []string
  arr << "foo"
  arr.free()
  arr << "bar"
}
```

**Comment by Bowero** [comment]
This also does not segfault for me at V 0.1.21 8a31ee4. Very interesting. 

The generated C code:

```c
void main__main() {
 
array_string arr=new_array_from_c_array(0, 0, sizeof(string), EMPTY_ARRAY_OF_ELEMS( string, 0 ) {   TCCSKIP(0) }) ;
 
_PUSH(& arr , ( /*typ = array_string   tmp_typ=string*/ tos3("foo") ), tmp2, string) ;
 
 v_array_free( arr ) ;
 
_PUSH(& arr , ( /*typ = array_string   tmp_typ=string*/ tos3("bar") ), tmp3, string) ;
 
 }
```

**Comment by Rendims** [comment]
Even when that code doesn't segfault it's most likely still doing invalid writes or pushing data into some other newly allocated object. Not all use-after-free memory corruptions result in segmentation fault.

A safe language should in my opinion require explicitly marking unsafe code and/or somehow check that the memory is still valid before appending to the array and panic otherwise. At least in debug builds and maybe skip checks in release builds for performance.
A guaranteed panic at run time is much better than maybe segfault and otherwise silent memory corruption with undefined behavior.

Detecting every use after free case when compiling is much harder and if it can do that then it would also be able to automatically free the array on its own. No .free() necessary.

**Comment by medvednikov** [comment]
To solve this I've just implemented `unsafe` and made `array.free()` an unsafe method.

It should almost never be used after the new memory model is out.

**Comment by netmute** [comment]
I think we can close this then.
