### ISSUE TITLE
Will you introduce features like SymPy, NumPy, and SciPy into the V language?

### ISSUE THREAD

**Issue by keito940** [vlang/v#2390]
...And Ploting Libary.

**Comment by medvednikov** [comment]
Yes, all part of the language.

**Comment by medvednikov** [comment]
Yes, I should have said "part of vlib" :)

**Comment by medvednikov** [comment]
I'm very passionate about this domain, and I'd like V to have all these capabilities out of the box.

**Comment by keito940** [comment]
Of course, would you like to add features like SciKit-Learn to vlib?

**Comment by christopherzimmerman** [comment]
I have started working on an n-dimensional tensor library modeled after a similar one I have been implementing in Crystal.  In Crystal, I was easily beating the numpy benchmarks, and I think I can continue that trend in v.  I also think having those features as part of the standard library is a really bad idea.

It seems really unnecessary to hold such a domain specific library to the release schedule of a programming language.  It also would introduce many OS specific issues, since any library will most likely be binding to hardware-specific optimized libraries (MKL, BLAS, Accelerate on OSX).
