### ISSUE TITLE
Looking up a missing key in a map

### ISSUE THREAD

**Issue by ntrel** [vlang/v#244]
https://vlang.io/docs#maps:
```rust
println(m['one']) // ==> "1"
println(m['bad_key']) // ==> "0"  
```
I think `m['bad_key']` should panic rather than return a default value, because:
* pointer types can't have a default value in V
* this is what arrays do with a bad index - container types should have the same interface for generic code.

> // TODO: implement a way to check if the key exists 

Use optionals?
```go
fn (m map[K]V) get(key K) ?V;

ob := m.get('bad_key')
assert ob == none
og := m.get('one')
assert og == 1
```
> `map[string]int{}`

~~It's unfortunate that `map` is a keyword, it clashes with functional `map`. Is a keyword necessary~~, could a map type just be e.g. `[string]int`?

**Comment by medvednikov** [comment]
map is not a keyword:

https://vlang.io/docs#keywords

maps are going to behave like in Go:

`m['bad_key'] == 0 (zero value)`

 or

`val := m['bad_key'] or { println('not found'); return }`

I also like Go's approach regarding panics: use them only in very exceptional cases. A missing key is a very common thing and should not result in a panic.

**Comment by medvednikov** [comment]
As for pointer types, not sure how to handle them yet. Maybe that's where a panic would be ok.

**Comment by data-man** [comment]
> ```fn (m map[K]V) get(key K) ?V;```

```fn (m map[K]V) get(key K, default K) V;```
?

BTW:
> map is not a keyword:
> V has 21 keywords: 

What about ```pub```?

**Comment by medvednikov** [comment]
> What about pub?

That's the most recent one. Fixed.

**Comment by ntrel** [comment]
@data-man:
> fn (m map[K]V) get(key K, default K) V;

If https://github.com/vlang/v/issues/129#issuecomment-485017862 is implemented you can mimic your function easily with get returning an optional: `m.get(key) or {default}`. Knowing that a key isn't in a map is important.

**Comment by bjeanes** [comment]
```
val := m['bad_key'] or { 0 }
// or this (I'm not sure yet on `continue` semantics)
val := m['bad_key'] or { continue 0 }
```

Seems like the only consistent (with V) way to do this. The default `or` block could be a panic, but the block should allow for `break`, `continue`, `return`, or fallback value. The spec doesn't seem very clear on if/how an `or` block can provide a non-`none` value (`continue 42`?) but this would make sense. Just because an underlying `fn` has returned an error or empty value, it doesn't mean there is no reasonable way to continue with a default value provided by the caller.

**Comment by avitkauskas** [comment]
Would that work?
val := m['bad_key'] or { val = 0 }

**Comment by bjeanes** [comment]
I think the fallback block should be an expression, not a statement.

Otherwise, how would you express the following:

```
doSomething(myMap['bad_key'] or { 0 })
// or
value * (scale[n] or { 1 })
```

Since Rust is one of V's inspirations, I think it is worth noting that getting a value by key from a map in Rust, [returns an option type](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.get).

This is a _safer_ alternative to both panics and the alternative which is requiring all types to have some kind of unique bottom value (a la Go or `nil`s), which is essentially what V appears to do now (empty string, 0, etc).

Bottom values either requires having NULLs for pointers and functions (like Go) or disallowing functions and pointers as map values (which would be a huge missed opportunity in expressiveness, in my opinion).

**Comment by bjeanes** [comment]
Just a further note: bottom values _feel_ nice for the simple scalar types because they can be interpreted as "identity" values which can be substituted for a real value. But they do not extend to all types (there is no meaningful "identity" pointer and although there is literally an `identity` function, it cannot stand in for any function. In other words, an "identity" value is context sensitive.

This is true even for numbers:

```
1 + identity // identity must be 0
1 * identity // identity must be 1
```

Identity values as defaults only make sense in certain cases (e.g. in variadic operators in a Lisp: `(* 2) ;=> 2`, `(*) ;=> 1`, `(+ 2) ;=> 2`, `(+) ;=> 0`.

**Comment by ntrel** [comment]
> getting a value by key from a map in Rust, returns an option type.

The `get` function does but indexing does not:
```rust
assert_eq!(map[&37], "c");
```
https://doc.rust-lang.org/std/collections/struct.HashMap.html#impl-Index%3C%26%27_%20Q%3E

**Comment by medvednikov** [comment]
@bjeanes yes, map's `get()` will be returning an optional, and `myMap['bad_key'] or { 0 }` syntax will be supported as well.

**Comment by medvednikov** [comment]
@ntrel interesting, Go doesn't allow references to map values at all.

**Comment by lutherwenxu** [comment]
This issue has been closed due to the inactivity.
Please reopen this issue if you want to continue the discussion.
