### ISSUE TITLE
V error: error: cgen.sort_structs() DGNAC.

### ISSUE THREAD

**Issue by vpervenditti** [vlang/v#2487]
**V version:** 
**OS:** 

**What did you do?**
a file with a lot of struct

**What did you expect to see?**
a succesful compilation
 
**What did you see instead?**
`V error: error: cgen.sort_structs() DGNAC.
please create a new issue here: https://github.com/vlang/v/issues and tag @joe-conigliaro
`

**Comment by vpervenditti** [comment]
@joe-conigliaro

**Comment by joe-conigliaro** [comment]
Howdy, can you please supply the code which caused it? Thanks for reporting!

**Comment by vpervenditti** [comment]
here is the code https://gist.github.com/vpervenditti/929ecacd5629cb98a0e3e657c3cf1dd9

**Comment by joe-conigliaro** [comment]
Thanks @vpervenditti, I will get back soon with my findings

**Comment by joe-conigliaro** [comment]
@vpervenditti I have found the issue, there is a circular dependency between `Chat` & `Message`.
I need to add a better error, but that's why I added this in the first place, just to have something to catch these situations.
@medvednikov should this be possible? I think if you use one with typedef and one as just struct it is possible in C. What are your thoughts?

**Comment by joe-conigliaro** [comment]
@vpervenditti I have updated the error to show this in #2517
