### ISSUE TITLE
V error : cannot specify libraries with -c 

### ISSUE THREAD

**Issue by 4whomtbts** [vlang/v#2530]
**V version:** 
V 0.1.21 fcead2f

**OS:** 
Ubuntu 16.04 

**What did you do?**
tried to build module with

v build module ./MY_FOLDER

**What did you expect to see?**
build with success.
 
**What did you see instead?**
![Screenshot from 2019-10-25 02-34-11](https://user-images.githubusercontent.com/34095479/67510466-f88a7f00-f6cf-11e9-96f0-030aa1929429.png)

+ what I did to solve problem
[https://github.com/vlang/v/issues/2410]
sudo apt install libglfw3 libglfw3-dev libfreetype6-dev libssl-dev

+ 
gcc version(I don't have idea which is relevant. though) 
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

Thanks In advance.

**Comment by JalonSolov** [comment]
Closing this issue for several reasons:

1) V no longer uses glfw or freetype.
2) No source was given to try to test/resolve problem.
3) V has gone through so many changes since this report the original code would be unlikely to compile at all.
4) gcc is up to version 10.2.0.  The latest version of ubuntu at least comes with gcc 9.3.0.  Both of these are far beyond the version used in the report, and changes in either one may have affected the original issue.

I hope that you are still using V, and enjoying working with it.
