### ISSUE TITLE
string type to f32 bug

### ISSUE THREAD

**Issue by sh0f** [vlang/v#2542]
```
>>> d := '7633.18'.f32()
>>> println(d)
7633.180176
>>> g := '7633.18'.f64()
>>> println(g)
7633.180000
```

**Comment by LorenzoPirro** [comment]
I think that it isn't a bug. F64 conv. is correct because the C compiler considers the 6 max digits in the float part (and so 180000) until they are completed. In fact F64 uses 16 bytes, and until to 10 digits in the integer part, the result will be xxx...,180000. The same is valid for F32. In fact if you write 33.18, the result will be 33.180000. If you add digits in the integer part, the C compiler will approximate the result.
