### ISSUE TITLE
vlib/ui do not consider separating out?

### ISSUE THREAD

**Issue by zeromake** [vlang/v#2549]
[vlang](https://github.com/vlang/v/blob/master/LICENSE) is MIT

[vlib/ui](https://github.com/vlang/v/blob/master/vlib/ui/LICENSE) is GPLv3

install valng carries `vlib/ui` by default but `vlang` is MIT, `vlib/ui` is GPLv3.

I think it should be installed separately by the user.

**Comment by topcheese** [comment]
I'm no expert here, but in addition shouldn't the UI lib at least be LGPL?  I was really thinking about this project until I found this.  I now understand the efforts to use UI's with more permissive licenses.
  I think it also needs to be spelled out on the website because it seems a little misleading.

**Comment by medvednikov** [comment]
https://github.com/vlang/v/issues/1492

**Comment by topcheese** [comment]
I'm pretty sure that the only license that will allow you to mix the two is the LGPLv2, otherwise you force people to adopt the GPL license.  Sure you can provide  commercial licenses and linking exceptions, but from my understanding LGPL is the most compatible with the MIT type licensing.
 The Red language has a BSD type license and provides a gui in the core.

  I believe some of your servers and services should/could be GPL, but the UI really should be a little bit more permissive.  You definitely want to start with a copyleft license, and go with a more permissive license later if need be.

**Comment by gslicer** [comment]
I would like to see V including its standard Libs to be avaiable with the same free lincence (preferably MIT or BSD-like) and its development should be based entirely on the community - for monetizing I would prefer @medvednikov to start a company to offer a commercial membership for professional services & support

If vlib/ui will be somehow restricted. users will find ways to use another UI frameworks with V - just my 2c
