### ISSUE TITLE
How to use a shadowed variable?

### ISSUE THREAD

**Issue by metaprem** [vlang/v#265]
If V does not allow variables outside function, program 1 should have compiler error.

Assuming program 1 is valid:

Program 1 : How to use a module level variable when function has var with same name?
Program 2 : How to use a const name when function has var with same name?

**Program 1**
```
AGE := 40
fn main() {
	Age := 20
	AGE := 30
	println('Age=$Age')
	println('AGE=$AGE')
}
```
Program 1 output:
```
Age=20
AGE=30
Program exited.
```

**Program 2**
```
const (
	AGE = 40
)

fn main() {
	Age := 20
	AGE := 30
	println('Age=$Age')
	println('AGE=$AGE')
}
```
Program 2 output:
```
Age=20
AGE=30
Program exited.
```

**Comment by medvednikov** [comment]
Shadowing is not allowed, but consts are not checked right now. This is a bug, will fix.

This will not compile:

```
fn main() {
a := 0
if true {
  a := 1
}
println(a)
}
```

**Comment by lutherwenxu** [comment]
Related: #260

**Comment by M4SSD35TRUCT10N** [comment]
Program 2 is no longer possible due to new checks from the compiler.
a) it warns that variables have to be snake_case and mustn't contain capitalized letters
b) only consts seem to be alowed in uppercase

With these two points and changing the code to this:
```
const (
	AGE = 40
)

fn main() {
	age := 20
	// AGE := 30 // it#s not allowed anymore
	println('Age=$age')
	println('AGE=$AGE')
}
```
Output:
Age=20
AGE=40

But now the next thing - here const age is ignored:
```
const (
	age = 40
)

fn main() {
	age := 20
	println('Age=$age')
}
```
Output: Age=20

**IMHO** this should not compile or at least drop a warning. I'm in favor of not to compile because a globally defined const would be rendered useless, when it can be shadowed within a function.
