### ISSUE TITLE
Fix Makefile

### ISSUE THREAD

**Issue by mrLSD** [vlang/v#2744]
**V version:** Latest
**OS:** Ubuntu 16.04

**What did you do?**
make

**What did you expect to see?**
builded V
 
**What did you see instead?**
```
v$ make
rm -rf vc/
git clone --depth 1 --quiet https://github.com/vlang/vc
#cp fns.h vc/fns.h
rm -rf /var/tmp/tcc/
git clone --depth 1 --quiet https://github.com/vlang/tccbin /var/tmp/tcc
fatal: Access denied
```

## The problem is:
```
all: fresh_vc fresh_tcc
```

And:
```
fresh_tcc:
...	rm -rf /var/tmp/tcc/
	git clone --depth 1 --quiet https://github.com/vlang/tccbin /var/tmp/tcc
```
But should be:
```
fresh_tcc:
...	rm -rf /var/tmp/tcc/
	git clone --depth 1 --quiet https://github.com/vlang/tccbin /tmp/tcc
```
You shouldn't use `/ver/tmp/tcc`.

*Moreover* `fresh_tcc` redundant. It's not used:
```
CC ?= cc
...
$(CC) -std=gnu11 -w -o v vc/v.c $(LDFLAGS) -lm
```

**Comment by spytheman** [comment]
tcc should be compiled for its final location since it hard codes the path to it inside the tcc binary.

Installing tcc inside /tmp/tcc instead of inside /var/tmp/tcc is not better, since on some distros /tmp is:
 a) mounted on ramfs or tmpfs (essentially in RAM), so it evaporates after a reboot
 b) mounted with noexec option, so you can not execute binaries stored there.

fresh_tcc (i.e. installing a recent tcc binary in a known location) is not used for building v itself (which is done by the `$(CC) -std=gnu11 -w -o v vc/v.c $(LDFLAGS) -lm` line, but is used when passing -fast to v on linux.

Also, on stock Ubuntu 16.04, /var/tmp is guaranteed to be writable to your user, and to not be purged after a reboot. If you do not have permission to write to it, your distro most probably has been modified by a hardening program like AppArmor or SELinux. 

Please use their documentation to allow writing to /var/tmp/tcc for your user.

**Comment by mrLSD** [comment]
You suggest install to `/var/tmp`?
It's not Linux way.
And `/var/tmp/tcc` will not in search path by default.

Additinonaly:
`$(LDFLAGS)` not set by defaults.
`--fast` same story.

And you should understand that `fresh_tcc` will execute everytime for `all` target. So it dosen't make sance to put into `/var/tmp/tcc` because it'll always rewrite.

**Comment by medvednikov** [comment]
The way tcc setup works right now, it needs a known absolute path. Right now `/var/tmp/tcc` is hardcoded.

This will be fixed of course, most likely by fixing tcc itself.

**Comment by spytheman** [comment]
@mrLSD I do not suggest anything, except to make your /var/tmp folder writable, so that v can clone the tccbin repo there.

I was explaining you the reasons behind the current state of the Makefile. 

V is fast moving, and at the time the downloaded custom build tcc also needed changes to accommodate more distributions. 

Now that it seems to have stabilized (have not seen changes in a month), the `fresh_tcc` rule may be changed to one that will not re-download it every time.

**Comment by medvednikov** [comment]
> Moreover fresh_tcc redundant. It's not used:

It's used internally, due to a bug in tcc, I have to use a hardcoded path like /var/tmp/tcc.

**Comment by medvednikov** [comment]
`tcc` is no longer used by default on Linux.

**Comment by mrLSD** [comment]
@medvednikov 
current Make file:
```
ifdef LINUX
	rm -rf /var/tmp/tcc/
	git clone --depth 1 --quiet https://github.com/vlang/tccbin /var/tmp/tcc
endif
```
