### ISSUE TITLE
Enum method in same module does not compile

### ISSUE THREAD

**Issue by elbow-jason** [vlang/v#2785]
**V version: V 0.1.22 1dadf9d** 
**OS: Darwin - macOS Mojave 10.14.6 (18G95)** 

**What did you do?**

I defined an `enum Feeling` then added a method `to_byte`.

**What did you expect to see?**

I expected the method `to_byte` to be on the `Feeling` enum and be usable.

**What did you see instead?**

I got a compiler error:
```
enum_method_not_working.v:22:16: type `Feeling` has no field or method `to_byte`
   20| 
   21| fn encode_feeling(f Feeling) []byte {
   22|  b :=  f.to_byte()
                        ^
   23|  return [b]
   24| }
```

Code:
```vlang

enum Feeling {
	happy
	sad
	nothing
}

pub fn (f Feeling) to_byte() byte {
	return match f {
		.happy { 0 }
		.sad { 1 }
		.nothing { 2 }
		else {
			// appease the compiler with an int cast here
			int(panic("invalid Feeling variant $f"))
		}
	}
}

fn encode_feeling(f Feeling) []byte {
	b :=  f.to_byte()
	return [b]
}

```

**Comment by Rhymond** [comment]
I believe it's the same: https://github.com/vlang/v/issues/2115

**Comment by Ivo-Balbaert** [comment]
After removing some errors in the code (pub in front of to_byte, else not necessary because match is exhaustive, superfluous }) the following code compiles and produces correct output (Windows 10 and Ubuntu 20 - V 0.1.27 33a9822):

enum Feeling {
	happy
	sad
	nothing
}

fn (f Feeling) to_byte() byte {
	return match f {
		.happy { 0 }
		.sad { 1 }
		.nothing { 2 }
	}
}

fn encode_feeling(f Feeling) byte {
	b :=  f.to_byte()
	return b
}

fn main() {
	f1 := Feeling.sad
	println(int(f1.to_byte()))       // 1
	println(int(encode_feeling(f1))) // 1
}

So an enum can have a method in the same module.
