### ISSUE TITLE
Linux debian repository

### ISSUE THREAD

**Issue by hegnuzalto** [vlang/v#2822]
It could be really cool and helpfull if you add V lang to the linux debian and arch repository because in some situations installing it could be really  better and updating it.

And other think maybe official Matrix channel?

**Comment by donnisnoni95** [comment]
Related -> https://github.com/vlang/v/issues/2797

**Comment by medvednikov** [comment]
I think this should be done after the 0.2 release later this month.

**Comment by jonathonf** [comment]
> arch repository

It's already in the AUR as [`vlang`](https://aur.archlinux.org/packages/vlang/) and [`vlang-git`](https://aur.archlinux.org/packages/vlang-git/).

**Comment by KeyWeeUsr** [comment]
+1 for the [Matrix](https://matrix.org/) room.

@medvednikov you can take advantage of [Discord bridge bot](https://t2bot.io/discord/) and connect already existing Discord rooms with new Matrix rooms. Since Matrix is FOSS and some people don't like Discord I think it's quite a good trade off instead of having 2 separate/not connected messaging channels which might eventually happen.
