### ISSUE TITLE
Testing doesn't work like documentation

### ISSUE THREAD

**Issue by Kamori** [vlang/v#3066]
**V version:** 
```
[kamori@kamori-pc helloworld]$ v version
V 0.1.23 28f76f1
```
**OS:** 
```
[kamori@kamori-pc helloworld]$ cat /etc/manjaro-release 
Manjaro Linux
[kamori@kamori-pc helloworld]$ uname -a
Linux kamori-pc 4.19.59-rt23-MANJARO #1 SMP PREEMPT RT Sat Jul 20 07:14:03 UTC 2019 x86_64 GNU/Linux
```

**What did you do?**
Ran the testing docs
https://vlang.io/docs#testing

```
// hello.v
fn hello() string {
	return 'Hello world'
}

// Adding main func because its required for a run
fn main() {
    println(hello())
}
```

```
// hello_test.v
fn test_hello() {
    assert hello() == 'Hello world'
}
```

**What did you expect to see?**
A successful test run

 
**What did you see instead?**
```
[kamori@kamori-pc helloworld]$ v test hello_test.v
Testing...
    85 ms | hello_test.v FAIL
`/opt/organized_opt/github/kamori/GoatTools/commands/helloworld/hello_test.v`
 (
hello_test.v:2:16: undefined: `hello`
    1| fn test_hello() {
    2|     assert hello() == 'Hello world'
                      ^
)
----------------------------------------------------------------------------
    85 ms | <=== total time spent running V _test.v files 
 ok, fail, total =     0,     1,     1```

**Comment by nedpals** [comment]
Have you tried assigning the value of `hello()` into a variable and use that to `assert`?

**Comment by Kamori** [comment]
I haven't, but I would assume that assigning a variable would return an undefined as well since the test file can't find the reference?

**Comment by nedpals** [comment]
You should import first the module `hello` at the top of the file and test it again using `v -user_mod_path $PWD/../ test hello_test.v`

**Comment by Kamori** [comment]
No success here. Even made use of the `pub` keyword.


```
// hello.v

module hello

pub fn hello() string {
	return 'Hello world'
}


fn main() {
    println(hello())
}
```


```
// hello_test.v
import hello

fn test_hello() {
    hello_func := hello()
    assert hello_func == 'Hello world'
}
```

Command (note: they're in the same dir)
```
[kamori@kamori-pc helloworld]$ v -user_mod_path $PWD test .
Testing...
    39 ms | hello_test.v FAIL
`/opt/organized_opt/github/kamori/GoatTools/commands/helloworld/hello_test.v`
 (
hello_test.v:1:11: cannot import module "hello" (not found)
    1| import hello
                 ^
    2| 
    3| fn test_hello() {
)
----------------------------------------------------------------------------
    39 ms | <=== total time spent running V _test.v files 
 ok, fail, total =     0,     1,     1
```

**Comment by zhylmzr** [comment]
Move the `hello.v` and `hello_test.v` to the `hello` sub directory, and then run `v -user_mod_path $PWD test` in parent directory.

The module name must be same as sub directory.

**Comment by Kamori** [comment]
No change

```
[kamori@kamori-pc hello]$ v -user_mod_path $PWD test hello_test.v
Testing...
    32 ms | hello_test.v FAIL
`/opt/organized_opt/github/kamori/GoatTools/commands/hello/hello_test.v`
 (
hello_test.v:1:11: cannot import module "hello" (not found)
    1| import hello
                 ^
    2| 
    3| fn test_hello() {
)
----------------------------------------------------------------------------
    32 ms | <=== total time spent running V _test.v files 
 ok, fail, total =     0,     1,     1
```

**Comment by medvednikov** [comment]
@Kamori for now in most cases you have to `import module` in the module_test.v file.

This will be fixed soon, as indeed it's different from the instructions in the docs.

**Comment by Kamori** [comment]
This seems reasonable to me. Still seems odd my latest example doesn't work. But I'll have to dig in more to see how to make a module, maybe I'm doing something else wrong.

**Comment by improveourselves** [comment]
@Kamori Hi. I had the same issue, and no suggestion I could find worked. I even built the module. Finally, I moved my test program called moduletest.v to the modules folder I created called mymodules, where I made myfirstmodule. So, within my mymodules folder, I have moduletest.v, the directory myfirstmodule wherein I made myfirstmodule.v, and finally the built module called myfirstmodule.vh. Now, with those three files in the same folder, I typed "v run moduletest.v", and got the correct response as in the manual, "hello from my first module!". 
So, for now, the lesson is we must place our modules we wish to import, in the same directory as the program. @medvednikov Am I doing this properly, or is there some better way now?

**Comment by spytheman** [comment]
@improveourselves , @Kamori A test file name should end with _test.v .
If you name your moduletest.v file `myfirstmodule/myfirstmodule_test.v` , then it should work.

Inside the file, you can have `module myfirstmodule` which will make all module functions (even the private ones) available to you without prefixes (just like if the test was a part of the module itself).

If you do not put `module myfirstmodule` at the top of the file, you have to do `import myfirstmodule` instead at the start of `myfirstmodule/myfirstmodule_test.v` . In this case, the test code will not have access to the internals of the module, and you can only test the public API of the module, just like in code that uses the module, by prefixing with `myfirstmodule.function()` .

**Comment by improveourselves** [comment]
@spytheman Why does a test file need _test.v afterwards? Does V interpret files with that ending and execute them differently? 
I'm unclear on which file is named which now. I tried what I thought you said, and it didn't work. Okay, so let's make the filenames clear by word-numbering them. 
Let's call the module itself modone. That is supposed to be the name of the module, and is to be the name of a directory, that has a file within it named modone.v, is that correct? 
So, proceeding, at the top of modone.v I am to put "module modone", right? 
Then, proceed per documentation, which says to write the code under the "module modone" and that code is the "pub fn sayhi()" function, correct? 
Next, I "cd .." outside the folder, and then type "v build module ./modone/modone.v", right? And that should build the module correctly? 
Lastly, while still outside the modone folder, I create a file which we'll call modcalltwo_test.v, so that you have the "test" in there like you asked me to do (again, why is that necessary?). The code in the modcalltwo_test.v file should be simply per the documentation, having as its code 
"module main
import modone
fn main() { 
sayhi()
}"
Is that correct? Notice, I'm omitting the prefixing like you said I should now be able to do. 
And finally, I save and then run the modcalltwo_test.v by typing, 
"v run modcalltwo_test.v", right? 
Ok, so is the above right, for me to write and test? If not, please correct me. Thanks.

**Comment by improveourselves** [comment]
FYI, I was going through the README.md file seqentially to learn. Today I scrolled down further, and see a section which discusses Test. I'm still not sure why it's needed, as why not simply write a function and see if the code compiles and runs as expected. Still, I'd love it if you could explain to me why "test" is even done at all (I'm not a computer science major, obviously), and how to do modules properly, as asked above. Thanks.

**Comment by spytheman** [comment]
@improveourselves 
See: https://github.com/vlang/v/blob/master/doc/docs.md
Also: https://vlang.io/docs#testing

> Why does a test file need _test.v afterwards? Does V interpret files with that ending and execute them differently?

Yes. Files ending with _test.v are skipped when a module is imported. They have to be executed by either explicitly doing `v file_test.v` or by `v test` . In this way the code in them do not burden the users of a module. These _test.v files contain functions named `test_xxxx` . These functions are automagically called by the V's builtin testing framework, which also collects stats about how many assertions have passed, whether the a given test_ function failed/passed, timing info and so on.
This information is shown when you pass `-stats` to the compiler.

> That is supposed to be the name of the module, and is to be the name of a directory, that has a file within it named modone.v, is that correct?

In v, all .v files in a module folder are part of the *same* module, whatever their filename is (it has to end in `.v`, but otherwise you can name them however you like, for example by topic of what functionality they contain).

You do not have to name a file like the folder itself (although many prefer to do it). You can have many files in the same module, and they will be compiled as if they are part of the same module - all functions inside the module are callable by all other functions in the same module without prefixing, even the ones that are not public.

> So, proceeding, at the top of modone.v I am to put "module modone", right?
Correct - .v files inside a module/folder named `modone`, should have `module modone` at their top.

> Next, I "cd .." outside the folder, and then type "v build module ./modone/modone.v", right? And that should build the module correctly?

That is not right. `v build module ` is reserved for building .o files (which you then can use for linking with other languages), which is a very specialized thing, and is buggy right now.

If you just want to simply use a v module, you do not need to do `v build module` as a separate step. You just write your code in the parent folder, and in it you do `import modone`, just like you would import a module like `net`, `math`, or `os`. The *only difference* between them, and your own brand new `moduleone`, is that they are in v's vlib, which v always knows where to find, while your module is in your folder, so v will find it only if your code that imports your module is one level up, or if you have moved/installed your module to `~/.vmodules/` .

So you just do `import modone` in your modcalltwo_test.v, add your test_ functions, then you do: `v modcalltwo_test.v` . 

V will see from the extension _test.v that this is a test file, will collect all test_ functions in it, and will run them, then V will present you with the results (pass `-stats` to see more details).

NB: v run file.v is needed for ordinary files (it saves you having to do 2 commands, i.e. compile the file, then run it manually). For _test.v files, run is not needed, since v presumes, that you want to run the test file. If you add `run` too, nothing bad will happen, only the tests will be run twice.

**Comment by spytheman** [comment]
NB: if you want your test to have access to the internals of your module (just like other files in the same module), the `_test.v` suffixed file should be placed inside the module folder, and should have `module modone` just like the other .v files there. Otherwise your `_test.v` file should import your module, like an ordinary v program, and will NOT have access to stuff that is not declared with `pub` in your module.

**Comment by spytheman** [comment]
NB: Another special thing, that V does for convenience with `_test.v` files, is that `_test.v` files, that are located *inside* the module folder `modone`, can simply do `import modone`.

**Comment by spytheman** [comment]
All in all => the easiest way to write tests for your module is to write one or several xx_test.v files inside the module folder. Then you can run your tests with `v test path/to/your/module/folder` (which can be shortened to just `v test .`, if your pwd is in the module folder).

**Comment by spytheman** [comment]
> I'm still not sure why it's needed, as why not simply write a function and see if the code compiles and runs as expected.

You can do that too if you want.
The test infrastructure is built to ease that process - it just provides a way to run such functions, and to produce results in an easy to understand/look at way. In order to do that, it just needs you to follow some conventions, like name your test files with a `_test.v` suffix, and your test functions should start with `test_` prefix.

**Comment by spytheman** [comment]
> I'd love it if you could explain to me why "test" is even done at all
Testing in general is done, so that you can have assurance that your program/code/modules work as you expect them to, and which is more importantly - that they continue to do so, even after you make changes to your code.

**Comment by spytheman** [comment]
If the question is why there is a need for `v test .` , when `v file_test.v` seemingly does the same thing, the answer is that `v test .` can run several test suites, while `v file_test.v` is limited to one single test file. `v test a b c` scans the passed arguments/paths recursively for xxx_test.v files, and executes each of them in order, then presents you with a summary for all of them.

**Comment by spytheman** [comment]
```shell
0[19:25:20] /v/nv LINUX $ ./v test
Usage:
   A)
      v test folder/ : run all v tests in the given folder.
      v -stats test folder/ : the same, but print more stats.
   B)
      v test file_test.v : run test functions in a given test file.
      v -stats test file_test.v : as above, but with more stats.
   NB: you can also give many and mixed folder/ file_test.v arguments after test.

0[19:25:22] /v/nv LINUX $
```

**Comment by spytheman** [comment]
```shell
0[19:26:21] /v/nv LINUX $ ./v test vlib/math/ vlib/net
-------------------------------------- Testing... ------------------------------------
OK   108 ms [ 1/11] vlib/math/math_test.v
OK   193 ms [ 2/11] vlib/math/stats/stats_test.v
OK   180 ms [ 3/11] vlib/math/factorial/factorial_test.v
OK    67 ms [ 5/11] vlib/math/fractions/fraction_test.v
OK    69 ms [ 6/11] vlib/net/urllib/urllib_test.v
OK   242 ms [ 4/11] vlib/math/complex/complex_test.v
OK   112 ms [ 7/11] vlib/net/socket_udp_test.v
OK   215 ms [ 8/11] vlib/net/http/http_test.v
OK   253 ms [ 9/11] vlib/net/http/http_httpbin_test.v
OK   133 ms [10/11] vlib/net/ftp/ftp_test.v
OK    83 ms [11/11] vlib/net/socket_test.v
--------------------------------------------------------------------------------------
     874 ms <=== total time spent running V _test.v files
                 ok, fail, total =    11,     0,    11
0[19:26:26] /v/nv LINUX $
```

**Comment by spytheman** [comment]
One last thing: the `main` module right now, is treated in a special way, which prevents testing it easily. That restriction will be removed very soon. For now, you can easily test only stuff in modules != main.

**Comment by improveourselves** [comment]
@spytheman  My extreme gratitude to you for the very thorough answers! It will take me a few days to go through all the details and complete everything related, to competency. It's so wonderful to feel that someone cares enough to take time to explain what things actually mean! Most advanced coders I've talked with assume that you have a base knowledge level and so throw about so many words that have special meanings in computer programming so people who aren't proficient hear these words and we don't know the special meaning so we get lost and the rest is smudged by our not understanding an early part. So, I again extend my preliminary and high gratitude to you for being so kind as to take time to explain what these terms actually mean. Assert and test, as examples, are now clear to me, where before I just felt stupid. Thank you for helping me feel competent again. :) I'll go through the above, and reply if I have further questions. Thanks again Delyan! -John
