### ISSUE TITLE
Can't use `i` inside of `.map()`

### ISSUE THREAD

**Issue by zeddidragon** [vlang/v#3110]
**V version:** ❯ V 0.1.23 0fb0c43
**OS:** macOS High Sierra 10.13.6

**What did you do?**
```
fn main() {
  arr := [5, 5, 5]
  i := 3
  arr2 := [].map(i)
  println(arr2)
}
```

**What did you expect to see?**
`[3, 3, 3]`

**What did you see instead?**
`[0, 1, 2]`

I discovered this while trying to do map inside of a loop. At first I thought "oh, that's useful, there's a magic variables called `i` just like `it` inside of the map closure", but then I tried using that:

```
fn main() {
  arr := [5, 5, 5]
  arr2 := [].map(i)
  println(arr2)
}
```

And was met with an error:
```
❯ v run test.v
test.v:2:25: undefined: `i`
    1| fn main() {
    2|   arr2 := [5, 5, 5].map(i)
                               ^
```

I don't mind `i` being shadowed, but if it is you should allow me to use it.

**Comment by Ivo-Balbaert** [comment]
The above code when compiling now (v 0.1.27) gives the error:

test2.v:5:11: error: array_init: no type specified (maybe: `[]Type{}` instead of `[]`) 
    3 |     println(arr)
    4 |   i := 3
    5 |   arr2 := [].map(i)
      |           ^

This is expected because an expression like [].map(i) is not defined in V.  An empty array should always define its type. This code works:

fn main() {
  arr := [5, 5, 5]
  it := 3
  array := []int{}
  arr2 := array.map(it)
  println(arr2) // => []
}
