### ISSUE TITLE
trim_space() doesn't work when reading files from /sys

### ISSUE THREAD

**Issue by illiliti** [vlang/v#3149]
**V version: V 0.1.23 1679457** 
**OS: Void linux(glibc)** 

**What did you do?**
```v
module main

import os

fn main() {
        status := os.read_file("/sys/class/power_supply/BAT0/status")?
        print(status.trim_space())
}
```

**What did you expect to see?**
Newline trimmed
```
00000000  44 69 73 63 68 61 72 67  69 6e 67                 |Discharging|
0000000b
``` 

**What did you see instead?**
Newline still persist
```
00000000  44 69 73 63 68 61 72 67  69 6e 67 0a              |Discharging.|
0000000c
```

**Comment by alexesprit** [comment]
This happens because of lots of trailing `\0` in this file. When I tested the example on Linux, file size was 4096 bytes, whereas the actual string size was 5 (it was `Full\n` for me).

This is how the actual file looks like:
```
Offset(h) 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000  44 69 73 63 68 61 72 67 69 6E 67 0A 00 00 00 00  Discharging.....
00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00000020  ...
```

This could be fixed by removing `fsize` parameter in string constructor:
```v
// read_file reads the file in `path` and returns the contents.
pub fn read_file(path string) ?string {
	...
	return string(str)
}
```
but I'm not sure if this is a correct fix.

**Comment by serkonda7** [comment]
For me `fread` fails, so i cannot even read the file content.

**Comment by danieldaeschle** [comment]
Anyone can reproduce this? Otherwise please close it.

**Comment by illiliti** [comment]
Can't reproduce anymore. Closing
