### ISSUE TITLE
Tail-recursive optimization [Feature request]

### ISSUE THREAD

**Issue by juliancoffee** [vlang/v#317]
I think tail-recursion optimization will be nice. That's mean if call function is last step in function it can be translated to loop on preprocessing step, for example.

```
fn fac (n int, accum int) int {
  if n == 1
      return accum
  else
     return fac (n - 1, accum*n)
}
```

while n - 1 and accum*n called before function call, compiler can translate it to simple iterative loop
```
fn fac (n int, accum int) int {
  while n != 1
    n -= 1
    accum *= n
  return accum
}
```

So people can write in functional way, but argument's stack cannot be overflow

**Comment by zac-garby** [comment]
This would be great, a lot of functions are more naturally written recursively.

**Comment by sgioia9** [comment]
Tthe compiler shouldn't translate the code to a recursive loop (I'm not sure if it would actually be possible generally), but rather, avoid allocating extra stack frames.

**Comment by ChillPC** [comment]
Just an idea for this proposition. Would it be possible to have a special keyword for tail recursion? So users will immediately see that a function is  tail recursive and it can raise error at compile time if the return statement is not well written. Maybe just `tail`.

```v
fn fac (n int, accum int) int {
  if n == 1
      return accum
  else
     tail fac (n - 1, accum*n)
}
```

**Comment by pavi2410** [comment]
@ChillPC It could be done like Kotlin's `tailrec fun`
```v
tailrec fn fac (n int, accum int) int {
  if n == 1 {
      return accum
  } else {
     return fac(n - 1, accum * n)
  }
}
```

**Comment by medvednikov** [comment]
This is already done with `v -prod`

**Comment by pavi2410** [comment]
Through the C compiler?

**Comment by medvednikov** [comment]
Yes.

**Comment by ka-weihe** [comment]
Have a look at:
https://godbolt.org/z/cEPT6r

**Comment by juliancoffee** [comment]
> Have a look at:
> https://godbolt.org/z/EWsWKP
> 
> ... no call instructions, just a simple loop.

yes, LLVM and GCC have some support for such optimization, but as far I know they are not guaranteed.

**Comment by MarcTCruz** [comment]
> > Have a look at:
> > https://godbolt.org/z/EWsWKP
> > ... no call instructions, just a simple loop.
> 
> yes, LLVM and GCC have some support for such optimization, but as far I know they are not guaranteed.

If GCC and LLVM doesn't have support for all the cases, it's probably because it's not easy/worth to implement it, but according to SO most tasks will be optmized.
[](https://stackoverflow.com/questions/34125/which-if-any-c-compilers-do-tail-recursion-optimization
)
Think about the logic to do following task, translate fibonnaci to loop:
```
fn fibbonacci(int n) int {
	if n < 2 {
		return n
	}
	return (fibbonacci(n - 1) + fibbonacci(n - 2))
}
```

I'll not post the loop version so you can freely think about how to make it in simple steps.

Also, IMO the loop version of fibbonacci is much easier to undestand/read since you can just write it in order, but you need to abstract to nodes in recursive fibbonacci to get it.

Also, recursive and loop factorial have almost no difference, so writing the loop version is fine.

The suggestion is nice, but already nicely implemented through compilers, this feature should be closed.

**Comment by JalonSolov** [comment]
It is an optimization that should be done (along with quite a few more) for the `x64` backend, but that is a long, long way away.
