### ISSUE TITLE
Error compiling overload assignment/print

### ISSUE THREAD

**Issue by codingconcepts** [vlang/v#3223]
**V version:** V playground
**OS:** V playground

**What did you do?**
```v
struct Vec {
	x int
}

fn (a Vec) + (b Vec) int {
	return a.x + b.x
}

fn main() {
	a := Vec{1}
	b := Vec{2}

	c := a + b
	println(c)
}
```

**What did you expect to see?**
```
{
	x: 3
}
```

**What did you see instead?**
You just found a bug. V should either compile this program or return an error.

Interestingly the following does work with a slight modification to the code that errors:

```v
struct Vec {
	x int
}

fn (a Vec) + (b Vec) int {
	return a.x + b.x
}

fn main() {
	a := Vec{1}
	b := Vec{2}
	println(a + b)
}
```

**Comment by Ivo-Balbaert** [comment]
I think the problem here is that this version is not overloading:
fn (a Vec) + (b Vec) int {
	return a.x + b.x
}
It doesn't return a Vec.

If you change the + overloading to:

fn (a Vec) + (b Vec) Vec {
	return Vec{a.x + b.x}
}

then the output is what you expected to see.

The fact that the code you give returns an error is strange, it should just print 3.
The C error it returns however shows that it expects the + overloading to return a Vec:

C:\Users\CVO\AppData\Local\Temp\v\test.tmp.c: In function 'wmain':
C:\Users\CVO\AppData\Local\Temp\v\test.tmp.c:9811:9: error: invalid initializer
 Vec c = Vec__plus(a, b);
         ^~~~~~~~~

The docs don't state that.

**Comment by spaceface777** [comment]
Both code snippets compile and run successfully with the latest V (0.1.29 99e607d at the time of writing)
