### ISSUE TITLE
Doc bug suggesting that variable names may contain spaces

### ISSUE THREAD

**Issue by kpeters58** [vlang/v#3225]
https://vlang.io/docs:

 If you need more complex expressions, use ${}: 'can register = ${user.age > 13}'. 

The underscore between 'can' & 'register' is missing - giving the wrong impression that variable names may contain spaces.

**Comment by nedpals** [comment]
Issue moved to [vlang/website](https://github.com/vlang/website).

**Comment by nedpals** [comment]
>If you need more complex expressions, use ${}: `'can register = ${user.age > 13}'`.

I haven't seen any problems at all since it just demonstrates the use of the `${}` inside a string hence you don't see an underscore between `can` and `register`. It's more like this:
```v
println('can register = ${user.age > 13}')
```
Move your issue to [vlang/website](https://github.com/vlang/website) as it is all about formatting on the docs and the website.
