### ISSUE TITLE
Rename functions like `mkdir` and `rm`

### ISSUE THREAD

**Issue by r00ster91** [vlang/v#3332]
I think these and other similar functions should be renamed to something more general that isn't so Linux-specific because V is a language for all operating systems, not just Linux. I think we should be equally welcoming to all operating systems. Naming the functions after a specific platform's terminology isn't very friendly for other platforms and might also be confusing for non-Linux users.

**Comment by dhonx** [comment]
I don't think this name is Linux specific name, but it is indeed a suitable name. short and clear.

**Comment by spytheman** [comment]
rm and rmdir are not Linux specific at all. They are present on every Unix-y platform except may be Windows, and even there you can use for example msys2 or https://docs.microsoft.com/en-us/windows/wsl/install-win10 and you will have them available.

**Comment by spytheman** [comment]
See for example https://www.unix.com/man-page/posix/1p/mkdir/ and https://www.unix.com/man-page/posix/1p/rm/ .

**Comment by vitalyster** [comment]
Agreed, vlib functions should follow standard V naming conventions (make_directory, remove, etc.)

**Comment by Delta456** [comment]
@vitalyster the name for functions are fine imo and just as @spytheman says that they are present on every Unix Platform expect Windows and also can be easily understood.

**Comment by vitalyster** [comment]
Sure, `os.list_directory` will match vlib naming conventions.
The issue is not only in `os` module but in other modules like `pg` and `mysql` where names just match their C counterparts. For example, that is one of most criticized part of PHP standard library, V standard library should be better :)

**Comment by spytheman** [comment]
There should be a balance between shortness, clear naming, and familiarity.

I also think that os.ls, os.mkdir and os.ls achieve that balance. 
Others may not think so. Such is life  ¯\_(ツ)_/¯ .

Claiming that they are biased towards Linux is wrong. 
The correct bias that is at play here is from Windows users, that are not accustomed to short names (probably because CLI interfaces are not very welcomed on that platform) in my opinion, is it not?

(See https://docs.microsoft.com/en-us/windows/win32/api/sddl/nf-sddl-convertsecuritydescriptortostringsecuritydescriptora and http://ashutoshmehra.net/blog/2010/02/long-function-names/ for examples...)

Should os.ls be renamed to os.list_directory, and os.rm to os.remove? 

I do not know. I personally do not like it.
It would affect vsh's ability to be short and terse like a shell script is. 

At this point, why even bother with vsh?

> For example, that is the one of most criticized part of PHP standard library, V standard library should be better :)
The criticism was mostly about inconsistent parameter position/naming, and not about the function names themselves, no? The vast builtin php standart library, has certainly played a huge part in PHP's success... The easy ability to upload scripts to practically any host, and VERY easy and high quality documentation of the said standart library, have also played a very big role.

Keep in mind also this aphorism:
"There are only two kinds of languages: the ones people complain about and the ones nobody uses."
I would like v to be a language that is used, and that people complain about. They already complain, so I hope v is on the right track ;-) .

@medvednikov what do you think?

**Comment by runeimp** [comment]
I could be wrong but I doubt V can even compile to any operating system that doesn't follow the POSIX standard, with the sole exception being Windows. That should make the current `os` method names the more inclusive standard. Windows isn't even command line compatible with itself as Command Prompt and PowerShell have different command sets from each other. But all of the UNIX subsystems for Windows all followed the POSIX standard. Now I'm not entirely against neutral method names. But that's yet another thing to learn for anyone who is not a Windows only developer.

**Comment by spytheman** [comment]
@runeimp it had (still have?) support for haiku, which I think is not POSIX, but I may be wrong.

**Comment by medvednikov** [comment]
These names are pretty much a standard now:

https://golang.org/pkg/os/#Mkdir
https://golang.org/pkg/os/#File.Chdir
https://golang.org/pkg/os/#File.Chmod

I'd rather use that than come up with something new. `make_dir`? `make_directory`?

Then VSH becomes pointless, since its goal is to be a simple alternative to bash.

**Comment by medvednikov** [comment]
And many Windows developers use Linux on the servers, I think a vast majority of developers knows what `mkdir` or `ls` do :)

**Comment by vitalyster** [comment]
@medvednikov golang standard library have consistent naming, the problem not in short names but part V `os` module have "long names" (is_executable) and another part is "familiar"

**Comment by medvednikov** [comment]
It's `os.mkdir` in Python as well.

**Comment by spytheman** [comment]
what is a suitable long name for os.is_executable ?

**Comment by spytheman** [comment]
os.is_x?
os.x?

**Comment by vitalyster** [comment]
@spytheman if we will follow your "familiar" way then there should not be "high level" is_executable function, and every V developer should play with `access` bits just like in C.

**Comment by spytheman** [comment]
why?
os.ls for example does not have libc equivalent, but is short and easy to use ...

Anyway, bikeshedding function naming is fun, but working on actual code is more so.
Have a nice and productive day to all.

**Comment by vitalyster** [comment]
it is "short in easy" only for "linux biased" people, `os.is_x` short and easy too then

**Comment by spytheman** [comment]
There is no linux bias, that was my point, which I already made 2 times... It comes from unix/posix.

**Comment by runeimp** [comment]
@spytheman BeOS and Haiku both are POSIX compatible. Haiku more so than BeOS even, I believe.

**Comment by spytheman** [comment]
Like it or not, Windows is the special one about naming C functions. I do not like it, but I agree that we have to support it 100%. Following its idiotic decisions however about long function names is not something that we should follow in my opinion.

**Comment by spytheman** [comment]
@runeimp thanks, I did not know that.

**Comment by medvednikov** [comment]
It's `os.mkdir()` in Python and Go, some of the most popular languages. I don't see any point in coming up with a new name.
