### ISSUE TITLE
string_add has memory leak if it is assign to same variable

### ISSUE THREAD

**Issue by S-YOU** [vlang/v#3409]
Following case has memory leak on first allocation of 'something', memory allocation is happened on 'something' and 'other', only point to 'other' is kept, and old allocation to pointer to 'something' is lost.
```
a := 'something'
a += 'other'
```

but if you assign to different variable, 
```
b = a + 'other'
```

you could manual free 'a' and 'b', if you want.

I still have no idea to work around or fix this though.

**Comment by lutherwenxu** [comment]
You shouldn't be required to free a string manually.
The semi-auto memory-management system is not complete yet but if it's done it should free/reuse the old string.

**Comment by 0-8-15** [comment]
Looks like **every** use of `string_add` results in a memory leak. Or maybe not *every*, still *most*.  All of mine so far.

**Comment by purinnohito** [comment]
Because this sentence is machine translated, it may contain slang that would be considered rude by native English speakers, unintentionally strong statements or imperative expressions.

A similar problem occurs with string types assigned in the intra-functional scope.

Compilation options
`v -os cross -autofree -o leekStr.c leekStr.v`

V Source
```
fn main() {
    num_cnt := 11
    mut str_leek1 := '${num_cnt}'
    str_nonleek1 := '${num_cnt}'
    println(str_nonleek1)
    {
        mut str_leek2 := '${num_cnt}'
        str_leek1 = '${num_cnt}'
        println(str_leek1)
        println(str_leek2)
    }
    println(str_nonleek1)
    println(str_leek1)
    println(num_cnt + 10)
}
```

compile C
```
int wmain(int ___argc, wchar_t* ___argv[], wchar_t* ___envp[]){
	_vinit();
	int num_cnt = 11;
	string str_leek1 = _STR("%"PRId32"", 1, num_cnt);
	string str_nonleek1 = _STR("%"PRId32"", 1, num_cnt);
	println(str_nonleek1);
	{
		string str_leek2 = _STR("%"PRId32"", 1, num_cnt);
		str_leek1 = _STR("%"PRId32"", 1, num_cnt);
		println(str_leek1);
		println(str_leek2);
	}
	println(str_nonleek1);
	println(str_leek1);
	string _t69 = int_str(num_cnt + 10); println(_t69); string_free(&_t69); //MEM2 int
	;
	_vcleanup();
	string_free(&str_leek1); // autofreed var
	string_free(&str_nonleek1); // autofreed var

	return 0;
}
```
As far as I can think of as a way to deal with it.
1: Because of the nature of "strings cannot be rewritten except by total substitution" in V language, a flag indicating "whether the reference string is heap or stack" is added.
2-A: Explicitly move ownership, such as Rust, at copy time because 1 alone cannot deal with a heap variable allocated in a narrow scope region being assigned to a variable with a wider scope.
2-B: At compile time, the variable lifetime is counted by reference, and the disposal process is inserted in the scope where the count expires.

This could be something like this.


I really like the "converted to readable C" nature of the V language.
The only reason I've been able to call you on your suggestions for improving the language in this way is because I've noticed the anomalies because it's been converted to readable C.

Thank you.

Translated with www.DeepL.com/Translator (free version)

**Comment by medvednikov** [comment]
Fixed when compiled with -autofree.
