### ISSUE TITLE
After running "v symlink", vlib cannot be found

### ISSUE THREAD

**Issue by refacto** [vlang/v#3446]
**V version:** 25e7ceeef06a86f6fe3b056091ff4f4506034f46
**OS:** OpenBSD -current

**What did you do?**
After successfully compiling V and running `v symlink`, I tried executing v from another directory.

**What did you expect to see?**
Successful V building/execution.
 
**What did you see instead?**
This error message:
```
~/dev/vprogs > v run hello.v
vlib not found. It should be next to the V executable.
Go to https://vlang.io to install V.
(os.executable=v vlib_path=./vlib vexe_path=v
```

Here's a ktrace/kdump output: http://ix.io/27q1

**Comment by PibePlayer** [comment]
Does it work well if you use it without the symlink? 
Ex: `./../v/v run hello.v`?

**Comment by refacto** [comment]
Yes, it does. As a workaround, I've started using
```
VFLAGS=-vlib-path /home/azarus/dev/v/vlib
```

**Comment by spytheman** [comment]
try setting `VEXE=/abs/path/to/v` as a workaround

**Comment by spytheman** [comment]
The current implementation of `os.executable()` on OpenBSD just returns os.args[0] . We could not find a way to get the equivalent of linux's `/proc/self/exe` on that platform.

If someone that uses OpenBSD patch vlib/os/os.v (search for `pub fn executable`), so that os.executable() works and returns the absolute path of the current executable, no matter what the current working folder, or whether it was symlinked to another location and so on, it would work fine there too.
