### ISSUE TITLE
doesn't work on windows

### ISSUE THREAD

**Issue by HedariKun** [vlang/v#358]
trying to using it on windows but it doesn't work.
it can't find code/v directory thingy.
tried to put it in different places like my documents and the user folder but no help

**Comment by binkiklou** [comment]
The creator didn't know what a windows was

**Comment by HedariKun** [comment]
a big project made by one person tho,
ofc it would have lot of errors at first

**Comment by binkiklou** [comment]
He had plenty of time to fix it before release, also I'm starting to think the language doesn't work at all because it I don't think I have seen anyone being able to do anything with the language without getting errors. I have been myself making a programming language, and something is terribly wrong if you can get anyone to be able to use your language.

**Comment by notoriouskyoko** [comment]
it's just malware

**Comment by HedariKun** [comment]
how it is a malware if you we can't run anything with it ?

**Comment by lutherwenxu** [comment]
Currently, there's no native Windows support afaik. You can probably run it on WSL (Windows Subsystem for Linux) however.

**Comment by Bowero** [comment]
Please refer to #413.

**Comment by aurelVZ** [comment]
hello ,is there anyone who compiled V lang for windows , no mather which version
i am really interested

**Comment by lutherwenxu** [comment]
> hello ,is there anyone who compiled V lang for windows , no mather which version
> i am really interested

Please don't bump a dead thread.
Instruction on compiling V can be found here: <https://github.com/vlang/v#installing-v-from-source>
