### ISSUE TITLE
Variables declared within an `$if` block are not available outside of the block

### ISSUE THREAD

**Issue by prime31** [vlang/v#3589]
**V version:** V 0.1.24 5a25341
**OS:** macos

**What did you do?**
```
fn main() {
	$if debug {
		t := 'debug'
	}
	
	$if !debug {
		t := 'not debug'
	}
	
	println('t: $t')
}
```

**What did you expect to see?**
I expected this to compile
 
**What did you see instead?**
```
test.v:10:15: undefined: `t`
    8| 	}
    9| 	
   10| 	println('t: $t')
             	       ^
   11| }
```

**Comment by elimisteve** [comment]
@prime31 @dhonx `$if` is a compile-time if, so it makes sense that `t` would not be defined! Also, by defining `t` in a block, you won't be able to access it in a block.

You could do this, though:

```v
mut t := ''
if some_condition {
    t = 'different value'
}
```

**Comment by prime31** [comment]
I wouldn't expect a compiler define to create a block. In other languages a compiler block isnt created for conditional includes/excludes.

**Comment by elimisteve** [comment]
If you're not in debug mode then `t` won't be defined at all! Perhaps that is part of the problem?

**Comment by prime31** [comment]
In most other langs, it would look like this:
```c
#if defined(DEBUG)
float t = 5;
#endif

#if !defined(DEBUG)
float t = 6;
#endif

print("t exists here no matter what: %f", t);
```
or if it has an else:
```c
#if defined(DEBUG)
float t = 5;
#else
float t = 6;
#endif

print("t exists here no matter what: %f", t);
```

`#define` or `#if FLAG` or whatever the language uses does not create any variable scope, or at least in any of the languages I have used.

**Comment by medvednikov** [comment]
This is a preprocessor, so a bit different.

Any other languages that have this behavior?

**Comment by exastencil** [comment]
My 2 cents. Those are directives only, not blocks. I think it makes sense to have `$if condition` have the same scoping behaviour as `if condition`.

As a new user of V, I would expect to solve it the way @elimisteve suggested. Or alternatively, although it would be much harder, try to fit everything that depends on that conditional inside the block.

I think, looking at your source, **you** can see that `t` will always be defined because you are reasoning about it. If you wanted something that checked all the cases you would need something like:

```v
$if debug {
  t := 'debug'
}
else {
  t := 'normal'
}
```

because logically, having two `if`s doesn't guarantee all cases are covered, and in doing so the compiler would need to do tricky union scopes. In essence if `t` will always be declared, best to declare it upfront.

**Comment by medvednikov** [comment]
@exastencil yes, that's what I also think.

**Comment by medvednikov** [comment]
To keep the compiler simple, and make `$if` behave the same as `if`, it's not going to change.
