### ISSUE TITLE
Iterators/generators?

### ISSUE THREAD

**Issue by t-k-** [vlang/v#36]
Also, can we define iterator/generators?

**Comment by medvednikov** [comment]
Hi,

Yes I should add docs on modules.

There are no iterators.

From wiki:
> In object-oriented programming, the iterator pattern is a design pattern in which an iterator is used to traverse a container and access the container's elements. 

V is not an OOP language, and design patterns go against the philosophy of simplicity.

**Comment by medvednikov** [comment]
A good talk about the drawbacks and complexity of iterators:

https://accu.org/content/conf2009/AndreiAlexandrescu_iterators-must-go.pdf

**Comment by t-k-** [comment]
Thanks for the slides, although it fails to convince me. I think the slide takes from a purely C++ point of view, but reminber generator can belong to language as simple as Lua. I do not think OOP itself is bad and necessarily complex, it can be just an easy way for human to think about problem.

**Comment by medvednikov** [comment]
I was referring to iterators. Missed the generators bit.

Can you give a simple example of a generator?

**Comment by t-k-** [comment]
A good example would be from Lua official documentation: https://www.lua.org/pil/7.5.html

**Comment by medvednikov** [comment]
I think “for i in vals { }” does the job

**Comment by tjpalmer** [comment]
Generators in many languages (C#, Python, JavaScript, and presumably others) have a lot to do with coroutines. This example in C# shows somewhat: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/yield#example

Upcoming C++20 and Rust features also enable this in similar fashions.

Whether it matters for V likely depends a lot on how V's coroutines end up working.

**Comment by ntrel** [comment]
@medvednikov:
> There are no iterators.
> V is not an OOP language, and design patterns go against the philosophy of simplicity.

Iterator functions are just an interface, it's not OOP, there's no inheritance. The interface can be just two functions to:
* get an iterator from a container
* request the first/next element, which would return an optional result, empty if no more elements

> A good talk about the drawbacks and complexity of iterators:
> https://accu.org/content/conf2009/AndreiAlexandrescu_iterators-must-go.pdf

This talk is a critique of C++ iterators, the main problem with those is that start/end iterators are not paired, so the two might not match up, and by design this is not memory safe. This PDF proposes ranges instead, which are essentially just a pair of iterators. Andrei is the co-architect of [D 2.0](http://dlang.org) and he designed ranges to be key to D's standard library.

Iterators/ranges allow [generic algorithms](https://dlang.org/phobos/std_algorithm.html) to be written, which work with *any container type*, binary tree, linked list, array, hash table, etc.

> I think “for val in vals { }” does the job

How do you write a generic algorithm that needs to iterate through two containers, whose types can be different, that needs to step through the first container at different times to stepping through the second, e.g. [merge](https://dlang.org/phobos/std_algorithm_sorting.html#.merge (the examples all use arrays but the function works on any two container types that have a common element type).

I don't have experience of generators/`yield`, but it looks easy to use - I imagine performance would be worse than normal iterators.

**Comment by t-k-** [comment]
Also another feature I want in loop iteration, I can delete element from the container I am currently iterating without any issue (ensure I will not go into an infinite loop).

**Comment by medvednikov** [comment]
The language has to be small and simple, for now this will not be implemented. Maybe in the future if we figure out a simple way to do this.

**Comment by Naheel-Azawy** [comment]
Hi @medvednikov , I don't understand why you find it complicated. For generators maybe a bit, maybe you just need to create a thread and have a coroutine in it. For iterators, they are a bit uglier than generators but are extremely simple and good enough as an alternative to generators.

Here's an example iterator struct:

```v
struct Range {
    end int
mut:
    cur int
}

fn (r Range) has_next() bool {
    return r.cur < r.end
}

fn (mut r Range) next() int {
    return r.cur++
}
```

What people are asking for, I believe, is something like:

```v
for i in Range{end: 10} {
    println(i)
}
```

Which the V compiler should translate it to something like:

```v
mut iter := Range{end: 10}
mut i := 0
for iter.has_next() {
    i = iter.next()
    println(i)
}
```

Where the iterator struct (e.g. `Range`) should be checked to have `has_next()` that returns a `bool` and `next()` that returns whatever (but returns something).

A bonus can be adding some syntax to delete elements and use an iterator function, say `remove()`, to delete elements.

**Comment by medvednikov** [comment]
Ok, let's do this, as long as things are kept as simple as possible.

**Comment by t-k-** [comment]
I think the one who proposed the idea initially does not get any credit for it... 

[link](https://discord.com/channels/592103645835821068/592115457029308427/795822582393864192)

@elimisteve

I decided not to use V in the future, if you value implementation over ideas, I am going to write my own C preprocessor.

**Comment by elimisteve** [comment]
Hi @t-k-, your feature suggestion led to ideas for a simple conception of iterator from @ntrel and others, followed by an implementation from @spaceface777. Go team! 👍

**Comment by lilenvy** [comment]
Was this change documented? Is it just a matter of implementing `next(): ?T` on the struct and does it support any type `T` or does it require to be an `int`?

**Comment by spaceface777** [comment]
> Was this change documented? 

not yet, I'll do that asap.

> Is it just a matter of implementing `next(): ?T` on the struct 

yup, `return T` if there are elements left, `return none` otherwise.

> does it support any type `T` or does it require to be an `int`?

this should work for any T, file a bug report if it doesn't.
