### ISSUE TITLE
Missing releases for vc?

### ISSUE THREAD

**Issue by SeekingMeaning** [vlang/v#3754]
https://github.com/vlang/vc seems to be missing releases for the versions following 0.1.20:

- 0.1.24 - vlang/vc@b9ea14b1f384b584b146ee59a8b179a1e2d68299
- 0.1.23.1 - vlang/vc@66368fffce007edc7f49fa8e51de5a07bac17773
- 0.1.23 - vlang/vc@0cbfbf61ddafabc4115ab5e9a85214942c12ce7f
- 0.1.22 - no commit found for vlang/v@11366e3
- 0.1.21 - vlang/vc@950a90b6acaebad1c6ddec5486fc54307e38a9cd

**Comment by joe-conigliaro** [comment]
@SeekingMeaning there could be missing releases in a few situations, it was never intended to be an archive of vc releases, just an automated way of updating the vc repo. if two or more commits happen with 5 mins it will only update to the newest commit, and also there is the odd time the stipt brkoe due to breaking changes and needed manual intervention

**Comment by SeekingMeaning** [comment]
Would it be possible to add them to https://github.com/vlang/vc/releases?

**Comment by medvednikov** [comment]
There's no point in that because until 0.2 V is on a rolled release schedule.

Things change too fast.
