### ISSUE TITLE
Ideas and Suggestions

### ISSUE THREAD

**Issue by cristian-ilies-vasile** [vlang/v#3961]
**Please add your ideas, suggestions, remarks etc here**

**Comment by cristian-ilies-vasile** [comment]
Please add posit[1] and bfloat16[2]. 
Posits/unums are used in HPC computing and bfloat16 on neural networks training. Might be of interest in the future. 
[1] https://en.wikipedia.org/wiki/Unum_(number_format)
      https://posithub.org/index
[2] https://en.wikipedia.org/wiki/Bfloat16_floating-point_format

**Comment by cristian-ilies-vasile** [comment]
We should probably compile the .o files in a separate folder under ~/.vmodules/cache/, and the name of the .o file should contain the names of the target platform and used c compiler
plus a text file (module.txt) with  the command line used to compile that module

**Comment by spytheman** [comment]
I think the topic of this issue is too general - these 2 ideas (a) support for different kinds of numbers formats, and b) for the .o file compilation cache), are not related to one another, and should be in 2 separate issues instead. In this way, people that are interested in each idea can discuss it separately, and when for example support is implemented for one, the corresponding issue can be closed.
