### ISSUE TITLE
stmt must return "v.ast.Stmt"

### ISSUE THREAD

**Issue by keito940** [vlang/v#4069]
**V version:** 0.1.24
**OS:** Windows 10

**What did you do?**
Label Loop Implementing.
(About for #4005.)

**What did you expect to see?**
Compile Passed.
 
**What did you see instead?**
```
Building V
git version 2.25.1.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Now using V to build V...
V Self Compiling (-prod mode)...
vlib\v\parser\parser.v:356:27: stmt must return "v.ast.Stmt"
  354| }
  355| 
  356| pub fn (p mut Parser) stmt() ast.Stmt {
                                 ^
  357| 	match p.tok.kind {
  358| 		.key_assert {
v.exe failed to compile itself - Create an issue at 'https://github.com/vlang'
Exiting from error
```

**Comment by hazohelet** [comment]
V told you to "Create an issue" but you're not supposed to do so because you're taking part in the compiler development.

There're some errors in your source code, like in #4052

V says "Create an issue" when V can't compile **itself**. You're editing the compiler's source code, so in this situation V is saying "Create an issue" because V can't compile **your source code**
