### ISSUE TITLE
consistent naming convention for test file and test function

### ISSUE THREAD

**Issue by yanghao** [vlang/v#4390]
Hello guys, just realized in vlang test files are named "abc_test.v" whereas test functions are named "test_xyz" ... just wondering if it would be better to name all tests starts with "test_", wouldn't this feel a bit more consistent to always have file/function name started with "test_" means this is for testing?

**Comment by JalonSolov** [comment]
The Go language automatically grabs files that end in "_test.go" to run when you use "go test" without specifying the name of a file to run.

Individual tests within a file in Go also normally start with "test" as the function name.

Since V started from Go (was written in Go originally), I would imagine the same conventions were used here.

So it is already consistent... with Go, and possibly other languages.

**Comment by medvednikov** [comment]
@JalonSolov pretty much nailed it.

V is consistent with Go in many cases, including this one.
