### ISSUE TITLE
vlib/v/tests/live_test.v failing

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#4856]
**V version:** V 0.1.27 fd71093
**OS:** Alpine 3.11.3

**What did you do?**

v test-fixed

**What did you expect to see?**

All tests passed/skipped.
 
**What did you see instead?**

```
FAIL [138/173]  9318.130 ms vlib/v/tests/live_test.v
Compiling and running with: /home/jalon/git/v/v -live run /home/jalon/.cache/generated_live_program.v > /home/jalon/.cache/generated_live_program.output.txt &
... running in the background
> change ORIGINAL to: CHANGED
> done.
> change ORIGINAL to: ANOTHER
> done.
source: /home/jalon/.cache/generated_live_program.v
output: /home/jalon/.cache/generated_live_program.output.txt
      1 END
      1 START
    304 CHANGED
---------------------------------------------------------------------------
> found START 1 times.
> found CHANGED 304 times.
> found END 1 times.
---------------------------------------------------------------------------
/home/jalon/git/v/vlib/v/tests/live_test.v:66: failed assert in testsuite_end()
Source  : assert histogram['ORIGINAL'] > 0
```

Every other test passed or was skipped, as expected.

**Comment by JalonSolov** [comment]
Same test works fine on Ubuntu 19.10.

**Comment by krischerven** [comment]
The test fails on Pop!_OS 20.04, same error message

**Comment by JalonSolov** [comment]
Fails today on Ubuntu 20.04.

**Comment by JalonSolov** [comment]
Here's a thought, though... is the test failing, or is it actually just starting to work correctly?

If the `main()` function is only run once, then the first time `change_source()` is called it will modify the file, and the second time it won't be able to because it is trying to change the word that has already been changed.

That would mean the
```
assert histogram['ORIGINAL'] > 0
```
will (and SHOULD) always fail.

Of course, if `main()` is actually run before every individual test, then it should be working correctly as-is.

**Comment by JalonSolov** [comment]
One other "fun" thing.  At the end of tests, there s a V panic...
```
               16662.129 ms <=== total time spent testing all fixed tests
                 ok, fail, skip, total =   172,     1,     4,   177
V panic:
WARNING: failed 1 times.

                                               | 0x55f3340a4a4c | /home/jalon/git/v/cmd/tools/vtest-fixed(+0x31a4c)
                                               | 0x7ff2d514a0b3 | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)
                                               | 0x55f334075a2e | /home/jalon/git/v/cmd/tools/vtest-fixed(+0x2a2e)
```

**Comment by spytheman** [comment]
This goal of this test, is to simulate a developer, that has run a program, compiled with `-live` flag.

It does so by writing a new program containing a `[live] fn pmessage() {...}` function, then runs the generated program at the start in the background, waits some time, so that the program could run a few iterations, then modifies its source (simulates a developer that has saved a new version of the program source), waits some more, modifies it again and saves it.

On each modification, the running program, should detect that its source code has changed, and recompile a shared library, which it then it should load, and thus modify its own behavior at runtime (the `pmessage` function).

Since this test program is sensitive to coordination (or lack of) of several processes, it tries to sidestep the coordination issue by just waiting enough time, which is clearly not enough in some cases. That approach is clearly not ideal, but I currently do not an idea on how to improve it without better process control primitives/communication to the background program. Suggestions are welcome.

**Comment by spytheman** [comment]
On ubuntu 16.04 and solaris, it prints a variation of:
![a working live test](https://url4e.com/gyazo/images/1a92ee9d.png)

**Comment by JalonSolov** [comment]
Now that you've explained how it works, I wonder if this is another case of my machine being too fast.

Seriously, already had to get one thing fixed because of this (the numbers & results in `v test-fixed` were off).

I'll see if I can come up with something.

**Comment by spytheman** [comment]
I just thought of another way for the generated program to communicate back its state to the test - it could write 3 files `ORIGINAL.txt` , `ANOTHER.txt` and `CHANGED.txt` , and the test could poll for them (with a larger timeout) periodically, and continue after they appear. 

That hopefully will make the test less dependent on the speed of the machine/compiler on which it is running, while in most cases speeding up the test (since it would continue in most cases after only just a small delay, instead of waiting).

**Comment by spytheman** [comment]
With polling instead of blindly waiting, it is slightly faster, and should be more stable:
![live test with polling](https://url4e.com/gyazo/images/b89a16a1.png)

**Comment by spytheman** [comment]
@JalonSolov can you please test if `./v vlib/v/tests/live_test.v` works more reliably now on your machine?

**Comment by JalonSolov** [comment]
Yes, the test passes now, as expected.  Good job!

**Comment by spytheman** [comment]
Thanks.
