### ISSUE TITLE
Anon function inside of if expr gets ternery'd by cgen

### ISSUE THREAD

**Issue by emily33901** [vlang/v#5134]
**V version:** V 0.1.27 f90a2d2
**OS:** MSVC Windows

**What did you do?**
```v
is_packed := if field.label == 'repeated' {
	// TODO revert when some issue that I havent made yet is fixed
	x := fn()bool {
		for o in field.options {
			if o.ident == 'packed' {
				return o.value.value == 'true'
			}
		}

		return false
	}
	x()
} else {
	false
}
```

**What did you expect to see?**
no error
 
**What did you see instead?**
Massive C error because of

```c
bool  anon_8459__16() {
				(
				// FOR IN array
				array _t1 = field->options;
				for (int _t2 = 0; _t2 < _t1.len; _t2++) {
					compiler__FieldOption* o = ((compiler__FieldOption**)_t1.data)[_t2];
					(
					(string_eq(o->ident, tos_lit("packed")) ? (
						return string_eq(o->value.value, tos_lit("true"));
					
					): 0)
				)}
				,
				return false;
			
			)}
```

which its right is definitely not valid C code.

**Comment by Gladear** [comment]
This should be fixed once I'm done with #5095 🙂

**Comment by ArtemkaKun** [comment]
So @emily33901, do you still have this error or the issue can be closed?

**Comment by emily33901** [comment]
This is almost certainly not an issue any more

**Comment by ArtemkaKun** [comment]
Hi @emily33901 

I tested the next code and it doesn't throw any error and produces the expected output.
```v
struct Field {
	label   string
	options []MyOption
}

struct MyOption {
	ident string
	value Value
}

struct Value {
	value string
}

fn main() {
	field := Field{
		label: 'repeated'
		options: [
			MyOption{
				ident: 'packed'
				value: Value{
					value: 'true'
				}
			},
		]
	}

	is_packed := if field.label == 'repeated' {
		x := fn (field Field) bool {
			for o in field.options {
				if o.ident == 'packed' {
					return o.value.value == 'true'
				}
			}

			return false
		}

		x(field)
	} else {
		false
	}

	println(is_packed)
}
```

It differs a bit from the issue code (because Windows doesn't support [closures](https://github.com/vlang/v/blob/master/doc/docs.md#closures).

### Testing environment
Windows 11, VS 2021

### How did I test
1. Wrote V code
2. `v -skip-unused -o main.c main.v`
3. `cl main.v`

### Output of C code
![image](https://user-images.githubusercontent.com/36485221/149575512-9b6211aa-157f-4b3b-92d4-95d43f3063b2.png)

Is everything is ok up to you - please, close the issue :)
