### ISSUE TITLE
Freeze on strconv.v_sprintf

### ISSUE THREAD

**Issue by shnorbluk** [vlang/v#5151]
Hi! I'm new to V but I find it promising and hope it will become more popular.
When I execute the example in [v_sprintf](https://github.com/vlang/v/blob/master/vlib/strconv/format.md#v_sprintf), it runs endlessly. Surprisingly, all tests in strconv are OK! Maybe you could add the "Hello world" example in tests?
Again, thank you for your job.

**Comment by spytheman** [comment]
This is due to a known bug with the implementation of main and how it interferes with varargs.
It would be fixed soon, when main is not treated as specially as it is now.
If you put the example in another function, then call it in main, it should work:
![ordinary_function](https://url4e.com/gyazo/images/1e9fced0.png)

**Comment by spytheman** [comment]
The tests work since they are executed inside test_ functions not inside `main`.

**Comment by shnorbluk** [comment]
You're right. It works outside of main.

**Comment by shnorbluk** [comment]
Yes, to get compile time string concatenation. But my need was to generate numbers padded with zeros, and printf seemed the simplest way.

**Comment by penguindark** [comment]
you can use string concatenation like this: 
```
fn main(){
	a := 1234
	allign_l := "[${a:-10}]"
	allign_r := "[${a:10}]"
	println("$allign_l $allign_r")
}
```
:)

**Comment by shnorbluk** [comment]
I didn't see it ;)  but it is documented here : https://github.com/vlang/v/blob/master/doc/docs.md#strings .
My code is:
```go
a := 1234
println("${a:06d}")
```
