### ISSUE TITLE
CudaText has V syntax now

### ISSUE THREAD

**Issue by Alexey-T** [vlang/v#536]
V lexer is in addons. Plugins / AddonManager / Install -> choose "lexer: V".

CodeTree panel supports items: fn, enum, interface, struct.
 
![Screenshot from 2019-06-25 01-05-44](https://user-images.githubusercontent.com/4154978/60055239-a3207000-96e5-11e9-808c-de9970308b45.png)

**Comment by MostHated** [comment]
Hopefully Jetbrains is not far behind (GoLand)

**Comment by Alexey-T** [comment]
Lexer updated.

**Comment by bitsnaps** [comment]
@Alexey-T Nice, however I can't install python3 on my mac because it conflict with the system, I'm using `virtualenv` from `conda` to use isolated python3, so CudaText cant detect python3
`No Python engine (3.x) found. Python plugins don't work now. To make it ok:
install Python 3.x from www.python.org, it should be found by CudaText then.`
it there any way to configure CudaText to use `conda` (or `Anaconda`)?

**Comment by Alexey-T** [comment]
@bitsnaps I think you can- open config user.json, and write there option "pylib__mac". Its example in default.json-

      "pylib__mac": "/Library/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5.dylib",

**Comment by bitsnaps** [comment]
@Alexey-T Thanks! in my case it was: `{"pylib__mac":"/miniconda2/envs/py3/lib/libpython3.7m.dylib",}
`

**Comment by Alexey-T** [comment]
@bitsnaps Will add this info to the Cudatext Wiki, thanks.

**Comment by medvednikov** [comment]
Thanks!

**Comment by bogen85** [comment]
If anyone else wants to look into this: https://github.com/Alexey-T/CudaText/issues/4473
Please let me know.

**Comment by Alexey-T** [comment]
@bogen85 No problem, i will fix the lexer.
