### ISSUE TITLE
[Race Condition] Race Condition breaking the program

### ISSUE THREAD

**Issue by nasirhm** [vlang/v#5403]
**V version:** V 0.1.27
**OS:** Linux:  5.6.18-300.fc32.x86_64

**What did you do?** 
```v
fn main(){
    foo := [1]
    go add(mut foo)
    go add(mut foo)
    for {}
}
fn add(mut foo []int) {
    for {
        foo[0] = foo[0] + 1
    }
}
```

**What did you expect to see?** this should have two threads infinitely trying to increment foo[0], which will eventually result in foo[0] getting corrupted by two threads trying to do the same thing at the same time (given the tight loops invovled).
 
**What did you see instead?**
I can't build it.

**Comment by amoyyy** [comment]
```
import time
fn main(){ 
    mut foo := [0,0,0]
    go add1(mut &foo)
    go add2(mut &foo)
    for {
        if foo[0] > 5000 {
            println(foo)
            break
        }
    } 
} 

fn add1(mut foo &[]int) { 
    for{ 
        foo[0] = foo[0] + 2
        foo[1] = foo[1] + 1
        time.sleep_ms(1) 
    } 
}

fn add2(mut foo &[]int) { 
    for{ 
        foo[0] = foo[0] + 1
        foo[2] = foo[2] + 1
        time.sleep_ms(1) 
    } 
}
```
Although not safe, passing the address to 'add()'  will pass the build.
And the foo[1], foo[2] records the calling times.

**Comment by spytheman** [comment]
The original in Christine's blog was formatted better. Please use triple backticks to quote source code here.

**Comment by spytheman** [comment]
The original should have produced a V error, since `foo` is immutable, not a C compilation error.

The deeper issue, that the threads are racing and overwriting the same block of memory, can not be solved easily right now. V does not have a builtin race detector. If someone wants to implement one, go ahead.

**Comment by dumblob** [comment]
>V does not have a builtin race detector. If someone wants to implement one, go ahead.

In addition, please note, that a race detector detecting all possible races in *V* is impossible to build with the current *V* semantics. So any *V* race detector would detect just a strict subset of races.

**Comment by nasirhm** [comment]
> The original in Christine's blog was formatted better. Please use triple backticks to quote source code here.

Indeed It's from Christine's Blug post, Thanks for fixing the formation with triple backticks along with clarifying the issue.

**Comment by ArtemkaKun** [comment]
Hi @nasirhm
I believe this issue is not valid anymore and should be closed. I did a test of your code on the fresh V (a master branch from 17.01.2022) and the results are:

1) First of all, as @spytheman mentioned, the original code will not compile and V will throw an error **`foo` is immutable, declare it with `mut` to make it mutable**
2) To make the original code works, you must make *foo* var mutable and pass it to the *add()* method as reference (see the code below). After these changes, the V errors will disappear and the code will compile and run without errors and crash (still with race condition if I understood things right).

```v
fn main() {
	mut foo := [1]
	go add(mut &foo)
	go add(mut &foo)
	for {}
}

fn add(mut foo []int) {
	for {
		foo[0] = foo[0] + 1
	}
}
```

Let me know what do you think about the status of this issue and what we should do with it.

**Comment by nasirhm** [comment]
As the code will execute as expected, we're good to close. Thanks @ArtemkaKun
