### ISSUE TITLE
Compile error: cannot assign `map_string_any_int` as `map_string_int`

### ISSUE THREAD

**Issue by nord501** [vlang/v#5414]
**V version:** V 0.1.27 947e892
**OS:** Linux

**What did you do?**
```
struct Struc {
pub mut:
	api  map[string]int
}

fn name() {
	// ok
	m := Struc {
		api: {'x': int(0) }
	}

	// error
	n := Struc {
		api: {'x': 0 }
	}
}
```

**What did you expect to see?**
I'm not sure this code is legitimate, just want to report compile error
 
**What did you see instead?**
```   11 |     // z.v:13:3: error: cannot assign `map_string_any_int` as `map_string_int` for field `api` ```

**Comment by medvednikov** [comment]
@UweKrueger how do you think this should be solved?

**Comment by UweKrueger** [comment]
Hmm... There are two possibilities:
- Handle this special case in `check_types.v` - however these checks are complicated enough...
- deduce the precise type of a map literal by examining the first element and applying `c.table.mktyp()` to the value - then the type has only got to be specified if it is not `f64` or `int`, like `api map[string]u16` ... `api: {'x': u16(0)}`.

I would prefer the second approach since it is consistent with what is done with array literals. I'll prepare a PR...

**Comment by medvednikov** [comment]
Thanks. check_types.v is also fine by me, doesn't really matter.
