### ISSUE TITLE
Infer return types from C functions (and better C interop)

### ISSUE THREAD

**Issue by LouCle** [vlang/v#555]
The issue boils down to this.
```
dir := C.opendir(...) // --> dir is inferred to be void* instead of DIR* (which is what the C function returns).
```
A shitty workaround is to do the following (creating a wrapper function specifying the return type)
```
fn _opendir(...) *C.DIR {
    return C.opendir(...)
}
```
and then do the same again
``` 
dir := _opendir(...) // --> dir is now inferred to be DIR*
```
Obviously that isn't viable, and we need to add this in the compiler

Another thing to note is that you cannot use C types as fn args, because they're not defined inside the type table. Solving this is a good step in being able to remove the `#` tag from code.

(also realize this is a bad example as this could work solely on void pointers)

**Comment by Henrixounez** [comment]
As you know, the big problem is to find the correct return type of functions.

Right now, for C functions there is a small function (`table.v : find_fn`) looking inside a table of registered functions, it will find the type and return it.
If no type is found it is automatically made into a `void *` , a trick that works quite well (`parser.v: name_expr`).

Your example works as the return type of opendir is a pointer, but it can be annoying for this example (From @RustemB in Discord) :
```
c := C.getchar() //int getchar(void)
println(c)
```
Here we would expect the println to show a number, but instead shows an hexa number, it is because the `c` variable is infered into a `void*` making the `println` think it needs to print a pointer.
A quick fix for the user would be to cast the return of the function into the type he want :
```
c := byte(C.getchar())
```

**Comment by ntrel** [comment]
I thought we're supposed to add a function prototype and struct declaration:
https://vlang.io/docs#calling_c

I don't see how V can simply infer a C function return type.

**Comment by ntrel** [comment]
> looking inside a table of registered functions, it will find the type and return it

Why don't we just add the prototypes for those functions to a built-in module?

> If no type is found it is automatically made into a void *

I think this should be an error, V should require prototypes to call C functions.
