### ISSUE TITLE
vlib-docs returns bad token `asm` error on Windows

### ISSUE THREAD

**Issue by robotee** [vlang/v#5742]
**V version:** V 0.1.28 97ef860
**OS:** Windows 10

**What did you do?**
`v vlib-docs`

**What did you expect to see?**
The documentation of the vlib modules

**What did you see instead?**
```
C:\v\vlib\builtin\bare\linuxsys_bare.v:233:3: error: expr(): bad token `asm`
  231 | fn do_not_call_me_asm_keeper0() {
  232 |     unsafe {
  233 |         asm {
      |         ~~~
  234 |             "\n"
  235 |             "ret\n"
```

**Comment by nedpals** [comment]
@robotee Did you update `vdoc`? This should respect ignore rules contained in `vlib/.vdocignore` file

**Comment by robotee** [comment]
> 
> 
> @robotee Did you update `vdoc`? This should respect ignore rules contained in `vlib/.vdocignore` file

I'm sorry but what do you mean by updating `vdoc`? and how is this `.vdocignore` file related to this issue ?. I'm new to V and  this problem appears only on windows but not on Linux and I'm sure I don't remember updating anything related to `vdoc`.

**Comment by nedpals** [comment]
@robotee `v vlib-docs` is just an alias command for `v doc vlib`. The `.vdocignore` file found on the vlib folder ignores the paths that the program needs to generate documentation. Included there in the file is the `builtin\bare\` in which you reported and should've been ignored by the program hence was asking if you updated the `vdoc` program included in the compiler since that feature is recently added.

**Comment by nedpals** [comment]
Closed as it was already fixed in the later versions of vdoc.
