### ISSUE TITLE
http.FetchConfig memory leak

### ISSUE THREAD

**Issue by thomaspeissl** [vlang/v#6128]
**V version:** V 0.1.29 eba4138.078ab47
**OS:** POP OS 20.04 (Linux)

**What did you do?**
import net.http
fn main() {
	mut c := http.FetchConfig{}
	for {
		// resp := http.fetch('https://vlang.io', http.FetchConfig{method: .get}) or {exit(1)}
		c = http.FetchConfig{}
	}
}

**What did you expect to see?**
Programm running in an endless loop without affecting memory usage.
 
**What did you see instead?**
In task manager. Program using 10 GB RAM in 5 seconds.

**Comment by ArtemkaKun** [comment]
Hi @treffner, I checked your code on fresh V (master branch from 21.01.2022) and still have this behavior.

First of all, since *-autofree* isn't a default flag for V and in your example you didn't use GC, as far as I understood, V wouldn't free any memory by itself.

With GC, memory leak for this code doesn't exist but uses an anomaly amount of CPU power. I will open a new issue to investigate this case more.

**Comment by medvednikov** [comment]
Fixed in 0.3
