### ISSUE TITLE
vlang ? rust but worse ?

### ISSUE THREAD

**Issue by Dammibruh** [vlang/v#6202]
Unpopular opinion around here but i think V doesn't deserve all of it's popularity. It hasn't even been around for a year and its already more popular than haxe, a language that has been worked on for more than four years. I just think its unfair that all of these langauages put in years of work on their language only to find out that V has gained more popularity than them. It must be super annoying that a languages that have been worked on for years and give what the languages offers gets overtaken by some language that is not even ready and is advertised falsely. I mean, come on, "No undefined behaviour"? How can you claim this when:
- There is no spec
- You are targeting C
- There are compiler bugs

Not to mention that V 1.0 was scheduled for release in December 2019... and issue 35

**Comment by gslicer** [comment]
So, you believe software on which ppl worked for a longer time should be more popular just because of this fact? By this terms Minix should be more popular than Linux by far... Are you serious?

**Comment by JalonSolov** [comment]
"Psychologists call this “irrational thinking” or a “cognitive distortion.” This specific distortion of our thoughts is called the Fallacy of Fairness. It basically says that somewhere in our head, we sometimes think like a child that all of life “should be fair.” Whether it should be a certain way or not is largely besides the point — because it isn’t."

We are working on a new language.  Whether or not others find it interesting is up to them.  If enough find it interesting, and tell others about it in an interesting way, it becomes popular.

The popularity of V is also not something anyone here wants to discourage.

If you are truly interested in V, I would suggest cloning it and giving it a try.  Otherwise, I wish you well in your future endeavors.

**Comment by spytheman** [comment]
> There is no spec
Demanding a spec for a language, that has not yet reached 1.0 is somewhat pushy, imho.

> You are targeting C
So what ? C++ also targeted C initially. C has many benefits as a compiler target. Please see https://github.com/vlang/v/wiki/On-the-benefits-of-using-C-as-a-language-backend for more details.

> There are compiler bugs
Just yesterday, I found a gcc optimization bug. Should I stop using gcc, then go bitch about that to its developers, and write nasty blog posts shitting on their hard work?

Are not you tired of being a troll @Dammibruh? Are you bored?
