### ISSUE TITLE
Enhance the Readme file

### ISSUE THREAD

**Issue by imanghafoori1** [vlang/v#6229]
`Performance: within 3% of C`

To be honest, I can not get the meaning:
1 - Is it 3% of the speed of C  (C does 100 things but V does 3, within the same time)
2-  Is it 97% of the speed of C  (C does 100 things but V does 97, within the same time)

I think a better explanation is needed. 
Thanks everyone

**Comment by JalonSolov** [comment]
"within 3%"  means the difference in performance of the V code against the performance of natively written C code will be 3% or less.  It might be anywhere from 0 down to 3% worse, but it will not go beyond that.

To put it in the terms you used: if C does 100 things, V might do 97 or 98 or 99 or 100, within the same time, depending on the code.  Since V generates C code which is then compiled, it  is unlikely it will do MORE things than the native C code... assuming the C code was well-written.

Of course, if the native C code is badly written, the V code may well be faster.

This is a fairly common way of stating such things in English.  It is short and succinct, as opposed to my response here.  :-\

**Comment by ntrel** [comment]
If we have good generic versions of C standard library functions like qsort and bsearch, performance should be significantly better than C, like how C++ algorithms are faster.

**Comment by imanghafoori1** [comment]
I think a better explanation is needed, since the fact is unbelievable, for a language to be the fast. 
Just write:
"As fast as native C"
V

**Comment by imanghafoori1** [comment]
I did some benchmark against rust and it performed better also the binary was smaller.

**Comment by medvednikov** [comment]
Current language is correct.
