### ISSUE TITLE
Variable name cannot contain uppercase letters

### ISSUE THREAD

**Issue by VinWare** [vlang/v#6362]
**V version:** V 0.1.29 bffa100

**OS:** Linux 5.4.0-47-generic

**What did you do?**
Used uppercase name in variables, like:
`A:=2`
`a_A:=2`
`aA:=2`
**What did you expect to see?**
Successful initialization
 
**What did you see instead?**
`error: variable name `A` cannot contain uppercase letters, use snake_case instead`
`error: variable name `a_A` cannot contain uppercase letters, use snake_case instead`
`error: variable name `aA` cannot contain uppercase letters, use snake_case instead`

**Comment by VinWare** [comment]
If this is not a bug but an undocumented feature (I did not see anything about identifier naming), then please document

**Comment by JalonSolov** [comment]
It is correct, but there is no explicit documentation.  The compiler enforces it as you have seen, and it is the final arbiter.

The rules are:  variables all lowercase, with snake_case recommended if you want separators.  Struct and Type alias names _must_ start with an uppercase character.

This was done so that it is visually obvious what you're looking at when you read through the code.

**Comment by VinWare** [comment]
Ok, and what about functions?

**Comment by medvednikov** [comment]
The error is clear, and I've just added this to the docs (Variables section).
