### ISSUE TITLE
A curse library 

### ISSUE THREAD

**Issue by joeitu** [vlang/v#6378]
Hello, 

I haven't found any curse in the doc or example. 

Is it possible to create a curse application with vlang yet ?

**Comment by JalonSolov** [comment]
I hope you mean [curses](https://en.wikipedia.org/wiki/Curses_(programming_library)).  :-)

Otherwise... no, V doesn't stand for "Voodoo".  :-)

No, there is no curses for V, but there is the "term" module, which does something similar.

https://modules.vlang.io/term.html

If it doesn't do what you need, please create issues for specific things, or even better, PRs are always welcome.  :-)
