### ISSUE TITLE
Translating V to C#/MSIL

### ISSUE THREAD

**Issue by wond12** [vlang/v#638]
Is it possible to translate V to C# or MSIL, so that v could be used in unity.

**Comment by kinggoesgaming** [comment]
This honestly will need LLVM-isque infrastructure for it to be possible, as doing so we are entering the world of building multiple targets

**Comment by TheStr3ak5** [comment]
@kinggoesgaming since when LLVM compiles to MSIL... LLVM compiles to native object code for several platforms, but MSIL is not native neither object code, but a bytecode used specifically for the .NET environment.
Such a task would require a specific backend to MSIL, which right now is not feasible in the state of the compiler imho, there is just too much to fix for this to be a real proposition.

**Comment by 3442853561** [comment]
@wond12 We are porting the V language to .Net and Wasm.

**Comment by 3442853561** [comment]
@wond12 We are writing another implementation in V and Rust. To port the V language to CLR and Mono. To avoid the negative effects of certain features (such as GC) on the V language, we call it V++ for the time being. We hope that it will become a member of the V family for Unity.

Project website: [https://github.com/casaliuqi-com/vpplang](https://github.com/casaliuqi-com/vpplang)

**Comment by medvednikov** [comment]
This is definitely doable.
