### ISSUE TITLE
To allow the user the use of semicolons

### ISSUE THREAD

**Issue by Joe23232** [vlang/v#6558]
Having a lack of semi collins `;`  only makes it harder for the programmer.

For exmaple in Rust:

```rust
fn main()
{
    println!("Hello, world!
    asd
    ads
    ads
    ads
    ads
    asd
    
    
    ");
}
```

This is perfectly legal. However in V this is not legal. I just had a play with the wasm live environment and it threw me an error when I tried the same thing there.

```
fn main()
{
    println("Hello, world!
    asd
    ads
    ads
    ads
    ads
    asd
    
    
    ")
}
```

A lack of semi collin only limits the programmer and I believe it should be optional if the user chooses to use semi collins. Even Python allows the use of semi collins.

**Comment by JalonSolov** [comment]
"semicolons" not "semi collins".

"semicolon" is defined as "a punctuation mark (;) indicating a pause, typically between two main clauses, that is more pronounced than that indicated by a comma."

The reason they aren't used is because they aren't necessary.  The compiler knows where things end.

Yes, other languages require them, and so many programmers are used to using them, but they simply are not needed.

**Comment by medvednikov** [comment]
Your example compiles just fine. I recommend using the V compiler for your OS, not WASM, it's not as stable yet.

I also don't see what this example has to do with semicolons.

**Comment by Joe23232** [comment]
> Your example compiles just fine. I recommend using the V compiler for your OS, not WASM, it's not as stable yet.
> 
> I also don't see what this example has to do with semicolons.

Oh I see I will do that then.

And I thought the lack of semicolons was causing me not to compile code that had enter characters inside the println function.

**Comment by medvednikov** [comment]
No, V strings can have newlines.

**Comment by Joe23232** [comment]
Thanks man
