### ISSUE TITLE
Regarding memory management

### ISSUE THREAD

**Issue by Joe23232** [vlang/v#6566]
I know that currently V doesn't have memory management, but how is it going to work if it is not afaik going to use the ownership model once when it is implemented? Is it going to use reference counting?

**Comment by medvednikov** [comment]
It does, via -autofree, work in progress. All details will be made public soon.

**Comment by Joe23232** [comment]
@medvednikov Would this have any runtime overhead?

**Comment by JalonSolov** [comment]
Of course.  ALL actions in your code have runtime overhead, if they run at all.

However, the "overhead" in this case is just the compiler calling 'free' for you, instead of you having to do it yourself.

I honestly wonder why everyone is so hung up on memory management... as long as it works, why care?

If it isn't working, open an issue.

Of course, if you're the one implementing the memory management code, you should care about it, but otherwise...

**Comment by Joe23232** [comment]
> However, the "overhead" in this case is just the compiler calling 'free' for you, instead of you having to do it yourself.

You are saying _compiler_ so do you mean that it calls _free_ during compile time? If so how would this result in overhead during runtime execution?

> I honestly wonder why everyone is so hung up on memory management... as long as it works, why care?

I am just curious to know how it works.

**Comment by JalonSolov** [comment]
No, I mean the compiler generates the free call to be executed during runtime.

**Comment by Joe23232** [comment]
I see, thanks.

![image](https://user-images.githubusercontent.com/34926497/95087976-1381c200-076e-11eb-9c59-254e68733df0.png)

While I understand that the free call might not generate _that_ much overhead, however it still does generate overhead, therefore wouldn't it be slower than C?

**Comment by medvednikov** [comment]
You do realise you need to call free in C as well? I suggest Discord for such discussions.

**Comment by ntrel** [comment]
@JalonSolov 
> However, the "overhead" in this case is just the compiler calling 'free' for you, instead of you having to do it yourself.

Only if the memory reference doesn't escape its initial owner. If it does then either reference counting or defensive copying must be used.

> I honestly wonder why everyone is so hung up on memory management... as long as it works, why care?

Dynamic memory management is often a huge source of slowdowns in otherwise performant code. It also can cause unnecessary memory exhaustion or hangs even without a tracing GC. Also it is closely related to memory safety, which is critical for reliable and secure software.

**Comment by JalonSolov** [comment]
Yes, I understand all the issues with memory management.  I've been at this a long, long time.

Again, I ask:  If it works, why care how it's done, unless you're working on the memory management code itself?
