### ISSUE TITLE
Thoughts on making struct fields immutable by default?

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#68]
```
struct Point {
    x     int
    y mut int
}

...

mut point := Point{x:10, y:20}
point.x++ // won't compile
point.y++ // OK
```

**Comment by zac-garby** [comment]
I like the idea, so long as there’s an advantage to immutable fields (e.g. perhaps they can be optimised further during compilation)

**Comment by PavelVozenilek** [comment]
Why not to reuse constants? 

```
struct Point1 {
    x     int
    const y int = 1 // always the same constant value, not set in constructor
}

struct Point2 {
    x     int
    const y int // has to be set in constructor
}

Point2{x:10, y:20}
```

Immutable struct member is exception, should not be default.

**Comment by ntrel** [comment]
> `y mut int`

This is good, consistent with variables. (`mut` should be a type modifier (see #41), rather than a declaration modifier, this helps towards that).

> so long as there’s an advantage to immutable fields

All the same advantages as immutable variables, including optimization. In particular, immutable data can be shared across threads without races.

> const y int // has to be set in constructor

`const` in V means compile-time constant. A struct is essentially multiple variables grouped together, so fields should have the same features and syntax as variables IMO.

**Comment by PavelVozenilek** [comment]
One note: immutability is something what can be inferred by the compiler (if the language doesn't act against, e.g. via function pointers).

1. The compiler can (for speed probably in release mode) track mutability status of variables/data members, and warn if they are used inappropriately, causing data race risk.
2. Hypothetical advanced IDE could differentiate immutable and mutable data/function parameters, highlight them differently, and show places they are mutated. This information could be only crudely replicated by mut/const keywords, with lot of busywork and fragility.
