### ISSUE TITLE
toml or yaml support

### ISSUE THREAD

**Issue by despiegk** [vlang/v#7022]
is it possible to have toml or yaml support for serialization?

maybe we can use c lib for now?

**Comment by medvednikov** [comment]
V will support TOML-like config language natively (similar to TOML, but much smaller and simpler). I had it on a branch since I needed it for V UI. Will release it next week.

YAML is a huge complex format, so it's not so easy to implement. We will have an official YAML module once comptime is stable enough to implement serialization outside the compiler.

**Comment by medvednikov** [comment]
Using a C lib is always an option in V, just need to write a small 50-100 line wrapper so that the library can be easily used in V without going low level. For example: https://github.com/vlang/v/blob/master/vlib/sqlite/sqlite.v

**Comment by esquerbatua** [comment]
#708

**Comment by Ekopalypse** [comment]
I guess this one can be closed, TOML is #7092 and as already pointed out, YAML is #708
