### ISSUE TITLE
Regression with v0.1.30 compiling on Windows when importing gg

### ISSUE THREAD

**Issue by MangelMaxime** [vlang/v#7074]
**V version:** V 0.1.30 c5cd53c, timestamp: 2020-12-01 18:59:33 +0100
**OS:** Windows 10

**What did you do?**

I run `v -g run .\repo.v` on Windows 10.
```
module main

import gg

fn main() {
	println('Starting the game loop...')
}
```

*Note: In my project, I actually have some code calling `gg` but just importing it is enough for the reproduction.*

**What did you expect to see?**

Program should compile. 

**What did you see instead?**

The program doesn't compile.

```
.\repo.v:5:8: warning: module 'gg' is imported but never used
    3 | module main
    4 |
    5 | import gg
      |        ~~
    6 |
    7 | fn main() {
recompilation with tcc failed; retrying with cc ...
C compilation failed.
builder error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: gcc @C:\Users\Maxime\AppData\Local\Temp\v\repo.1497925209216856393.tmp.c.rsp
```

The program does compile, if I run `v -cc msvc -g run .\repo.v`. Before, I didn't have to explicitly tell v to use `msvc` it was choosing it by default on Windows.

I tracked the regression from this https://github.com/vlang/v/pull/6598

I also saw that if `tcc` compilation fails then v fall back to `gcc` on Windows. 

https://github.com/vlang/v/blob/c5cd53ca79420e704e44c5611926311f557cdb0e/vlib/v/pref/default.v#L128-L138

Is it the expected behaviour? Before, I guess it was using `msvc` by default on Windows. 

I also prefer `msvc` because from my experience msvc compilation is faster that gcc. gcc on my computer always hug for 2-3sec while msvc is instant.

I am just starting to code in v and in c, so I don't really know if that's normal/expected.

**Comment by JalonSolov** [comment]
It is by design.  It used to use whichever C compiler it found in your path.  Now, if you do not explicitly use `-cc <compiler>` option, or  `-prod` switch, it will always use tcc compiler installed in thirdparty/tcc directory.  With `-prod` it will always try to run gcc... again, unless you use the `-cc <compiler>` option.   (On non-Windows systems, it will run  `cc`.)

I'm not sure why `gcc` was chosen over `msvc` on Windows.  Seems like it should use the old logic with `-prod` and use the one it finds in your path.

**Comment by medvednikov** [comment]
Yes it should use msvc by default if it's installed @spytheman
