### ISSUE TITLE
Make comptime $if work with consts

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#7165]
This should compile even though the second branch uses a wrong function definition:

```
const (
  version = 2
)

fn add(x int, y int, z int) int {
    return x + y + z
}

fn main() {
    $if version == 2 {
        res := add(1, 2, 3)
    }
    $else {
        res := add(1, 2)
    }
}
```

Also I'm not sure if we should require $if explicitly (like `if constexpr() {` in C++) or just make `if version == 2 {` magically work.

**Comment by dumblob** [comment]
Any downsides to the "magically working" variant? I didn't put much thought in that, but I can't think of any off the head. Feel free to elaborate :wink:.

I actually incline to think, that smooth transition from a runtime code to compile time code should be a priority. And explicitly marking such places doesn't seem to support this vision.

**Comment by medvednikov** [comment]
"Explicit is better than implicit" is one V's main philosophies.

Hence the mandatory `mut` args, mandatory returns etc.

**Comment by dumblob** [comment]
>"Explicit is better than implicit" is one V's main philosophies.

Sure, but:

1. They're all backed by well known risks when programming - unlike compile time evaluation which is generally considered of low-risk issue (as it basically boils down just to performance in critical cases which is easily testable by unit tests, benchmarks, profiling, etc.).

2. There are many **implicit** places in V where computation happens in compile time. Making `if version == [1, 2, 3] {` require `constexpr()` but `if [1, 2, 3] == [1, 2, 3] {` not (i.e. any - including compound - literals) does look like a much bigger issue than not requiring `constexpr()` (but e.g. making it optional - see below).

Btw. I've actually come up with one benefit of making it explicit: one doesn't want the source to compile if the given code block isn't evaluable in compile time (useful e.g. for time critical stuff in games, scientific libraries, etc.).

So making it explicit in some cases makes sense - though I'm pretty certain **requiring** `constexpr()` everywhere will either extremely bloat the code (due to every literal being marked as that - see (2) above) or will introduce awkward inconsistency (it'd be basically impossible to know where the line has been drawn - is the operator `+` in between of two float literals compile time or not assuming [there is a defined behavior erasing differences between FPU behaviors on the dev machine and deploy machine](https://github.com/vlang/v/issues/5180#issuecomment-675732199 ) and thus the `constexpr()` has to be written there or not?) as in (2) above.

Maybe making it work in the "opposite direction" - namely pretty much as pass-by-value and pass-by-reference works in *V* - i.e. if there is nothing, it's solely up to the *V* compiler. But if there is `constexpr()`, then the compiler would guarantee it's evaluated in compile time (and error out if impossible).
