### ISSUE TITLE
It is 2 times faster if we use itoa() function for number to string.

### ISSUE THREAD

**Issue by lcddh** [vlang/v#7359]
```
import time

fn C.itoa()

fn main() {
  mut sw := time.new_stopwatch({})

  for i in 0..5000000 {
    //println(i.str())
    i.hex()
  }
  println('hex(): ${sw.elapsed().milliseconds()}')

  sw.restart()
  for i in 0..5000000 {
    //println(itoa(i,16))
    itoa(i,16)
  }
  println('itoa(): ${sw.elapsed().milliseconds()}')
}

fn itoa(n int, radix int) string {
  s := [32]byte{}
  C.itoa(n, s, radix)
  return unsafe {byteptr(s).vstring()}
}
```
![image](https://user-images.githubusercontent.com/5841609/102374154-f7b35b80-3ffb-11eb-9cda-147cb6778127.png)

**Comment by JalonSolov** [comment]
I get this with the latest version of V:
```
==================
/tmp/v/foo.8073255529886412121.tmp.c: In function ‘main__itoa’:
/tmp/v/foo.8073255529886412121.tmp.c:9464:2: error: implicit declaration of function ‘itoa’ [-Werror=implicit-function-declaration]
 9464 |  itoa(n, s, radix);
      |  ^~~~
cc1: some warnings being treated as errors
...
==================
```

**Comment by changrui** [comment]
my output is:
```
hex(): 511
itoa(): 248
```

**Comment by JalonSolov** [comment]
Yes, like everything else, it depends greatly on your hardware, which C compiler is used, whether or not `-prod` is used, etc.

**Comment by UweKrueger** [comment]
From [Wikibook](https://en.wikibooks.org/wiki/C_Programming/stdlib.h/itoa):
*The itoa (integer to ASCII) function is a widespread **non-standard** extension to the standard C programming language. It **cannot be portably used**, as it is not defined in any of the C language standards...*

Furthermore: if available (on Windows, maybe?), the second parameter is a pointer to a pe-allocated buffer. Your `itoa()` uses a stack buffer and returns its address. This is a not go! Once `itoa()` finishes, this stack area is no longer reserved and will be used by something else, so the string is no longer valid. You test case only works because you are not using the generated strings.

V's `.hex()` does heap allocation for the buffer referenced by the `string` it returns. This is time consuming by itself (and might be the most expensive part) - but necessary, since this way the buffer remains valid after `.hex()` has finished.

For a fair comparison your test case should at least do heap allocation.

**Comment by medvednikov** [comment]
You should simply replace `s := [32]byte{}` with `s := malloc(32)` and try again.
