### ISSUE TITLE
running v as REPL, window reports virus

### ISSUE THREAD

**Issue by gshields** [vlang/v#7379]
50_000/45

![image](https://user-images.githubusercontent.com/3464355/102559272-4dcbe180-4084-11eb-83bd-98b2bd3f7230.png)

V 0.1.30 b9edbf7

window 10 20h2 build 19042.685
 gcc --version
clang version 11.0.0 (https://github.com/llvm/llvm-project.git 176249bd6732a8044d457092ed932768724a6f06)
Target: x86_64-w64-windows-gnu
Thread model: posix

recompiling with  gcc --version
gcc.exe (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.

and could not reproduce problem.

**Comment by JalonSolov** [comment]
Sounds like a problem in v11 gcc for Windows, adding something the virus check doesn't like.

I've been using gcc downloaded from https://winlibs.com - 10.2.0 is latest version there, and it has been working fine (with no problem like you saw).  Since it worked for you using a different version of gcc, that means the problem isn't in V.

**Comment by gshields** [comment]
Thank you for the reply

I was going to try your compiler (since the mingw gcc is an older 8.0
version) but that website is not secure with either firefox or chrome

[image: image.png]
