### ISSUE TITLE
How do you generate VC?

### ISSUE THREAD

**Issue by IngwiePhoenix** [vlang/v#7571]
This is a pretty simple question but I hadn't found a better place to ask at.

So basically I wonder how you are generating the VC repository, more specificaly, `v.c`. Would it be possible to even compile V without obtaining a V compiler first?

I am just curious about this because I know this kind of mechanic from D: You need an older-ish version of D to build D. Same seems to go for V: You need an older-ish - or recent, since `v.c` is auto generated off recent commits - version of V to compile V.

Say the `vc` repo is broken for some reason: How would you bootstrap V __without__ the pre-created `v.c`?

**Comment by JalonSolov** [comment]
Something like this...

New version of V is built.  Then `v -o v.c self` is run, and that output is checked in.

If things go bust, just clone v.c and build it with `cc v.c` and you have V back.

The only way things would go completely south is if you lost the `vc` repo, the `v` repo, and every copy of `v` on everyone's machines.

Plus all the backups, etc.

Since `v.c` is built by `v`, it is kept up-to-date.  No need for an older version of V to build anything.

**Comment by IngwiePhoenix** [comment]
I see. So you can't build V without VC at all. Thank you!

In D it would, in theory, be possible to chain-build between a couple of versions from an old version all the way to the new one by only having a C compiler - for V, you can't do that but have to rely on an existing `v.c` - or `v_win.c` instead. Good to know. ^^

**Comment by JalonSolov** [comment]
Almost... you can build V as much as you want as long as V is available.  `v.c` is there are a fail-safe, to bootstrap if V is not available.
