### ISSUE TITLE
`os.file_name` doesn't work correctly on Windows

### ISSUE THREAD

**Issue by pavi2410** [vlang/v#7690]
On Windows, `/` is a valid path-separator. It should be converted to `\` internally for compatibility.

### Actual
```
>>> file := 'a/b/c'
>>> os.file_name(file)
a/b/c
```

### Expected
```
>>> file := 'a/b/c'
>>> os.file_name(file)
c
```

https://github.com/vlang/v/blob/6cf3b96a379e5d1bb3dccc77f0c21237b49db613/vlib/os/os.v#L214

**Comment by dumblob** [comment]
>It should be converted to `\` internally for compatibility.

I'm not exactly sure about this. What do you mean by "compatibility". Could you give us some examples?

I'm asking because if `/` is fully supported by Windows (which it **is**), then I think using `/` is by definition **fully** compatible with anything Windows-related. If it's not the case, then it's a bug there where `/` is not being supported.

Of course, if there are any notable existing SW solutions or apps which have issues with `/`, I'd probably accept converting `/` internally to `\` always. But currently I'm not convinced :wink:.

**Comment by pavi2410** [comment]
It's `v bin2v` which has a problem with `/`

**Comment by felipensp** [comment]
Already solved.
