### ISSUE TITLE
ternary value cannot be used in expressions

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#8088]
**V version:** 
master

**OS:**
win10 

**What did you do?**
```V
fn main() {
	str := if true { 'V' } else { ' ' } + ' is awesome'
	println(str)
}
```

**What did you expect to see?**
`V is awesome`
 
**What did you see instead?**
```V
sample.v:3:38: error: mismatched types `void` and `string`
    1 |
    2 | fn main() {
    3 |     str := if true { 'V' } else { ' ' } + ' is awesome'
      |                                         ^
    4 |     println(str)
    5 | }
```

**Comment by bartimus-primed** [comment]
I'm confused, should that work?
I'm not sure how it's parsed, but if it did allow it, wouldn't it have to be considered mutable?
`fn main() {
	mut str := if true { 'V' } else { ' ' }
	str += ' is awesome'
	println(str)
}`

In most languages wouldn't the line bail before it even hits the else, since it's true?

**Comment by SleepyRoy** [comment]
@bartimus-primed Yes the `else` block in my code won't be hit because condition in `if` is true, but IMO it is unrelated to this issue.
I don't think the `str` should be declared with `mut` in my case, because compiler should parse it as
```V
str := (if true { 'V' } else { ' ' }) + ' is awesome'
```
which is essentially equal to
```V
str := 'V' + ' is awesome'
```
IMO `mut` should be used only if a variable is going to be changed **after** declaration.

**Comment by bartimus-primed** [comment]
@SleepyRoy 
yeah, I just wasn't sure if it hits the "if true { 'V' }" and assigns the value without parsing the rest of the line, as an optimization or something, which would then give the error "error: mismatched types `void` and `string`" since it already assigned the value.
I get what you are saying though. Also as a note if you do this on wasm (https://v-wasm.now.sh/) the error is:

main.v:2:38: error: bool types only have the following operators defined: `==`, `!=`, `||`, and `&&`

not sure if this is due to wasm being a different version or the emscripten conversion.

**Comment by ntrel** [comment]
On Discord they said this does work:
```v
ret := 3 + if true {4} else { 0 } + 2
```
But deleting '3 + ' doesn't, like with string here.
