### ISSUE TITLE
$if aarch64 {} else {} doesn't generate else statements

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#8644]
```v
$if aarch64 {
        println('yes')
} $else {
        println('no')
}
```

results in

```
#if defined(__V_aarch64)
{
        println(_SLIT("YES"));
}
#else
{
}
#endif
```

**Comment by spaceface777** [comment]
This is by design imho - V skips any unreachable statements after an `$if` branch matching the current target platform is found. Say you have code like this:
```v
$if windows {
    mymodule.windows_specific_fn()
} $else {
    mymodule.unix_specific_fn()
}
```

If you're compiling on windows, you'd want `unix_specific_fn` to not be resolved - it might be defined inside a `_nix.c.v` file, which would not be parsed, and then you'd get `function does not exist` errors. The same logic applies the other way - on a unix-based OS, you wouldn't want the windows-specific code to even be checked.

If you do want to produce code including all platforms (for cross-compiling or whatever), afaik you can use `v -os cross ...`, and in that case V *will* generate every `$if` branch (that is what v.c does afaik).

**Comment by ntrel** [comment]
> If you're compiling on windows, you wouldn't want unix_specific_fn to be resolved

And it wouldn't be, the C pre-processor would remove that code. V is prematurely removing it - the C code could be kept and used on a different platform.

**Comment by spaceface777** [comment]
> the C pre-processor would remove that code

it actually wouldn't, because the V type checker would've printed an `unknown function` error, and no C code would've even been generated :)

> the C code could be kept and used on a different platform

Again, you can use `v -os cross -o file.c ...`, and then you *will* get the complete C file, with all branches included.

**Comment by medvednikov** [comment]
Yeah it makes sense to only enable it for cross compilation.

**Comment by Wertzui123** [comment]
Wouldn't it make sense to remove the C preprocessor statement (`defined(__V_aarch64`) then?
It suggests that this may be true or not, but since the else code is never generated, this C code is not platform-independent and `__V_aarch64` **must** be defined.

**Comment by felipensp** [comment]
This seems has been fixed. Now it generates:

```C
        #if defined(__V_arm64)
        {
        }
        #else
        {
                println(_SLIT("no"));
        }
        #endif
 ```
