### ISSUE TITLE
shared/mut error messsages

### ISSUE THREAD

**Issue by abrandoned** [vlang/v#8685]
OS: macos, macOS, 11.2.1, 20D74
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 12.0.0 (clang-1200.0.32.29)

is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 9b4f2ed

**What did you do?**

```
import sync

fn main() {
  shared shared_map := &map[string]int{}
  do_stuff(shared_map)
}

fn do_stuff(shared shared_map map[string]int) {
  println(shared_map)
}
```

**What did you expect to see?**

Expected compilation error message to reference "shared" instead of "mut" because of the declaration of the map; made troubleshooting difficult
 
**What did you see instead?**
```
v shared_message.v
shared_message.v:5:12: error: `do_stuff` parameter `shared_map` is `mut`, you need to provide `mut` e.g. `mut arg1`
    3 | fn main() {
    4 |   shared shared_map := &map[string]int{}
    5 |   do_stuff(shared_map)
      |            ~~~~~~~~~~
    6 | }
    7 |
```

if the error advice is followed and 'mut' is prefaced at the call site then additional error

```
 v shared_message.v
shared_message.v:5:16: error: wrong shared type
    3 | fn main() {
    4 |   shared shared_map := &map[string]int{}
    5 |   do_stuff(mut shared_map)
      |                ~~~~~~~~~~
    6 | }
    7 |
```

**Comment by UweKrueger** [comment]
Please be aware that `shared` types are still work in progress, so not everything works, not everything is checked and error messages are sometimes misleading. We are aware of that and we are actively working to improve that.

"wrong shared type" means you should specify `shared shared_map` instead of `mut shared_map`. However, if you do so, you'll come into the next problem that `println()` doesn't work for `shared` objects, yet. What you can do for now is:
```v
fn main() {
    shared shared_map := map[string]int{}
    lock shared_map {
        shared_map['xyz'] = 42
    }
    do_stuff(shared shared_map)
}

fn do_stuff(shared shared_map map[string]int) {
    rlock shared_map {
        println(shared_map.len)
        println(shared_map['xyz'])
    }
}
```

**Comment by felipensp** [comment]
Already fixed.
