### ISSUE TITLE
More integrated WaitGroup support for concurrency

### ISSUE THREAD

**Issue by mcastorina** [vlang/v#8774]
First off, I just started learning V a few days ago and I am really impressed, so thank you for making, developing, and maintaining this awesome language! Now for the feature request :)

One common use-case in Go is wrapping a function call with a closure to call `wg.Done()` after the function finishes:

```go
var wg sync.WaitGroup
wg.Add(1)
go func() {
    defer wg.Done()
    doSomething()
}()
wg.Wait()
```

I think something similar could be accomplished in V once closures are supported, but since it is such a common use case, it would be nice to simplify the syntax. I think using the following would be nice:

```v
go doSomething() and { wg.done() }
```

The advantage of this is that it reads logically and it is similar to the `or { }` syntax for Option / Result.

Here is a full example (taken from the docs):

```v
import sync
import time

fn task(id int, duration int) {
	println('task $id begin')
	time.sleep_ms(duration)
	println('task $id end')
}

fn main() {
	mut wg := sync.new_waitgroup()
	wg.add(3)
	go task(1, 500) and { wg.done() }
	go task(2, 900) and { wg.done() }
	go task(3, 100) and { wg.done() }
	wg.wait()
	println('done')
}
```

**Comment by dumblob** [comment]
Hm, someone would probably argue, that such thing is also common in many other scenarios as it's very similar to e.g. Python's `with x, y, z:`. Others would probably say that it's too simple and not enough repetitive for yet another syntax and that it violates the `there is only one way of doing things in V` rule (because this special syntactic sugar could be easily replaced with the usual syntax).

Let's see where the discussion brings us :wink:.

**Comment by mcastorina** [comment]
Related: https://github.com/vlang/v/issues/8301

I like the idea of using the append operator even better because it would also automatically run `wg.add(1)` before spawning the thread. I'm not sure if that's possible though, since `go` returns a handle and `wg` needs to be incremented *before* the thread spawns.

**Comment by mcastorina** [comment]
Implemented with https://github.com/vlang/v/pull/8840
