### ISSUE TITLE
V cannot run symlinked vsh scripts when the symlink doesn't end with .vsh

### ISSUE THREAD

**Issue by serkonda7** [vlang/v#9313]
**V version:** V 0.2.2 5cfe55b
**OS:** Kali

**What did you do?**
- Create this script (`foo.vsh`):
    ```v
    #!/usr/bin/env -S v run
    println(@FILE)
    ```
- `chmod +x ./foo.vsh`
- Create a symlink to it named `foo`
- Execute the symlink

**What did you expect to see?**
The path of the original file should be printed.
 
**What did you see instead?**
```
usage: `v file.v` or `v directory`
unknown file extension ``
```

**Comment by Larpon** [comment]
I've provided a fix for this in #9385 .

I couldn't test with `#!/usr/bin/env -S v run` on my Ubuntu 18.04 system since `env` errored on the `-S` flag.
So I had to modify it to use `#!/usr/local/bin/v run`.

Another issue that might have been discovered is that V errors if the ***symlinked*** `.vsh` doesn't have a `main()` - I'm not sure why this is not working.

So I had to change your code
from:
```
#!/usr/local/bin/v run
println(@FILE)
```

to:

```
#!/usr/local/bin/v run
fn main() {
	println(@FILE)
}
```
for #9385 to work.
