### ISSUE TITLE
More robust documentation on the memory management.

### ISSUE THREAD

**Issue by m-kru** [vlang/v#9461]
In the docs section on the [Memory management](https://github.com/vlang/v/blob/master/doc/docs.md#memory-management) one can read.

> Most objects (~90-100%) are freed by V's autofree engine: the compiler inserts necessary free calls automatically during compilation. Remaining small percentage of objects is freed via reference counting.

Is there anywhere more robust documentation that would explain:
1. What objects are not auto freed by the autofree engine?
2. Who and how  does decide if an object can be freed by the autofree engine? Is it the developer or the compiler?
3. How the reference counting is done?

**Comment by JalonSolov** [comment]
1. autofree is still a work in progress.  There is no fixed list of what is or is not freed by the autofree engine because that changes as autofree is improved to cover more things.
2. The compiler.  Hence the "auto" part of "autofree".  If the developer wants to do it, they can mark things with `[manualfree]`.
3. The standard way.  Each new reference increases the count.  Each reference going out of scope decreases the count.  When the count reaches 0, the object is freed.

**Comment by danieldaeschle** [comment]
Duplication of https://github.com/vlang/v/issues/274
