### ISSUE TITLE
[Bug] `println` refuses to print large number

### ISSUE THREAD

**Issue by guekho64** [vlang/v#9507]
# What did you do?

``` v

module main

fn main () {
 println(i64(0x8000000000000000))
}

```

# What did you expect to see?

``` v

-9223372036854775808

```

# What did you see instead?

Literally nothing

# Additional Info

* No warnings / errors when executing with `v run Test.v` nor `v Test.v && ./Test`
* Tested against `Weekly V 0.2.2 7664964` and `Stable V 0.2.2 46cdf4f`
* Using `Ubuntu 20.04.2 LTS -> Kernel: 5.8.0-48-lowlatency`
* Possibly related to #3751 (Although this bug persists even when executing a successfully compiled binary)

**Comment by Carpall** [comment]
I'm not a fan of vlang, I found this issue in VLang Memes (wip), so I don't known if vlang compiles also to LLVM Bitcode, anyway the problem is linked to native version of binary, it seems to work perfectly in playground with wasm interpreter (executed in msedge)
![image](https://user-images.githubusercontent.com/65513900/113178695-1ce87480-924f-11eb-91f0-c2264f02fb5a.png)

**Comment by guekho64** [comment]
Apparently, you've just discovered a new/related bug: [Playground](https://v-wasm.now.sh/) seems to be broken as well, probably even more than native `v`. Haven't checked on Windows, but this doesn't look promising...

These should be the correct results:

``` v

int(0xffffffff) == -1
i64(0x8000000000000000) == -9223372036854775808

```

![image](https://user-images.githubusercontent.com/8020999/113322446-edc71700-92d1-11eb-918b-1e56afd87f81.png)

**Comment by ArtemkaKun** [comment]
Actual V (0.3.2):

```v
module main

fn main() {
	println(i64(0x8000000000000000) == -9223372036854775808)
}
```

```
true
```

Fixed
