### ISSUE TITLE
sum types, discriminated unions, tagged unions + exhaustiveness

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [vlang/v#955]
enums is the only sum type that is currently in v
are there any plans to allow arbitrary yet discriminated unions?
if so, will there be a way to do exhaustive handling?

**Comment by medvednikov** [comment]
Hi

The answer is yes to everything.

**Comment by hillerstorm** [comment]
@medvednikov now that Sum types are in and I've been playing around with them I really feel like the `else` case shouldn't be required when matching on them. IMO the beautiful thing with exhaustiveness and sum types are the fact that adding a type to the sum type gives compiler errors everywhere where you have missed implementing it.
Helps catching errors that would just creep under the radar due to the catch-all in `else`.

Having coded some Elm in the past, this was one of the most helpful things when refactoring in that language, having the compiler helping you handle all cases.

**Comment by medvednikov** [comment]
Good point @hillerstorm.

I think exhaustiveness should still be required, but without `else`.

**Comment by medvednikov** [comment]
Closing, since V now has

`type Expr = IfExpr | MatchExpr | StringLiteral`
