### ISSUE TITLE
V 0.1.12 can finally compile itself on Windows. If you were having issues, please check it out.

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#970]
It works, at least on my VM with MinGW-w64.

You have to follow these instructions to build it from source: 

https://github.com/vlang/v#mingw-w64

The prebuilt binary and Visual Studio instructions will be available tomorrow.

**Comment by changrui** [comment]
Yes, I got it. Thanks, Mr. Alex.

**Comment by MaD70** [comment]
`v.c` compiles correctly but running it gives again this damned message:

> Looks like you are running V for the first time.
> V repo not found. Go to https://vlang.io to download V.zip
> or install V from source.

@medvednikov can you please specify **exactly** where the hell the compiler is searching the content of `V.zip`? I supposed, glancing at the compiler sources, under `C:\Users\<user name>\.vlang` (the name of the home directory in File Explorer is translated to the national language of the installation, but it's always accessible as `C:\Users\<user name>\`). Well I tried putting the content of the `V.zip` there, added the directory to `PATH` and nothing changed, still the same message.

As I wrote in https://github.com/vlang/v/issues/918#issuecomment-507479628 this is **not** the way we do things traditionally on Windows (and I suggested a way to solve this problem — not with a Pull Request because I hadn't the time to study the compiler sources yet —  which anyway is compatible with putting things under home directory). If nonetheless you want to use the home directory concept at least instruct us **exactly** where to put things.

Thank you.

**Comment by medvednikov** [comment]
@MaD70 where did you clone the repo to? Make sure there are no spaces in the path.

**Comment by medvednikov** [comment]
Visual Studio instructions are live:

https://github.com/vlang/v/wiki/Installing-V-from-source-on-Windows

**Comment by MaD70** [comment]
@medvednikov I haven't cloned the repo, I have downloaded `V.zip`. I supposed that the instructions printed by compiler are up-to-date. I have put the content of `V.zip` under `C:\Users\<my_name_here>\.vlang` no spaces in the path (and when there are spaces it usually suffices to put it between double quotes).

**Comment by medvednikov** [comment]
Ah, so that's why you are getting this.

You should clone it. The v.zip contains files with nix line endings, they don't work on Windows. This will be fixed today, but you should just `git clone` for now.

**Comment by medvednikov** [comment]
Sorry about the wrong instructions in the compiler, forgot to update them.

**Comment by MaD70** [comment]
@medvednikov I finally had success in compiling `hello_world.v`

My friend if you aren't careful with instructions you'll drive people mad and you'll loose a lot of time trying to diagnose stupid problems: after cloning the repo and building the compiler, **I had to put the executable of the compiler exactly in the root of the clone repo**.

Instead in [Installing V from source on Windows](https://github.com/vlang/v/wiki/Installing-V-from-source-on-Windows) after cloning the repo you change dir (`cd v`) and you build the compiler and execute it from there. But from there it never find the cloned repo and set `VROOT`! So I thought the compiler were searching the repo in `C:\Users\<user name>\.vlang` (I now understand that it's just a temporary build directory).

**Comment by medvednikov** [comment]
The bug with the newlines was fixed, V.zip now has a working v_windows.exe.
