### ISSUE TITLE
Interface cast doesn't work

### ISSUE THREAD

**Issue by fieryorc** [vlang/v#9755]
Interface casting doesn't appear to work. 

**V version:** V 0.2.2 60bc280
**OS:** MacOS

**What did you do?**
```
interface Any{}
interface Any2{}
struct Foo {}

fn main() {
 f := Any(Foo{})
 if f is Any2 {
	 println('Hello')
 }
}
```

**What did you expect to see?**
Print Hello
 
**What did you see instead?**
```
> v ./iface.v && ./iface
./iface.v:7:5: error: cannot implement interface `Any` with a different interface `Any2`
    5 | fn main() {
    6 |  f := Any(Foo{})
    7 |  if f is Any2 {
      |     ~~~~~~~~~
    8 |      println('Hello')
    9 |  }
```

**Comment by spaceface777** [comment]
I don't think that's how interfaces work in V, but that error message isn't very clear.

**Comment by leighmcculloch** [comment]
I'm seeing the same issue when I've given a function an io.ReaderWriter and that function wants to pass on that io.ReaderWriter as an io.Reader to another function. This is a logically sane thing to do, after-all the value inside the io.ReaderWriter implements both io.ReaderWriter and io.Reader since io.Reader is a subset of io.ReaderWriter.

The docs say the following about interfaces:
https://github.com/vlang/v/blob/c21df2d44cf49bbc2333e7e33bf400c542835c8b/doc/docs.md#L2218

Upon reading this ☝🏻 my assumption is that the value I'm passing around wrapped in an io.ReaderWriter would coerce to io.Reader since it implements io.Reader.

I think without this capability it will be difficult to compose using interfaces, which is something that is very easy to do in Go.

> I don't think that's how interfaces work in V

If that is the case then I think we should add some more details in the docs and in the comparison with Go located here: https://vlang.io/compare#go.

@spaceface777 Could you elaborate about how they work? Thanks!

**Comment by spaceface777** [comment]
@leighmcculloch that's a different issue - please open a new issue so that it can b

The issue you're describing is

**Comment by kahsa** [comment]
This works now, can be closed.
