### ISSUE TITLE
ORM blocks should support multiple statements

### ISSUE THREAD

**Issue by rheber** [vlang/v#9837]
First attempt:

```
// example.v

import sqlite

struct Table1 {
	id int
}

struct Table2 {
	id int
}

fn main() {
	db := sqlite.connect(':memory:') or { panic(err) }
	sql db {
		create table Table1
		create table Table2
	}
}
```

Result of `v run example.v`:

```
example.v:17:3: error: unexpected name `create`, expecting `}`
   15 |     sql db {
   16 |         create table Table1
   17 |         create table Table2
      |         ~~~~~~
   18 |     }
   19 | }
```

Second attempt:

```
// example2.v

import sqlite

struct Table1 {
	id int
}

struct Table2 {
	id int
}

fn main() {
	db := sqlite.connect(':memory:') or { panic(err) }
	sql db {
		create table Table1;
		create table Table2;
	}
}
```

Result of `v run example2.v`:

```
example2.v:16:22: error: unexpected token `;`, expecting `}`
   14 |     db := sqlite.connect(':memory:') or { panic(err) }
   15 |     sql db {
   16 |         create table Table1;
      |                            ^
   17 |         create table Table2;
   18 |     }
```

I know that you can work around this by writing one block per statement but I wouldn't expect to need to do that.

**Comment by VinWare** [comment]
One related suggestion - make every sql db block a transaction.

**Comment by dumblob** [comment]
> One related suggestion - make every sql db block a transaction.

I'm not exactly opposed to this idea, but I find it difficult, because databases support wildly differing transactional guarantees (see file locking, power loss, commit policies, buffering policies, network guarantees, isolation guarantees, multiprocess & multithreaded guarantees, etc. e.g. in PostreSQL or even SQLite to gain a rough impression about the extreme breadth this is all about), that even finding the least common denominator might become impossible if the API wants to **guarantee** a certain useful set of capabilities.

In my SQL library I've solved this by choosing only **one SQL backend** and I'm supporting only a small subset of the most common transactional "combinations".
